// ELL12 U1 L05 — Words That Show (adjectives and the five senses). ALL content here; the renderer holds the design.
// Rebuilt Sep 21 2026 from the v13 L06 deck + Core sheets, to the standing orders and the taught L04 v2 deck.
// Unit order now: L1 Welcome · L2 The Simple Sentence · L3 Nouns & Articles · L4 Where Things Are · L5 this · L6 Joining Ideas
const bankWords = ["touch", "detail", "hear", "adjective", "taste", "describe", "see", "smell"];
const vocab = [
  ["adjective", "a word that describes a thing (warm, loud, sweet)"],
  ["see", "what your eyes notice"],
  ["hear", "what your ears notice"],
  ["smell", "what your nose notices"],
  ["taste", "what your tongue notices"],
  ["touch", "what your skin feels"],
  ["describe", "to say what something is like"],
  ["detail", "a small, exact thing you notice"]];
const helpLine = "Stuck? Fill in a help slip: \u201CCan you check my \u2026?\u201D  \u201CI need help with \u2026\u201D";

module.exports = {
 course: "ELL12",
 meta: { unit: 1, unitTitle: "Who I Am", lesson: 5, title: "Words That Show", subtitle: "Adjectives and the five senses", month: "September" },
 banner: { obj: "Use adjectives and the five senses to show a place, not just name it.",
   std: "ELL 1: W1 simple sentences \u00B7 W7 familiar words  \u2022  ELL 2: W1 simple sentences \u00B7 W7 capitals and punctuation", lit: ["COM", "TH"] },
 plan: {
  objective: "Students move from telling (\u2018it is nice\u2019) to showing, with adjectives and a sense detail \u2014 the skill the descriptive piece rests on.",
  outcomes: "ELL 1: W1 simple sentences \u00B7 W7 familiar words and phrases. ELL 2: W1 simple sentences \u00B7 W7 capitals and punctuation.",
  materials: "Deck \u00B7 ELL 1 and ELL 2 Lesson 5 worksheets, one each plus spares \u00B7 exercise books \u00B7 help slips in the box \u00B7 three or four foods in mind to describe for the game",
  timing: "80 minutes",
  steps: [
   ["10", "Warm-up Parts A and B", "In exercise books. Part A \u00B7 Vocabulary: ten sense adjectives per level from a shuffled bank. Part B \u00B7 Grammar: ELL 1 uses am, is or are with an adjective; ELL 2 moves the adjective in front of the noun. Show all ten, then reveal one at a time, alternating ELL 1 and ELL 2."],
   ["3", "Warm-up: write it", "Two sentences about this room with an adjective in each; ELL 2 uses two different senses. Show the one example answer and take two or three aloud."],
   ["7", "Guess the food", "Describe a food with your senses without naming it (it is hot, it smells sweet, it is soft). Students guess with the frames. After two or three rounds, partners take turns. Leave the instructions and frames slides up while they play. English only."],
   ["2", "Title and goals", "Read the three goals. Name the big idea: show with your senses; do not just say nice."],
   ["6", "Teaching 1: the five senses", "One row per sense with its adjectives. Ask the class for one more adjective for each sense before moving on."],
   ["6", "Teaching 2: telling and showing", "\u2018The kitchen is nice\u2019 against sentences with an adjective and a sense. Ban nice and good as describing words for the rest of the unit. Then the ELL 1 and ELL 2 examples."],
   ["8", "Match the word", "Eight words against meanings from a shuffled bank, revealed one at a time, then the summary slides and a partner talk with sense words. English only."],
   ["8", "Lina\u2019s kitchen", "Read My Kitchen (ELL 1) and The Sunday Kitchen (ELL 2) in full, then side by side. Students find one detail for each sense, then reveal."],
   ["10", "Worksheet Parts A and B", "Hand out both sheets. Show the full pages, then walk Part A and Part B for each level with the worked example, revealing one answer at a time."],
   ["4", "Describe it with two senses", "Partners pick one thing in the room and describe it with two senses; the partner guesses. English only."],
   ["10", "Part C independent writing", "Walk Part C for each level and show one good answer. ELL 1 rewrites each sentence with an adjective added; ELL 2 rewrites telling sentences so they show. Circulate with help slips; push every nice and good back."],
   ["6", "Check and exit ticket", "Part D tick-box check, then the Part E exit ticket on the sheet, with one example answer per level. Next class, then agendas."] ],
  diff: "Support: the five-senses slide can go back up during Part C, and ELL 1 may take adjectives from the warm-up bank. Extension: ELL 2 early finishers add a third showing sentence about their own kitchen, using a sense they have not used yet.",
  assess: "Formative. Part C shows who can move from telling to showing (ELL 2) or add a fitting adjective (ELL 1). The exit ticket is the quick check. Not marked.",
  homework: "Finish Part C if it is not done.",
  watch: "Students naming a feeling (it is nice, it is good) instead of a sense detail \u2014 push it back: show me with your nose or your ears. In ELL 1 Part C, watch for the adjective after the noun (the radio old)." },
 shape: [["Warm-up: words and grammar", "quick practice"], ["Guess the food", "guessing game"], ["The five senses", "mini-lesson"],
   ["Telling and showing", "mini-lesson"], ["Match the word", "vocabulary game"], ["Lina\u2019s kitchen", "reading"],
   ["Worksheet Parts A and B", "worksheet"], ["Describe it with two senses", "partner speaking"],
   ["Part C: show it", "independent writing"], ["Check and exit ticket", "quick write"]],
 sequence: [
  { type: "drill", part: "A", kind: "Vocabulary", lvls: [
    { lvl: "ELL 1", bankLabel: "Word bank \u2014 one word in each blank", bank: "soft \u00B7 dark \u00B7 hot \u00B7 quiet \u00B7 bright \u00B7 wet \u00B7 cold \u00B7 salty \u00B7 loud \u00B7 sweet",
      items: [["Ice is very ____.", "cold"], ["A light bulb is ____.", "bright"], ["Fire is very ____.", "hot"], ["Candy tastes ____.", "sweet"],
        ["A library is ____.", "quiet"], ["Chips taste ____.", "salty"], ["A pillow feels ____.", "soft"], ["Rain makes the street ____.", "wet"],
        ["A drum is ____.", "loud"], ["The room at night is ____.", "dark"]] },
    { lvl: "ELL 2", bankLabel: "Word bank \u2014 one word in each blank", bank: "smooth \u00B7 crackling \u00B7 fresh \u00B7 sour \u00B7 humming \u00B7 cloudy \u00B7 bitter \u00B7 steaming \u00B7 sticky \u00B7 smoky",
      items: [["A lemon tastes ____.", "sour"], ["Honey on your fingers feels ____.", "sticky"], ["Bread from the oven smells ____.", "fresh"],
        ["A campfire smells ____.", "smoky"], ["Black coffee tastes ____.", "bitter"], ["A cup of hot tea is ____.", "steaming"],
        ["A window in a hot kitchen looks ____.", "cloudy"], ["Oil in a hot pan makes a ____ sound.", "crackling"],
        ["A fridge makes a low ____ sound.", "humming"], ["A new plate feels ____.", "smooth"]] } ] },
  { type: "drill", part: "B", kind: "Grammar", lvls: [
    { lvl: "ELL 1", bankLabel: "Use am, is or are", bank: "am \u00B7 is \u00B7 are",
      items: [["The soup ____ hot.", "is"], ["The apples ____ sweet.", "are"], ["I ____ cold.", "am"], ["The radio ____ loud.", "is"],
        ["My hands ____ wet.", "are"], ["The kitchen ____ bright.", "is"], ["We ____ tired.", "are"], ["The chips ____ salty.", "are"],
        ["My grandmother ____ quiet.", "is"], ["I ____ hungry.", "am"]] },
    { lvl: "ELL 2", bankLabel: "Put the adjective in front of the noun", bank: "The pan is hot.  \u2192  the hot pan",
      items: [["The rice is sticky.  \u2192  ____", "the sticky rice"], ["The window is cloudy.  \u2192  ____", "the cloudy window"],
        ["The song is soft.  \u2192  ____", "the soft song"], ["The tea is bitter.  \u2192  ____", "the bitter tea"],
        ["The radio is old.  \u2192  ____", "the old radio"], ["The bread is fresh.  \u2192  ____", "the fresh bread"],
        ["The steam is warm.  \u2192  ____", "the warm steam"], ["The rain is cold.  \u2192  ____", "the cold rain"],
        ["The broth is salty.  \u2192  ____", "the salty broth"], ["The spoon is wooden.  \u2192  ____", "the wooden spoon"]] } ] },
  { type: "rows", label: "Warm-up: write it", tag: "Warm-up \u00B7 write it", head: "Write two sentences", icon: "icon-book.png", big: "In your exercise book.", rows: [
    ["ELL 1", "Look around this room. Write two sentences. Use an adjective in each."],
    ["ELL 2", "Write two sentences about this room. Use two different senses."]] },
  { type: "rows", label: "Warm-up: example answer", tag: "Warm-up \u00B7 example answer", head: "One good answer", rows: [
    ["ELL 1", "The window is bright. My chair is hard."],
    ["ELL 2", "The old heater hums in the corner, and the air smells of pencils."]] },
  { type: "rows", label: "Guess the food", tag: "Warm-up game", head: "Guess the food: how to play", englishOnly: true, rows: [
    ["1", "I describe a food."], ["2", "Listen for sense words."],
    ["3", "Ask: \u201CIs it \u2026?\u201D"], ["4", "Then play with a partner."]] },
  { type: "speaking", label: "Guess the food: the describer", head: "The describer says", englishOnly: true, signAll: true,
    prompt: "Do not say its name.",
    frames: ["It is ______.", "It smells ______.", "It tastes ______.", "It feels ______."] },
  { type: "speaking", label: "Guess the food: the guessers", head: "The guessers say", englishOnly: true, signAll: true,
    prompt: "Ask a yes or no question.",
    frames: ["Is it ______?", "Does it taste ______?", "Yes, it is. / No, it isn\u2019t.", "Yes, it does. / No, it doesn\u2019t."] },
  { type: "title", label: "Today\u2019s lesson" },
  { type: "goals", label: "Today\u2019s goals", items: [
    "Say what an adjective is, and use one.",
    "Use the five senses: see, hear, smell, taste, touch.",
    "Show a place, not just say it is nice."] },
  { type: "rows", label: "The five senses", tag: "Teaching 1 of 2", head: "The five senses", rows: [
    ["See", "bright, cloudy, dark"], ["Hear", "loud, quiet, humming"], ["Smell", "sweet, fresh, smoky"],
    ["Taste", "salty, sour, bitter"], ["Touch", "soft, cold, sticky"]] },
  { type: "rows", label: "Telling and showing", tag: "Teaching 2 of 2", head: "Telling or showing?", rows: [
    ["Telling", "The kitchen is nice."], ["Showing", "The kitchen smells of garlic rice."],
    ["Showing", "The window is cloudy with steam."], ["The rule", "Nice and good tell us nothing. Use a sense."]] },
  { type: "rows", label: "Examples", tag: "Examples", head: "Adjectives at work", rows: [
    ["ELL 1", "The rice is hot."], ["ELL 1", "The radio is loud."],
    ["ELL 2", "Garlic rice crackles in the hot pan."], ["ELL 2", "Her grandmother\u2019s old radio hums a soft song."]] },
  { type: "match", label: "Match the word", head: "Match the word", bank: bankWords, words: vocab },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: vocab },
  { type: "speaking", label: "Say it with a sense", head: "Say it with a sense", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "Point. Say one sense word.",
    frames: ["I can see a ______ window.", "I can hear a ______ sound.", "It smells ______.", "It feels ______."] },
  { type: "prose", text: "k1", label: "My Kitchen" },
  { type: "prose", text: "k2", label: "The Sunday Kitchen" },
  { type: "text2", a: "k1", b: "k2" },
  { type: "rows", label: "Find the senses", tag: "Practice", head: "Find the senses in Lina\u2019s kitchen", rows: [
    ["See", "What does Lina see?"], ["Hear", "What does she hear?"], ["Smell", "What does she smell?"],
    ["Taste", "What does she taste?"], ["Touch", "What does she hold?"]] },
  { type: "rows", label: "Find the senses: answers", tag: "Practice \u00B7 answers", head: "In The Sunday Kitchen", rows: [
    ["See", "The window is cloudy with steam."], ["Hear", "Garlic rice crackles, and the rain taps on the glass."],
    ["Smell", "The kitchen still smells like home."], ["Taste", "Lina tastes everything first."],
    ["Touch", "She holds a wooden spoon."]] },
  { type: "handout", label: "Hand out the worksheet", note: "ELL 1 and ELL 2 sheets. Name and date first.",
    items: [["A", "find the adjective \u00B7 telling or showing"], ["B", "which sense?"], ["C", "write it again \u00B7 show it"], ["D", "check your work"], ["E", "exit ticket", true]],
    foot: "The sheet stays in your duotang." },
  { type: "walk", part: "1A-A", withExample: true }, { type: "reveals", part: "1A-A" },
  { type: "walk", part: "2A-A", withExample: true }, { type: "reveals", part: "2A-A" },
  { type: "walk", part: "1A-B", withExample: true }, { type: "reveals", part: "1A-B" },
  { type: "walk", part: "2A-B", withExample: true }, { type: "reveals", part: "2A-B" },
  { type: "speaking", label: "Describe it with two senses", head: "Describe it with two senses", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "Two senses. Your partner guesses.",
    frames: ["It looks ______.", "It sounds ______.", "It feels ______.", "Is it the ______?", "Yes, it is. / No, it isn\u2019t."] },
  { type: "walk", part: "1A-C", withExample: true }, { type: "reveals", part: "1A-C", good: true },
  { type: "walk", part: "2A-C", withExample: true }, { type: "reveals", part: "2A-C", good: true },
  { type: "walk", part: "1A-D" }, { type: "walk", part: "2A-D" },
  { type: "pages", label: "The whole sheet again" },
  { type: "exit", part: "1A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "1A-E", good: true },
  { type: "exit", part: "2A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "2A-E", good: true },
  { type: "nextshape", label: "Next class", head: "Next class: Joining Ideas", items: [
    ["Warm-up: words and grammar", "quick practice"], ["Two into one", "warm-up game"], ["and, but, so, because", "mini-lesson"],
    ["Two ideas, one sentence", "mini-lesson"], ["Match the word", "vocabulary game"], ["Say a joined sentence", "partner speaking"],
    ["Lina\u2019s kitchen", "reading"], ["Worksheet Parts A and B", "worksheet"], ["Part C: your joined sentences", "independent writing"],
    ["Check and exit ticket", "quick write"]] },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", icon: "icon-calendar.png", rows: [
    ["Next class", "Joining Ideas."], ["Homework", "Finish Part C if it is not done."], ["Remember", "Your worksheet goes in your duotang."]] } ],
 sheets: [
  { lvl: "ELL 1", suffix: "1A", label: "ELL 1", objective: "Add adjectives and sense words to simple sentences.",
    outcomes: "ELL 1  W7 Use familiar words and phrases  \u2022  W1 Write simple sentences", vocab,
    remember: "An adjective describes a thing. The five senses are see, hear, smell, taste and touch.", helpLine },
  { lvl: "ELL 2", suffix: "2A", label: "ELL 2", objective: "Turn telling sentences into showing sentences.",
    outcomes: "ELL 2  W1 Write simple sentences  \u2022  W7 Use capitalization and punctuation correctly", vocab,
    remember: "Showing beats telling. Replace flat words (nice, good) with an adjective and a sense detail.", helpLine } ],
 worksheet: { parts: [
  // ---------------- ELL 1 ----------------
  { key: "1A-A", lvl: "ELL 1", id: "A", title: "Find the adjective", kind: "cloze",
    instr: "Read each sentence. Write the adjective (the describing word) on the line.",
    example: { text: "The rice is hot.", ans: "hot", tail: "" },
    items: [{ text: "The radio is loud.", ans: "loud", tail: "" }, { text: "The steam is warm.", ans: "warm", tail: "" },
      { text: "The song is soft.", ans: "soft", tail: "" }, { text: "The window is cloudy.", ans: "cloudy", tail: "" },
      { text: "The kitchen is bright.", ans: "bright", tail: "" }],
    how: "Find the word that tells you what the thing is like. That word is the adjective. Write only that word." },
  { key: "1A-B", lvl: "ELL 1", id: "B", title: "Which sense?", kind: "cloze", newPage: true,
    instr: "Write the sense for each word. Use each bank word once, and cross it out when you use it.",
    bank: ["touch", "see", "taste", "hear", "smell"], bankCols: 5, crossed: ["taste"],
    example: { text: "sweet  \u2192", ans: "taste", tail: "" },
    items: [{ text: "loud  \u2192", ans: "hear", tail: "" }, { text: "bright  \u2192", ans: "see", tail: "" },
      { text: "smoky  \u2192", ans: "smell", tail: "" }, { text: "sticky  \u2192", ans: "touch", tail: "" }],
    how: "Ask: which part of my body notices this? Ears hear. Eyes see. Nose smells. Tongue tastes. Skin touches." },
  { key: "1A-C", lvl: "ELL 1", id: "C", title: "Write it again", kind: "lines", lines: 2,
    instr: "Write each sentence again. Add one adjective. Write the whole sentence.",
    example: { text: "The radio is on.", ans: "The old radio is on." },
    items: [{ text: "The rice is in the pan.", ans: "The hot rice is in the pan." },
      { text: "The window is beside the door.", ans: "The cloudy window is beside the door." },
      { text: "My grandmother sings a song.", ans: "My grandmother sings a soft song." },
      { text: "The kitchen smells of garlic.", ans: "The small kitchen smells of garlic." },
      { text: "I drink tea in the morning.", ans: "I drink sweet tea in the morning." },
      { text: "The cat sleeps on the bed.", ans: "The black cat sleeps on the bed." }],
    how: "Copy the whole sentence. Put one adjective in front of a thing: the old radio, a soft song. Do not use nice or good." },
  { key: "1A-D", lvl: "ELL 1", id: "D", title: "Check your work", kind: "check",
    instr: "Read your work again. Tick each box when it is true.",
    checks: ["I wrote the adjective in Part A.", "I matched each word to a sense.", "I wrote each sentence again with an adjective.",
      "I did not use nice or good.", "Each sentence starts with a capital letter.", "Each sentence ends with a period."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "1A-E", lvl: "ELL 1", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then show me before you leave.",
    items: [{ text: "Write one sentence about a thing in this room. Use an adjective.", reveal: "The big clock is on the wall." }],
    how: "One sentence. Name a thing and use one adjective. No nice or good." },
  // ---------------- ELL 2 ----------------
  { key: "2A-A", lvl: "ELL 2", id: "A", title: "Telling or showing?", kind: "cloze",
    instr: "Write T for a telling sentence or S for a showing sentence.",
    example: { text: "The kitchen is nice.", ans: "T", tail: "" },
    items: [{ text: "The garlic rice crackles in the hot pan.", ans: "S", tail: "" }, { text: "The food is good.", ans: "T", tail: "" },
      { text: "The sweet steam covers the cold window.", ans: "S", tail: "" }, { text: "The room is great.", ans: "T", tail: "" },
      { text: "The old radio hums a soft, off-key song.", ans: "S", tail: "" }],
    how: "A telling sentence uses a flat word: nice, good, great. A showing sentence lets you see, hear, smell, taste or touch something." },
  { key: "2A-B", lvl: "ELL 2", id: "B", title: "Name the sense", kind: "cloze",
    instr: "Each phrase uses a sense. Write which sense: see, hear, smell, taste or touch.",
    example: { text: "smells of garlic rice  \u2192", ans: "smell", tail: "" },
    items: [{ text: "a soft, off-key song  \u2192", ans: "hear", tail: "" }, { text: "the cloudy window  \u2192", ans: "see", tail: "" },
      { text: "the warm steam on my skin  \u2192", ans: "touch", tail: "" }, { text: "the salty broth  \u2192", ans: "taste", tail: "" },
      { text: "the clicking rice cooker  \u2192", ans: "hear", tail: "" }],
    how: "Ask which part of your body would notice it: ears, eyes, nose, tongue or skin." },
  { key: "2A-C", lvl: "ELL 2", id: "C", title: "Show it", kind: "lines", lines: 3,
    instr: "Rewrite each telling sentence so it shows a picture. Use an adjective and a sense.",
    example: { text: "The kitchen is nice.", ans: "The kitchen smells of garlic rice, and the window is warm with steam." },
    items: [{ text: "The food is good.", ans: "The soup is hot and salty, and the steam smells of ginger." },
      { text: "The room is loud.", ans: "The TV blares in the corner, and my brother shouts over it." },
      { text: "It was cold.", ans: "The wind bit my ears, and my fingers were stiff on the bus pole." },
      { text: "My place is comfortable.", ans: "My bed is soft, and the lamp beside it glows a warm yellow." }],
    how: "Take out the flat word. Put in what you see, hear, smell, taste or feel. Your sentence can be longer \u2014 that is the point." },
  { key: "2A-D", lvl: "ELL 2", id: "D", title: "Check your work", kind: "check",
    instr: "Read your work again. Tick each box when it is true.",
    checks: ["I marked every sentence T or S.", "I named a sense for each phrase.", "I replaced flat words with sense details.",
      "I used more than one sense.", "I did not use nice or good.", "Every sentence is complete."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "2A-E", lvl: "ELL 2", id: "E", title: "Exit ticket", kind: "exit", lines: 3,
    instr: "Answer, then show me before you leave.",
    items: [{ text: "Write one sentence about a place you know. Use two senses.", reveal: "The library is quiet, and the old books smell like dust." }],
    how: "One sentence, two senses. Take out every flat word." } ] },
 texts: {
  k1: { lvl: "ELL 1", title: "My Kitchen",
    body: "My name is Lina. I am fifteen years old. I am from Manila, but now I live in Richmond. On Sunday, I am in the kitchen with my grandmother. The rice smells good, and the radio is loud. I am happy in my kitchen." },
  k2: { lvl: "ELL 2", title: "The Sunday Kitchen",
    body: "If you want to know who I am, come to my kitchen on a Sunday morning. My name is Lina, and I am fifteen years old. I moved to Richmond from Manila two years ago, but the kitchen still smells like home. Garlic rice crackles in the pan, and the rice cooker clicks and steams in the corner. My grandmother\u2019s radio plays old songs while she hums along, a little off-key. I stand beside her with a wooden spoon, and I taste everything before anyone else because I am the official taster. The window is cloudy with steam, and outside the rain taps on the glass. My little brother asks a hundred questions, and I answer every one. I want to be a nurse one day, so I like taking care of people, and this kitchen is where I learned how. When the plates are empty and the radio is still playing, I know exactly who I am." } }
};
