// ELL12 U1 L08 — Planning My Place. ALL content here; the renderer holds the design.
// Rebuilt Sep 26 2026 from the v13 L09 "Planning" deck + Core sheets, to the standing orders, on the L05–L07 pattern.
// Approved spec Sep 26: warm-up Parts A/B at FIVE items per level; Part C plans aligned to the Unit 1 writing rubric
// (ELL12_U01_CompositionRubric_v1) so the plan feeds the L11 clean copy and unit-test Part B; Sean's rule: a NEW place, not the L3 room.
// Unit order: L7 One Clear Picture · L8 this · L9 Writing My Place
const vocab = [
  ["plan", "notes you make before you write"],
  ["place", "where something is"],
  ["detail", "a small, exact thing you notice"],
  ["topic", "what the writing is about"],
  ["organizer", "a chart that holds your ideas"],
  ["sense", "see, hear, smell, taste or touch"],
  ["matter", "to be important to you"],
  ["gather", "to collect or bring together"]];
const bankWords = ["gather", "detail", "organizer", "place", "matter", "plan", "sense", "topic"];
const helpLine = "Stuck? Fill in a help slip: “Can you check my …?”  “I need help with …”";

module.exports = {
 course: "ELL12",
 meta: { unit: 1, unitTitle: "Who I Am", lesson: 8, title: "Planning My Place", subtitle: "Choose a place and gather details", month: "September" },
 banner: { obj: "Choose a place that matters and plan what you will write.",
   std: "ELL 1: W7 describing words · W1 simple sentences · W11 place words  •  ELL 2: W3 beginning, middle, end · W1 · W2 joining ideas", lit: ["COM", "TH", "PS"] },
 plan: {
  objective: "Every student chooses a NEW place (not the Lesson 3 room) and fills a plan with exact details for the Lesson 9 draft. ELL 2 plans a beginning, middle and end.",
  outcomes: "ELL 1: W7 · W1 · W11. ELL 2: W3 · W1 · W2. Plans line up with the Unit 1 writing rubric.",
  materials: "Deck · ELL 1 and ELL 2 Lesson 8 worksheets, one each plus spares · exercise books · help slips in the box · class list for the plan check",
  timing: "80 minutes",
  steps: [
   ["8", "Warm-up Parts A and B", "In exercise books, five items per level. Part A · Vocabulary: ELL 1 names the sense (see, hear, smell, touch, taste); ELL 2 swaps a flat word for an exact one. Part B · Grammar: ELL 1 place words; ELL 2 and, but, so or because. Show all five, then reveal one at a time, alternating levels."],
   ["3", "Warm-up: write it", "ELL 1: one sentence about a place you like, with an adjective and a place word. ELL 2: two sentences about a place you like, one with because. Show the example answer and take two or three aloud."],
   ["6", "Guess my place", "Warm-up game. Give three sense clues and the class guesses the place: waves, salt, sand (the beach) · an engine, many seats, it moves (the bus) · bread, the oven beeps, flour (a bakery). Then partners play with their own places. English only."],
   ["2", "Title and goals", "Read the three goals. Name the big idea: a full plan makes the writing easy."],
   ["6", "Match the word", "Eight planning words against meanings from a shuffled bank, revealed one at a time, then the key-vocabulary summary."],
   ["4", "Tell me your place", "Partners tell each other about a place using the three plan parts; the listener asks what else they notice. English only. Remind: not the room from Lesson 3."],
   ["7", "Lina’s kitchen and Lina’s plan", "Read My Kitchen (ELL 1) and The Sunday Kitchen (ELL 2) in full, then side by side. Then show the plan Lina could have made: where, what she notices, why it matters."],
   ["5", "The three-part plan and how your writing is marked", "Teach where / what you notice / why it matters, and the new-place rule. Then show what the paragraph is marked on at each level, so students see the plan feeds the mark."],
   ["12", "Worksheet Parts A and B", "Hand out both sheets. Show the full pages, then walk Part A and Part B for each level with the worked example. Part A answers one at a time; ELL 2 Part B shows one good answer."],
   ["20", "Part C: fill your plan", "Walk Part C for each level and show one good answer. Students fill their own plan. Circulate: check the place is new, the details are exact, and ELL 2 has a beginning, middle and end."],
   ["7", "Check, exit ticket and plan check", "Part D tick-box check, then the Part E exit ticket with one example answer per level. Every student shows their plan before leaving. Next class, then agendas."] ],
  diff: "Support: ELL 1 may keep the Part A sense-word bank open while planning, and the Lina plan slide can go back up during Part C. Extension: ELL 2 early finishers write their first and last sentences in full under the plan.",
  assess: "MARKING TODAY (in class, no evening marking): check every Part C plan before students leave — a new place, exact details, why it matters; ELL 2 beginning, middle and end. Fix thin plans now, before drafting. Tick it on the class list.",
  homework: "None if the plan is checked. An unfinished plan goes home and comes back next class.",
  watch: "The Lesson 3 room chosen again (not allowed). Vague details: nice, good, beautiful. ELL 2: a middle with one detail, or no ending reason." },
 shape: [["Warm-up: words and grammar", "quick practice"], ["Guess my place", "warm-up game"], ["Match the word", "vocabulary game"],
   ["Tell me your place", "partner speaking"], ["Lina’s kitchen and Lina’s plan", "reading"], ["The three-part plan", "mini-lesson"],
   ["Worksheet Parts A and B", "worksheet"], ["Part C: fill your plan", "independent writing"], ["Check, exit ticket and plan check", "quick write"]],
 sequence: [
  { type: "drill", part: "A", kind: "Vocabulary", side: true, lvls: [
    { lvl: "ELL 1", bankLabel: "Which sense? One word in each blank", bank: "taste · smell · see · touch · hear",
      items: [["the bright window: I ____ it.", "see"], ["the loud radio: I ____ it.", "hear"], ["the soft blanket: I ____ it.", "touch"],
        ["garlic rice cooking: I ____ it.", "smell"], ["a sweet mango: I ____ it.", "taste"]] },
    { lvl: "ELL 2", bankLabel: "Choose the exact word", bank: "bitter · crowded · cozy · spotless · deafening",
      items: [["The room is nice. → The room is ____ and warm, with soft pillows.", "cozy"], ["The street is loud. → The street is ____; I cannot hear my friend.", "deafening"],
        ["The kitchen is clean. → The kitchen is ____; not one crumb is on the table.", "spotless"], ["The bus is full. → The bus is ____; there is no seat.", "crowded"],
        ["The coffee is bad. → The coffee is ____; it makes my face twist.", "bitter"]] } ] },
  { type: "drill", part: "B", kind: "Grammar", side: true, lvls: [
    { lvl: "ELL 1", bankLabel: "Place words — use a word more than once", bank: "in · next to · on · under",
      items: [["There is a lamp ____ the desk.", "on"], ["My shoes are ____ the bed.", "under"], ["There is rice ____ the pot.", "in"],
        ["The chair is ____ the table.", "next to"], ["There is a picture ____ the wall.", "on"]] },
    { lvl: "ELL 2", bankLabel: "Joining words — use a word more than once", bank: "and · so · because · but",
      items: [["I like my room ____ it is quiet.", "because"], ["The room is small, ____ it is bright.", "but"], ["It was noisy, ____ I closed the door.", "so"],
        ["I read there, ____ I sleep there.", "and"], ["The bus is crowded, ____ I stand by the door.", "so"]] } ] },
  { type: "rows", label: "Warm-up: write it", tag: "Warm-up · write it", head: "Write it", icon: "icon-book.png", big: "In your exercise book.", rows: [
    ["ELL 1", "One sentence about a place you like. Use an adjective and a place word."],
    ["ELL 2", "Two sentences about a place you like. Use because in one."]] },
  { type: "rows", label: "Warm-up: example answer", tag: "Warm-up · example answer", head: "One good answer", rows: [
    ["ELL 1", "My warm bed is next to the window."],
    ["ELL 2", "The library is quiet, so I read there. I like it because nobody rushes me."]] },
  { type: "rows", label: "Guess my place", tag: "Warm-up game", head: "Guess my place: how to play", englishOnly: true, rows: [
    ["1", "I give three clues: I hear… I smell… I see…"], ["2", "You guess the place: Is it the …?"],
    ["3", "Then play with a partner. Use YOUR places."]] },
  { type: "rows", label: "Guess my place: try these", tag: "Warm-up game", head: "Guess the place", rows: [
    ["1", "I hear waves. I smell salt. I see sand."], ["2", "I hear an engine. I see many seats. It moves."], ["3", "I smell bread. The oven beeps. I see flour."]] },
  { type: "rows", label: "Guess my place: answers", tag: "Warm-up game · answers", head: "The places", rows: [
    ["Waves, salt, sand", "the beach"], ["Engine, seats, it moves", "the bus"], ["Bread, the oven, flour", "a bakery"]] },
  { type: "speaking", label: "Guess my place: with a partner", head: "Now with a partner", englishOnly: true, signAll: true,
    prompt: "Give three clues. Your partner guesses your place.",
    frames: ["I hear ______.", "I smell ______.", "I see ______.", "Is it the ______?", "Yes, it is. / No, it isn’t."] },
  { type: "title", label: "Today’s lesson" },
  { type: "goals", label: "Today’s goals", items: [
    "Choose ONE place that matters to you — a new place, not your Lesson 3 room.",
    "Gather exact details: what you see, hear, smell and feel there.",
    "Fill a plan you can write from next class."] },
  { type: "match", label: "Match the word", head: "Match the word", bank: bankWords, words: vocab },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: vocab },
  { type: "speaking", label: "Tell me your place", head: "Tell me your place", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "Tell a partner about your place. Your partner asks: What else do you notice?",
    frames: ["My place is ______.", "There I see / hear / smell ______.", "It matters to me because ______.", "What else do you notice?"] },
  { type: "prose", text: "k1", label: "My Kitchen" },
  { type: "prose", text: "k2", label: "The Sunday Kitchen" },
  { type: "text2", a: "k1", b: "k2" },
  { type: "rows", label: "How Lina planned", tag: "Model", head: "Lina’s plan", rows: [
    ["Where", "the kitchen, on a Sunday morning"], ["See", "the cloudy window, the rice cooker in the corner"],
    ["Hear / smell", "the radio, garlic rice crackling in the pan"], ["Touch", "the wooden spoon, the warm steam"],
    ["Why it matters", "it is where she knows who she is"]] },
  { type: "rows", label: "The three-part plan", tag: "Teaching 1 of 2", head: "The three-part plan", rows: [
    ["Where", "name the place and when you are there"], ["What you notice", "exact details: see, hear, smell, touch, and where things are"],
    ["Why it matters", "one line: why this place is yours"], ["New place", "Not the room you wrote about in Lesson 3. Choose a new place."]] },
  { type: "rows", label: "How your writing is marked", tag: "Teaching 2 of 2", head: "How your writing is marked", rows: [
    ["ELL 1", "complete sentences · and, but, so · capitals and end marks · describing words"],
    ["ELL 2", "beginning, middle, end · complete sentences · joining ideas · capitals and punctuation"],
    ["Your plan", "gives you the details and the order. A full plan makes a strong paragraph."]] },
  { type: "rows", label: "Examples", tag: "Examples", head: "Two good plans", rows: [
    ["ELL 1", "My place is my uncle’s shop. I see old shelves next to the window. I smell coffee. It matters because my uncle teaches me there."],
    ["ELL 2", "Beginning: On Saturday mornings, my uncle’s shop is where I feel useful. Middle: shelves, the radio, cold coins, the till by the door. End: my uncle trusts me there."]] },
  { type: "handout", label: "Hand out the worksheet", note: "ELL 1 and ELL 2 sheets. Name and date first.",
    items: [["A", "sense words · topic or detail?"], ["B", "detail or not? · sharpen the detail"], ["C", "my plan"], ["D", "check your work"], ["E", "exit ticket", true]],
    foot: "The sheet stays in your duotang." },
  { type: "walk", part: "1A-A", withExample: true }, { type: "reveals", part: "1A-A" },
  { type: "walk", part: "2A-A", withExample: true }, { type: "reveals", part: "2A-A" },
  { type: "walk", part: "1A-B", withExample: true }, { type: "reveals", part: "1A-B" },
  { type: "walk", part: "2A-B", withExample: true }, { type: "reveals", part: "2A-B", good: true },
  { type: "walk", part: "1A-C", withExample: true }, { type: "reveals", part: "1A-C", good: true },
  { type: "walk", part: "2A-C", withExample: true }, { type: "reveals", part: "2A-C", good: true },
  { type: "walk", part: "1A-D" }, { type: "walk", part: "2A-D" },
  { type: "pages", label: "The whole sheet again" },
  { type: "exit", part: "1A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "1A-E", good: true },
  { type: "exit", part: "2A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "2A-E", good: true },
  { type: "rows", label: "Show me your plan", tag: "Before you go", head: "Show me your plan before you leave", icon: "icon-folder.png", rows: [
    ["1", "Put your plan on your desk."], ["2", "I check it: a new place, exact details, why it matters."],
    ["3", "Fix anything I mark. Then it goes in your duotang for next class."]] },
  { type: "nextshape", label: "Next class", head: "Next class: Writing My Place", items: [
    ["Warm-up: words and grammar", "quick practice"], ["Read your plan", "class activity"], ["The shape of the piece", "mini-lesson"],
    ["Say your first line", "partner speaking"], ["Write your place (draft)", "independent writing"], ["Exit ticket", "quick write"]] },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", icon: "icon-calendar.png", rows: [
    ["Next class", "Writing My Place. Your plan is your guide."], ["Homework", "If your plan is not finished, finish it at home and bring it back."],
    ["Remember", "Your worksheet goes in your duotang."]] } ],
 sheets: [
  { lvl: "ELL 1", suffix: "1A", label: "ELL 1", objective: "Plan the place you will write about.",
    outcomes: "ELL 1  W7 Use familiar words and phrases  •  W1 Write simple sentences  •  W11 Use articles and prepositions", vocab,
    remember: "A plan has three parts: where, what you notice, and why it matters. Choose a NEW place, not your Lesson 3 room.", helpLine },
  { lvl: "ELL 2", suffix: "2A", label: "ELL 2", objective: "Plan a descriptive paragraph with a beginning, middle and end.",
    outcomes: "ELL 2  W3 Write a composition with a beginning, middle and end  •  W1 Write simple sentences  •  W2 Connect ideas using and, but, so, or, because", vocab,
    remember: "Beginning: your place and a feeling. Middle: exact details. End: why it matters. Fill the plan fully before you draft.", helpLine } ],
 worksheet: { parts: [
  // ---------------- ELL 1 ----------------
  { key: "1A-A", lvl: "ELL 1", id: "A", title: "Sense words", kind: "cloze",
    instr: "Write the sense for each detail. You can use a word more than once.",
    bank: ["see", "hear", "smell", "feel"], bankCols: 4, crossed: [],
    example: { text: "the smell of bread →", ans: "smell", tail: "" },
    items: [{ text: "the humming fridge →", ans: "hear", tail: "" }, { text: "the cold floor →", ans: "feel", tail: "" },
      { text: "the bright window →", ans: "see", tail: "" }, { text: "the soft blanket →", ans: "feel", tail: "" },
      { text: "the loud street →", ans: "hear", tail: "" }],
    how: "Ask: do I notice it with my eyes, ears, nose or skin? Eyes = see, ears = hear, nose = smell, skin = feel." },
  { key: "1A-B", lvl: "ELL 1", id: "B", title: "Detail or not?", kind: "cloze", newPage: true,
    instr: "Write Y if it is a real detail you can see, hear or smell. Write N if it is too vague.",
    example: { text: "a nice room", ans: "N", tail: "" },
    items: [{ text: "the cold floor", ans: "Y", tail: "" }, { text: "a good place", ans: "N", tail: "" },
      { text: "the smell of coffee", ans: "Y", tail: "" }, { text: "my favourite spot", ans: "N", tail: "" },
      { text: "the humming fridge", ans: "Y", tail: "" }],
    how: "A real detail makes a picture in your head. Nice, good and favourite do not make a picture: N." },
  { key: "1A-C", lvl: "ELL 1", id: "C", title: "My place plan", kind: "lines", lines: 2,
    instr: "Choose ONE new place (not your Lesson 3 room). Finish each sentence with real details.",
    example: { text: "My place is …", ans: "My place is my uncle’s shop." },
    items: [{ text: "When I am there, it is … (morning / night / the weekend)", ans: "When I am there, it is Saturday morning." },
      { text: "I see … (a thing + an adjective)", ans: "I see old shelves and a red door." },
      { text: "Where is it? Use a place word: in, on, under, next to.", ans: "The shelves are next to the window." },
      { text: "I hear or smell …", ans: "I smell coffee, and I hear the radio." },
      { text: "Join two ideas with and, but or so.", ans: "The shop is small, but it is busy." },
      { text: "It matters to me because …", ans: "It matters to me because my uncle teaches me there." }],
    how: "One place for the whole plan. Write real things you can see, hear or smell there. These sentences become your writing next class." },
  { key: "1A-D", lvl: "ELL 1", id: "D", title: "Check your work", kind: "check",
    instr: "Read your plan again. Tick each box when it is true.",
    checks: ["I chose a new place (not my Lesson 3 room).", "I wrote what I see, hear or smell.", "I used an adjective and a place word.",
      "I joined two ideas with and, but or so.", "I wrote why it matters.", "My plan is full enough to write from."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "1A-E", lvl: "ELL 1", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then show me your plan before you leave.",
    items: [{ text: "Write one sentence: My place is …, and I notice …", reveal: "My place is my uncle’s shop, and I notice the smell of coffee." }],
    how: "One sentence: your place, the word and, then one thing you notice." },
  // ---------------- ELL 2 ----------------
  { key: "2A-A", lvl: "ELL 2", id: "A", title: "Topic idea or detail?", kind: "cloze",
    instr: "Write T for a topic idea (it names the place and a feeling) or D for a detail.",
    example: { text: "My kitchen is the warmest room in the house.", ans: "T", tail: "" },
    items: [{ text: "The kettle whistles at six.", ans: "D", tail: "" }, { text: "The floor is cold in the morning.", ans: "D", tail: "" },
      { text: "My grandfather’s balcony is where I feel calm.", ans: "T", tail: "" }, { text: "The city lights blink below.", ans: "D", tail: "" },
      { text: "I can smell the rain coming.", ans: "D", tail: "" }],
    how: "A topic idea names the whole place and how you feel there. A detail is one small thing inside it." },
  { key: "2A-B", lvl: "ELL 2", id: "B", title: "Sharpen the detail", kind: "lines", lines: 2,
    instr: "Each detail is vague. Rewrite it with a sense so a reader can picture it.",
    example: { text: "The room is nice.  →", ans: "The room smells of coffee and old books." },
    items: [{ text: "It is a comfortable place.  →", ans: "The old couch sinks under me like a soft hand." },
      { text: "The balcony is cool.  →", ans: "The night air moves cool across my arms." },
      { text: "My room is quiet.  →", ans: "In my room, I can hear my own breathing." },
      { text: "The street is busy.  →", ans: "Cars honk, and people rush past the bakery." }],
    how: "Replace the flat word with something you can see, hear, smell or feel. There is no single right answer." },
  { key: "2A-C", lvl: "ELL 2", id: "C", title: "My paragraph plan", kind: "lines", lines: 2, newPage: true,
    instr: "Choose ONE new place (not your Lesson 3 room). Plan the beginning, middle and end.",
    example: { text: "Beginning: your place and a feeling. Try an opening with a comma.", ans: "On Saturday mornings, my uncle’s shop is where I feel useful." },
    items: [{ text: "Middle — see:", ans: "Old shelves lean next to the window, full of rice bags." },
      { text: "Middle — hear or smell:", ans: "The radio plays, and the shop smells of coffee." },
      { text: "Middle — touch:", ans: "The cold coins feel heavy in my hand." },
      { text: "Middle — where things are (use a place word):", ans: "The till sits on a wooden counter by the door." },
      { text: "End — why it matters (use because):", ans: "This shop matters to me because my uncle trusts me there." },
      { text: "One sentence from your plan with but or so:", ans: "The shop is small, but it is always busy." }],
    how: "Beginning, then four exact details, then the reason. Write full sentences so the plan is ready to become your paragraph." },
  { key: "2A-D", lvl: "ELL 2", id: "D", title: "Check your work", kind: "check",
    instr: "Read your plan again. Tick each box when it is true.",
    checks: ["My beginning names the place and a feeling.", "I have four middle details.", "One detail says where things are.",
      "My ending says why it matters, with because.", "I chose a new place (not my Lesson 3 room).", "My details are exact, not vague."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "2A-E", lvl: "ELL 2", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then show me your plan before you leave.",
    items: [{ text: "Write your first sentence: an opening, a comma, your place and a feeling.", reveal: "On Saturday mornings, my uncle’s shop is where I feel useful." }],
    how: "Start with when or where, add a comma, then name your place and how you feel there." } ] },
 texts: {
  k1: { lvl: "ELL 1", title: "My Kitchen",
    body: "My name is Lina. I am fifteen years old. I am from Manila, but now I live in Richmond. On Sunday, I am in the kitchen with my grandmother. The rice smells good, and the radio is loud. I am happy in my kitchen." },
  k2: { lvl: "ELL 2", title: "The Sunday Kitchen",
    body: "If you want to know who I am, come to my kitchen on a Sunday morning. My name is Lina, and I am fifteen years old. I moved to Richmond from Manila two years ago, but the kitchen still smells like home. Garlic rice crackles in the pan, and the rice cooker clicks and steams in the corner. My grandmother’s radio plays old songs while she hums along, a little off-key. I stand beside her with a wooden spoon, and I taste everything before anyone else because I am the official taster. The window is cloudy with steam, and outside the rain taps on the glass. My little brother asks a hundred questions, and I answer every one. I want to be a nurse one day, so I like taking care of people, and this kitchen is where I learned how. When the plates are empty and the radio is still playing, I know exactly who I am." } }
};
