// ELL12 U1 L06 — Joining Ideas (and, but, so, because). ALL content here; the renderer holds the design.
// Rebuilt Sep 21 2026 from the v13 L07 deck + Core sheets, to the standing orders, on the L05 pattern.
// Unit order: L5 Words That Show · L6 this · L7 One Clear Picture
const bankWords = ["reason", "so", "comma", "and", "idea", "because", "join", "but"];
const vocab = [
  ["and", "joins two ideas that go together"],
  ["but", "joins two ideas that are different"],
  ["so", "shows a result: it was cold, so I closed the window"],
  ["because", "gives a reason: I am happy because it is Sunday"],
  ["join", "to put two things together"],
  ["idea", "one thought or one fact"],
  ["reason", "why something happens"],
  ["comma", "a small pause mark: ,"]];
const helpLine = "Stuck? Fill in a help slip: \u201CCan you check my \u2026?\u201D  \u201CI need help with \u2026\u201D";

module.exports = {
 course: "ELL12",
 meta: { unit: 1, unitTitle: "Who I Am", lesson: 6, title: "Joining Ideas", subtitle: "and, but, so and because", month: "September" },
 banner: { obj: "Join two ideas into one sentence with and, but, so and because.",
   std: "ELL 1: W2 compound sentences \u00B7 W1 simple sentences  \u2022  ELL 2: W2 connect ideas \u00B7 W1 simple sentences", lit: ["COM", "TH"] },
 plan: {
  objective: "Students join two sentences into one with and, but and so (ELL 1) and give reasons with because (ELL 2) \u2014 the connected-sentence rung of Term 1.",
  outcomes: "ELL 1: W2 compound sentences \u00B7 W1 simple sentences. ELL 2: W2 connect ideas \u00B7 W1 simple sentences.",
  materials: "Deck \u00B7 ELL 1 and ELL 2 Lesson 6 worksheets, one each plus spares \u00B7 exercise books \u00B7 help slips in the box \u00B7 the five sentence pairs for the game (below) \u00B7 a way to keep score for Two into one",
  timing: "80 minutes",
  steps: [
   ["10", "Warm-up Parts A and B", "In exercise books. Part A \u00B7 Vocabulary: ten home and kitchen verbs per level from a shuffled bank (ELL 1 cook, wash, eat\u2026; ELL 2 stir, chop, simmer\u2026). Part B \u00B7 Grammar: ELL 1 chooses and, but or so; ELL 2 chooses and, but, so or because. Show all ten, then reveal one at a time, alternating ELL 1 and ELL 2."],
   ["3", "Warm-up: write it", "ELL 1: two sentences about your morning, one joined with and, one with but. ELL 2: two sentences about your weekend, one with because, one with so. Show the one example answer and take two or three aloud."],
   ["7", "Two into one", "Read a pair; first pair of partners to say it as ONE sentence scores. Pairs: I am tired. / I go to bed early. (so) \u00B7 The rice is hot. / It is sweet. (and) \u00B7 The room is small. / It is warm. (but) \u00B7 I stay inside. / It is raining. (because) \u00B7 Grandmother cooks. / I help her. (and). Then partners: one starts a sentence ending in a joining word, the other finishes. English only."],
   ["2", "Title and goals", "Read the three goals. Name the big idea: two short ideas can become one sentence, if they belong together."],
   ["5", "Teaching 1: and, but, so, because", "One row per word with its job (together, different, a result, a reason) and a Lina example. Ask for one more example of each from the class before moving on."],
   ["6", "Teaching 2: two ideas, one sentence", "The radio example: two sentences, then one with but. The comma goes before but and so, not before because. Show the bad join (The radio is old, and I like math) \u2014 longer is not better if the ideas do not belong together. Then the ELL 1 and ELL 2 examples."],
   ["6", "Match the word", "Eight words against meanings from a shuffled bank, revealed one at a time, then the key-vocabulary summary."],
   ["4", "Say a joined sentence", "Partners say three joined sentences about their day with the frames; the listener names the joining word each time. English only."],
   ["7", "Lina\u2019s kitchen", "Read My Kitchen (ELL 1) and The Sunday Kitchen (ELL 2) in full, then side by side. Students find a joined sentence for each word (ELL 1: and, but; ELL 2: all four), then reveal."],
   ["10", "Worksheet Parts A and B", "Hand out both sheets. Show the full pages, then walk Part A and Part B for each level with the worked example, revealing one answer at a time."],
   ["14", "Part C independent writing", "Walk Part C for each level and show one good answer. ELL 1 writes four sentences about their day with the joining word given; ELL 2 writes five about a place that matters, with because twice. Circulate with help slips; push back any join with no joining word or a comma alone."],
   ["6", "Check and exit ticket", "Part D tick-box check, then the Part E exit ticket on the sheet, with one example answer per level. Next class, then agendas."] ],
  diff: "Support: the Teaching 1 slide (the four jobs) can go back up during Part C, and ELL 1 may use the frames from Say a joined sentence. Extension: ELL 2 early finishers write one sentence about their place that uses two joining words and still reads clearly.",
  assess: "Formative. Part C shows who can join two ideas with the right word (ELL 1) and give a real reason with because (ELL 2). The exit ticket is the quick check. Not marked.",
  homework: "Finish Part C if it is not done.",
  watch: "Run-ons: two sentences joined with no word, or with a comma alone (I was hungry, I ate rice). because must give a real reason, not just make the sentence longer. Commas before because. ELL 1 dropping the subject after but (I am tired, but go to school)." },
 shape: [["Warm-up: words and grammar", "quick practice"], ["Two into one", "warm-up game"], ["and, but, so, because", "mini-lesson"],
   ["Two ideas, one sentence", "mini-lesson"], ["Match the word", "vocabulary game"], ["Say a joined sentence", "partner speaking"],
   ["Lina\u2019s kitchen", "reading"], ["Worksheet Parts A and B", "worksheet"], ["Part C: your joined sentences", "independent writing"],
   ["Check and exit ticket", "quick write"]],
 sequence: [
  { type: "drill", part: "A", kind: "Vocabulary", lvls: [
    { lvl: "ELL 1", bankLabel: "Word bank \u2014 one word in each blank", bank: "eat \u00B7 wash \u00B7 sit \u00B7 open \u00B7 sleep \u00B7 cut \u00B7 drink \u00B7 help \u00B7 clean \u00B7 cook",
      items: [["We ____ rice for dinner.", "cook"], ["I ____ water when I am thirsty.", "drink"], ["I ____ at night in my bed.", "sleep"],
        ["I ____ the door with a key.", "open"], ["We ____ the dishes after dinner.", "wash"], ["I ____ my grandmother in the kitchen.", "help"],
        ["I ____ the bread with a knife.", "cut"], ["We ____ on chairs at the table.", "sit"], ["I ____ my room on Saturday.", "clean"],
        ["We ____ breakfast at seven.", "eat"]] },
    { lvl: "ELL 2", bankLabel: "Word bank \u2014 one word in each blank", bank: "season \u00B7 pour \u00B7 stir \u00B7 boil \u00B7 rinse \u00B7 serve \u00B7 chop \u00B7 taste \u00B7 peel \u00B7 simmer",
      items: [["Grandmother asks me to ____ the soup with a wooden spoon.", "stir"], ["We ____ the onions into small pieces.", "chop"],
        ["I ____ the rice in cold water before I cook it.", "rinse"], ["We ____ the potatoes so the skin comes off.", "peel"],
        ["Let the soup ____ slowly on low heat.", "simmer"], ["I ____ everything first because I am the taster.", "taste"],
        ["We ____ the water for tea.", "boil"], ["They ____ the chicken with salt and pepper.", "season"],
        ["I ____ hot tea into the cups.", "pour"], ["We ____ dinner to the family at seven.", "serve"]] } ] },
  { type: "drill", part: "B", kind: "Grammar", lvls: [
    { lvl: "ELL 1", bankLabel: "Use and, but or so", bank: "and \u00B7 but \u00B7 so",
      items: [["Lina is hungry, ____ she eats rice.", "so"], ["I like tea, ____ I do not like coffee.", "but"], ["My brother reads, ____ I write.", "and"],
        ["It is cold, ____ I close the window.", "so"], ["The kitchen is small, ____ it is warm.", "but"], ["I cook, ____ my grandmother helps me.", "and"],
        ["The rice is ready, ____ we eat.", "so"], ["I am tired, ____ I do my homework.", "but"], ["I wash the plates, ____ my brother dries them.", "and"],
        ["It is raining, ____ I take an umbrella.", "so"]] },
    { lvl: "ELL 2", bankLabel: "Use and, but, so or because", bank: "and \u00B7 but \u00B7 so \u00B7 because",
      items: [["Lina tastes everything first ____ she is the official taster.", "because"], ["The window is cloudy, ____ I can still see the rain.", "but"],
        ["The rice is ready, ____ we sit down to eat.", "so"], ["The radio plays, ____ my grandmother hums along.", "and"],
        ["I open the window ____ the kitchen is full of steam.", "because"], ["My brother asks a hundred questions, ____ I answer every one.", "and"],
        ["Lina moved to Richmond, ____ the kitchen still smells like home.", "but"], ["Lina likes taking care of people, ____ she wants to be a nurse.", "so"],
        ["We eat together on Sunday ____ it is our family day.", "because"], ["The soup is hot, ____ it is not ready yet.", "but"]] } ] },
  { type: "rows", label: "Warm-up: write it", tag: "Warm-up \u00B7 write it", head: "Write two sentences", icon: "icon-book.png", big: "In your exercise book.", rows: [
    ["ELL 1", "Two sentences about your morning. Join one with and and one with but."],
    ["ELL 2", "Two sentences about your weekend. Use because in one and so in the other."]] },
  { type: "rows", label: "Warm-up: example answer", tag: "Warm-up \u00B7 example answer", head: "One good answer", rows: [
    ["ELL 1", "I wake up at seven, and I eat breakfast. I am tired, but I go to school."],
    ["ELL 2", "I stay home on Saturday because my cousins visit. It rains on Sunday, so we cook together."]] },
  { type: "rows", label: "Two into one", tag: "Warm-up game", head: "Two into one: how to play", englishOnly: true, rows: [
    ["1", "I say two short sentences."], ["2", "Make ONE sentence: and, but, so or because."],
    ["3", "First pair to say it right gets a point."], ["4", "Then play with a partner."]] },
  { type: "speaking", label: "Two into one: make one sentence", head: "Make one sentence", englishOnly: true, signAll: true,
    prompt: "Two ideas. One sentence.",
    frames: ["______, and ______.", "______, but ______.", "______, so ______.", "______ because ______."] },
  { type: "speaking", label: "Two into one: with a partner", head: "Now with a partner", englishOnly: true, signAll: true,
    prompt: "Start a sentence. Your partner finishes it.",
    frames: ["I like my school, but \u2026", "I was hungry, so \u2026", "I am happy because \u2026", "I have a friend, and \u2026"] },
  { type: "title", label: "Today\u2019s lesson" },
  { type: "goals", label: "Today\u2019s goals", items: [
    "Join two ideas into one sentence.",
    "Use and, but and so. ELL 2: give a reason with because.",
    "Put a comma before but and so."] },
  { type: "rows", label: "and, but, so, because", tag: "Teaching 1 of 2", head: "Four joining words", rows: [
    ["and", "together: The radio plays, and Grandmother hums."], ["but", "different: The kitchen is small, but it is warm."],
    ["so", "a result: The rice is ready, so we eat."], ["because", "a reason: I stay because it feels like home."]] },
  { type: "rows", label: "Two ideas, one sentence", tag: "Teaching 2 of 2", head: "Two ideas, one sentence", rows: [
    ["Two ideas", "The radio is old. It still plays."], ["One sentence", "The radio is old, but it still plays."],
    ["Comma", "A comma goes before but and so. No comma before because."],
    ["Bad join", "The radio is old, and I like math."], ["The rule", "Join ideas that belong together."]] },
  { type: "rows", label: "Examples", tag: "Examples", head: "Joins at work", rows: [
    ["ELL 1", "I like rice, and I like soup."], ["ELL 1", "It is cold, so I close the window."],
    ["ELL 2", "The window is cloudy, but I can still see the rain."], ["ELL 2", "Lina is the taster because she is always in the kitchen first."]] },
  { type: "match", label: "Match the word", head: "Match the word", bank: bankWords, words: vocab },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: vocab },
  { type: "speaking", label: "Say a joined sentence", head: "Say a joined sentence", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "Three sentences about your day. Your partner names the joining word.",
    frames: ["I like ______, and ______.", "I am ______, but ______.", "I was ______, so ______.", "I ______ because ______.", "You used ______."] },
  { type: "prose", text: "k1", label: "My Kitchen" },
  { type: "prose", text: "k2", label: "The Sunday Kitchen" },
  { type: "text2", a: "k1", b: "k2" },
  { type: "rows", label: "Find the joins", tag: "Practice", head: "Find the joins in Lina\u2019s kitchen", rows: [
    ["and", "Find a sentence joined with and."], ["but", "Find a sentence joined with but."],
    ["so", "ELL 2: find a sentence joined with so."], ["because", "ELL 2: find a sentence with because."]] },
  { type: "rows", label: "Find the joins: My Kitchen", tag: "Practice \u00B7 answers", head: "In My Kitchen", rows: [
    ["and", "The rice smells good, and the radio is loud."], ["but", "I am from Manila, but now I live in Richmond."]] },
  { type: "rows", label: "Find the joins: The Sunday Kitchen", tag: "Practice \u00B7 answers", head: "In The Sunday Kitchen", rows: [
    ["and", "My name is Lina, and I am fifteen years old."],
    ["but", "I moved to Richmond from Manila two years ago, but the kitchen still smells like home."],
    ["so", "I want to be a nurse one day, so I like taking care of people."],
    ["because", "I taste everything before anyone else because I am the official taster."]] },
  { type: "handout", label: "Hand out the worksheet", note: "ELL 1 and ELL 2 sheets. Name and date first.",
    items: [["A", "the joining word"], ["B", "join into one"], ["C", "your joined sentences"], ["D", "check your work"], ["E", "exit ticket", true]],
    foot: "The sheet stays in your duotang." },
  { type: "walk", part: "1A-A", withExample: true }, { type: "reveals", part: "1A-A" },
  { type: "walk", part: "2A-A", withExample: true }, { type: "reveals", part: "2A-A" },
  { type: "walk", part: "1A-B", withExample: true }, { type: "reveals", part: "1A-B" },
  { type: "walk", part: "2A-B", withExample: true }, { type: "reveals", part: "2A-B" },
  { type: "walk", part: "1A-C", withExample: true }, { type: "reveals", part: "1A-C", good: true },
  { type: "walk", part: "2A-C", withExample: true }, { type: "reveals", part: "2A-C", good: true },
  { type: "walk", part: "1A-D" }, { type: "walk", part: "2A-D" },
  { type: "pages", label: "The whole sheet again" },
  { type: "exit", part: "1A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "1A-E", good: true },
  { type: "exit", part: "2A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "2A-E", good: true },
  { type: "nextshape", label: "Next class", head: "Next class: One Clear Picture", items: [
    ["Warm-up: words and grammar", "quick practice"], ["Show me the mark", "warm-up game"], ["Capitals and end marks", "mini-lesson"],
    ["Different openings", "mini-lesson"], ["Match the word", "vocabulary game"], ["Say it three ways", "partner speaking"],
    ["Lina\u2019s kitchen", "reading"], ["Worksheet Parts A and B", "worksheet"], ["Part C: fix it and new openings", "independent writing"],
    ["Check and exit ticket", "quick write"]] },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", icon: "icon-calendar.png", rows: [
    ["Next class", "One Clear Picture."], ["Homework", "Finish Part C if it is not done."], ["Remember", "Your worksheet goes in your duotang."]] } ],
 sheets: [
  { lvl: "ELL 1", suffix: "1A", label: "ELL 1", objective: "Join two ideas with and, but or so.",
    outcomes: "ELL 1  W2 Write compound sentences with and, but, or, so  \u2022  W1 Write simple sentences", vocab,
    remember: "and = together. but = different. so = a result. Put a comma before but and so.", helpLine },
  { lvl: "ELL 2", suffix: "2A", label: "ELL 2", objective: "Join ideas and give reasons with because.",
    outcomes: "ELL 2  W2 Connect ideas using and, but, so, or, because  \u2022  W1 Write simple sentences", vocab,
    remember: "and = together, but = different, so = a result, because = a reason. A comma goes before but and so, never before because.", helpLine } ],
 worksheet: { parts: [
  // ---------------- ELL 1 ----------------
  { key: "1A-A", lvl: "ELL 1", id: "A", title: "and, but or so?", kind: "cloze",
    instr: "( ? ) shows where the joining word goes. Write and, but or so on the line. You can use a word more than once.",
    bank: ["so", "and", "but"], bankCols: 3, crossed: [],
    example: { text: "The rice is hot ( ? ) sweet.", ans: "and", tail: "" },
    items: [{ text: "The room is small, ( ? ) it is warm.", ans: "but", tail: "" }, { text: "I was hungry, ( ? ) I ate rice.", ans: "so", tail: "" },
      { text: "I read, ( ? ) I write.", ans: "and", tail: "" }, { text: "It is late, ( ? ) I am not tired.", ans: "but", tail: "" },
      { text: "It was cold, ( ? ) I closed the window.", ans: "so", tail: "" }],
    how: "Read both ideas. Do they go together (and), are they different (but), or is the second one a result (so)? Write only the joining word." },
  { key: "1A-B", lvl: "ELL 1", id: "B", title: "Join with and", kind: "lines", lines: 2,
    instr: "Join the two sentences into one sentence with and. Write the whole sentence.",
    example: { text: "The room is warm. The room is bright.  \u2192", ans: "The room is warm and bright." },
    items: [{ text: "I like rice. I like soup.  \u2192", ans: "I like rice and soup." },
      { text: "She sings. She cooks.  \u2192", ans: "She sings and cooks." },
      { text: "The window is big. The window is cloudy.  \u2192", ans: "The window is big and cloudy." },
      { text: "My brother reads. I write.  \u2192", ans: "My brother reads, and I write." }],
    how: "Same person or thing in both sentences? Say it once: The room is warm and bright. Two different people? Keep both: My brother reads, and I write." },
  { key: "1A-C", lvl: "ELL 1", id: "C", title: "Join your own ideas", kind: "lines", lines: 2,
    instr: "Write five sentences about your day. Use the joining word given. Write the whole sentence.",
    example: { text: "Use and.", ans: "I woke up early, and I ate breakfast." },
    items: [{ text: "Use but.", reveal: "I was tired, but I went to school." }, { text: "Use so.", reveal: "It was cold, so I wore a jacket." },
      { text: "Use and.", reveal: "I ate lunch, and I talked to my friend." }, { text: "Use but.", reveal: "I like math, but it is hard." }, { text: "Use so.", reveal: "The bus was late, so I walked to school." }],
    how: "Two ideas about your day, one sentence. A comma goes before but and so. Every sentence starts with a capital and ends with a period." },
  { key: "1A-D", lvl: "ELL 1", id: "D", title: "Check your work", kind: "check",
    instr: "Read your work again. Tick each box when it is true.",
    checks: ["I wrote the joining word in Part A.", "I joined the sentences in Part B.", "I used and, but and so in Part C.",
      "My joins make sense.", "Each sentence starts with a capital letter.", "Each sentence ends with a period."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "1A-E", lvl: "ELL 1", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then show me before you leave.",
    items: [{ text: "Join two ideas about your day. Use and, but or so.", reveal: "I ate breakfast, and I took the bus to school." }],
    how: "One sentence, two ideas, one joining word." },
  // ---------------- ELL 2 ----------------
  { key: "2A-A", lvl: "ELL 2", id: "A", title: "Which joining word?", kind: "cloze",
    instr: "( ? ) shows where the joining word goes. Write and, but, so or because on the line.",
    bank: ["because", "so", "and", "but"], bankCols: 4, crossed: [],
    example: { text: "The rice is hot ( ? ) sweet.", ans: "and", tail: "" },
    items: [{ text: "The kitchen is small, ( ? ) it is warm.", ans: "but", tail: "" }, { text: "It was raining, ( ? ) Lina closed the window.", ans: "so", tail: "" },
      { text: "I stay in the kitchen ( ? ) it feels like home.", ans: "because", tail: "" }, { text: "The radio plays, ( ? ) Grandmother hums along.", ans: "and", tail: "" },
      { text: "Lina tastes first ( ? ) she is the official taster.", ans: "because", tail: "" }],
    how: "Ask what the second idea does: goes with the first (and), is different (but), is a result (so), or is a reason (because)." },
  { key: "2A-B", lvl: "ELL 2", id: "B", title: "Join into one", kind: "lines", lines: 2, newPage: true,
    instr: "Join each pair into one sentence with the best joining word. Put a comma before but and so.",
    example: { text: "The radio is old. It still plays.  \u2192", ans: "The radio is old, but it still plays." },
    items: [{ text: "I like the kitchen. It smells like home.  \u2192", ans: "I like the kitchen because it smells like home." },
      { text: "The rice was ready. We ate.  \u2192", ans: "The rice was ready, so we ate." },
      { text: "The window is cloudy. I can see the rain.  \u2192", ans: "The window is cloudy, but I can see the rain." },
      { text: "My brother asks questions. I answer them.  \u2192", ans: "My brother asks questions, and I answer them." }],
    how: "Read both sentences and choose the job: together, different, a result or a reason. Write ONE sentence. Comma before but and so; no comma before because." },
  { key: "2A-C", lvl: "ELL 2", id: "C", title: "Your joined sentences", kind: "lines", lines: 2,
    instr: "Write five joined sentences about a place that matters to you. Use the joining word given.",
    example: { text: "Use because.", ans: "I love my kitchen because my family talks there." },
    items: [{ text: "Use but.", reveal: "My room is small, but it is quiet." }, { text: "Use and.", reveal: "The lamp glows, and the heater hums." },
      { text: "Use because.", reveal: "I read there because nobody bothers me." }, { text: "Use so.", reveal: "It is my own space, so I feel calm there." },
      { text: "Use because.", reveal: "I go there often because it feels like mine." }],
    how: "One place, five sentences. Each because must give a real reason. Use a sense detail if you can: what you see, hear or smell there." },
  { key: "2A-D", lvl: "ELL 2", id: "D", title: "Check your work", kind: "check",
    instr: "Read your work again. Tick each box when it is true.",
    checks: ["I chose the best joining word in Part A.", "I joined each pair in Part B.", "I used because twice in Part C.",
      "I put a comma before but and so.", "My joins make sense.", "Every sentence is complete."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "2A-E", lvl: "ELL 2", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then show me before you leave.",
    items: [{ text: "Write one sentence about a place you know. Give a reason with because.", reveal: "I like the library because it is quiet and warm." }],
    how: "One sentence. The part after because must say why." } ] },
 texts: {
  k1: { lvl: "ELL 1", title: "My Kitchen",
    body: "My name is Lina. I am fifteen years old. I am from Manila, but now I live in Richmond. On Sunday, I am in the kitchen with my grandmother. The rice smells good, and the radio is loud. I am happy in my kitchen." },
  k2: { lvl: "ELL 2", title: "The Sunday Kitchen",
    body: "If you want to know who I am, come to my kitchen on a Sunday morning. My name is Lina, and I am fifteen years old. I moved to Richmond from Manila two years ago, but the kitchen still smells like home. Garlic rice crackles in the pan, and the rice cooker clicks and steams in the corner. My grandmother\u2019s radio plays old songs while she hums along, a little off-key. I stand beside her with a wooden spoon, and I taste everything before anyone else because I am the official taster. The window is cloudy with steam, and outside the rain taps on the glass. My little brother asks a hundred questions, and I answer every one. I want to be a nurse one day, so I like taking care of people, and this kitchen is where I learned how. When the plates are empty and the radio is still playing, I know exactly who I am." } }
};
