// ELL12 U1 L09 — Writing My Place. ALL content here; the renderer holds the design.
// Rebuilt Sep 26 2026 from the v13 L10 "Drafting" deck + Core sheets, to the standing orders, on the L05–L08 pattern.
// Approved spec Sep 26: side-by-side warm-up, five items per level (ELL 2 items kept to one line); models are the uncle's-shop
// pieces grown from L08's example plan; Part C aligned to the Unit 1 writing rubric; drafts are COLLECTED today (Week 2 draft read).
// Unit order: L8 Planning My Place · L9 this · L10 Making It Better
const vocab = [
  ["draft", "your first full try at the writing"],
  ["paragraph", "a group of sentences about one topic"],
  ["beginning", "the first sentence: it names your place"],
  ["middle", "the details: what you see, hear, smell, feel"],
  ["end", "the last sentence: why it matters"],
  ["connected", "sentences that go together"],
  ["keep going", "do not stop to fix: finish first"],
  ["one place", "do not change places halfway"]];
const bankWords = ["one place", "end", "draft", "connected", "middle", "keep going", "paragraph", "beginning"];
const helpLine = "Stuck? Fill in a help slip: “Can you check my …?”  “I need help with …”";
const M1 = "My place is my uncle’s shop. I see old shelves and a red door. The shelves are next to the window. I smell coffee, and I hear the radio. The shop is small, but it is busy. It matters to me because my uncle teaches me there.";
const M2 = "On Saturday mornings, my uncle’s shop is where I feel useful. Old shelves lean next to the window, full of rice bags and tins. The radio plays in the back, and the shop smells of coffee. When customers pay, the cold coins feel heavy in my hand. The till sits on a wooden counter by the door, so I can greet everyone who comes in. The shop is small, but it is always busy. This shop matters to me because my uncle trusts me there.";

module.exports = {
 course: "ELL12",
 meta: { unit: 1, unitTitle: "Who I Am", lesson: 9, title: "Writing My Place", subtitle: "From plan to draft", month: "September" },
 banner: { obj: "Turn your plan into a complete draft: beginning, middle, end.",
   std: "ELL 1: W1 · W2 joining · W5 capitals and end marks · W7 describing words  •  ELL 2: W3 beginning, middle, end · W1 · W2 · W7", lit: ["COM", "TH", "PS"] },
 plan: {
  objective: "Every student turns their Lesson 8 plan into a complete draft: ELL 1 six connected sentences, ELL 2 a descriptive paragraph. A finished rough draft, not a perfect one.",
  outcomes: "ELL 1: W1 · W2 · W5 · W7. ELL 2: W3 · W1 · W2 · W7 (the Unit 1 writing rubric).",
  materials: "Deck · ELL 1 and ELL 2 Lesson 9 worksheets · students’ Lesson 8 plans (from duotangs) · help slips · a tray for the drafts",
  timing: "80 minutes",
  steps: [
   ["8", "Warm-up Parts A and B", "In exercise books, five items per level, both levels on one slide. Part A · Vocabulary: ELL 1 opposites; ELL 2 exact sound verbs (whistles, hums, crackles, taps, clicks). Part B · Grammar: ELL 1 and, but or so; ELL 2 because or so. Reveal one at a time, alternating levels."],
   ["3", "Warm-up: write it", "ELL 1: one sentence that names your place. ELL 2: a strong first line with an opening and a comma. Show the example answer and take two or three aloud."],
   ["5", "Head, belly, feet", "Warm-up game. Read a sentence; students touch their head for a beginning, belly for a middle, feet for an end. Six practice sentences, then the answers, then partners play with sentences about their own place. English only."],
   ["2", "Title and goals", "Read the three goals. Name the big idea: a finished rough draft beats a perfect first sentence."],
   ["6", "Match the word", "Eight drafting words against meanings from a shuffled bank, revealed one at a time, then the key-vocabulary summary."],
   ["3", "Say your first line", "Partners say their opening sentence out loud before writing it. Does it name the place? English only."],
   ["7", "The model: My Uncle’s Shop", "Read the ELL 1 model and the ELL 2 model in full, then side by side. Then map the ELL 2 model: beginning, middle details, end."],
   ["6", "The shape and three drafting rules", "Beginning names the place, middle gives details, end says why it matters. Rules: stay in one place, keep going, use your plan."],
   ["10", "Worksheet Parts A and B", "Hand out both sheets. Walk Part A and Part B for each level with the worked example. ELL 1 answers one at a time; ELL 2 Part B shows one good answer."],
   ["25", "Part C: write your draft", "Walk Part C and show one good answer for each level. Students draft from their plan. Circulate with help slips; push anyone stuck on a word to keep going."],
   ["5", "Check, exit ticket and hand in", "Part D tick-box check, then the Part E exit ticket. Every worksheet goes in the tray: the draft is marked tonight. Next class, then agendas."] ],
  diff: "Support: ELL 1 may keep the Lesson 8 plan open and copy its sentences in order; the model slide can stay up during Part C. Extension: ELL 2 early finishers add a second sense detail to two middle sentences.",
  assess: "MARKING TODAY (draft read, schedule Week 2): collect every worksheet. Tonight write ONE strength and ONE fix on each Part C draft, no line editing, about 3 minutes each. Return before Lesson 10: students revise from your comment.",
  homework: "None if the draft is handed in. Unfinished drafts go home and come back at the start of Lesson 10.",
  watch: "Changing places halfway. Stopping to fix spelling instead of finishing. ELL 1 sentences with no join. ELL 2 paragraphs with no ending." },
 shape: [["Warm-up: words and grammar", "quick practice"], ["Head, belly, feet", "warm-up game"], ["Match the word", "vocabulary game"],
   ["Say your first line", "partner speaking"], ["The model: My Uncle’s Shop", "reading"], ["The shape and three rules", "mini-lesson"],
   ["Worksheet Parts A and B", "worksheet"], ["Part C: write your draft", "independent writing"], ["Check, exit ticket, hand in", "quick write"]],
 sequence: [
  { type: "drill", part: "A", kind: "Vocabulary", lvls: [
    { lvl: "ELL 1", bankLabel: "Opposites", bank: "dark · old · quiet · small · cold",
      items: [["The opposite of loud is ____.", "quiet"], ["The opposite of hot is ____.", "cold"], ["The opposite of big is ____.", "small"],
        ["The opposite of bright is ____.", "dark"], ["The opposite of new is ____.", "old"]] },
    { lvl: "ELL 2", bankLabel: "Exact sound words", bank: "hums · clicks · whistles · taps · crackles",
      items: [["The kettle ____ at six.", "whistles"], ["Rice ____ in the pan.", "crackles"], ["Rain ____ on the glass.", "taps"],
        ["The fridge ____ all night.", "hums"], ["The rice cooker ____.", "clicks"]] } ] },
  { type: "drill", part: "B", kind: "Grammar", lvls: [
    { lvl: "ELL 1", bankLabel: "and · but · so", bank: "and · so · but",
      items: [["It is small, ____ it is warm.", "but"], ["I was cold, ____ I sat inside.", "so"], ["I read ____ I rest there.", "and"],
        ["It is loud, ____ I like it.", "but"], ["It rained, ____ I stayed in.", "so"]] },
    { lvl: "ELL 2", bankLabel: "Reason or result?", bank: "so · because",
      items: [["I go there ____ it is calm.", "because"], ["It was calm, ____ I stayed.", "so"], ["I smile ____ I feel safe.", "because"],
        ["It was late, ____ I left.", "so"], ["I like it ____ it is warm.", "because"]] } ] },
  { type: "rows", label: "Warm-up: write it", tag: "Warm-up · write it", head: "Write it", icon: "icon-book.png", big: "In your exercise book.", rows: [
    ["ELL 1", "One sentence that names your place."],
    ["ELL 2", "A strong first line: an opening, a comma, your place and a feeling."]] },
  { type: "rows", label: "Warm-up: example answer", tag: "Warm-up · example answer", head: "One good answer", rows: [
    ["ELL 1", "My place is the park near my house."],
    ["ELL 2", "Every Sunday night, the park near my house is where I feel free."]] },
  { type: "rows", label: "Head, belly, feet", tag: "Warm-up game", head: "Head, belly, feet: how to play", englishOnly: true, rows: [
    ["Head", "a beginning: it names the place"], ["Belly", "a middle: one detail"], ["Feet", "an end: why it matters"],
    ["Then", "play with a partner. Use sentences about YOUR place."]] },
  { type: "rows", label: "Head, belly, feet: try these", tag: "Warm-up game", head: "Head, belly or feet?", rows: [
    ["1", "The kettle sings at six."], ["2", "My kitchen is the warmest room."], ["3", "It matters because my family gathers here."],
    ["4", "The floor is cold under my feet."], ["5", "Come to my balcony at night."], ["6", "I can smell the rain coming."]] },
  { type: "rows", label: "Head, belly, feet: answers", tag: "Warm-up game · answers", head: "The answers", rows: [
    ["1", "belly — a middle detail"], ["2", "head — a beginning"], ["3", "feet — an end"],
    ["4", "belly — a middle detail"], ["5", "head — a beginning"], ["6", "belly — a middle detail"]] },
  { type: "speaking", label: "Head, belly, feet: with a partner", head: "Now with a partner", englishOnly: true, signAll: true,
    prompt: "Say a sentence about your place. Your partner touches head, belly or feet.",
    frames: ["Head! It is a beginning.", "Belly! It is a middle.", "Feet! It is an end."] },
  { type: "title", label: "Today’s lesson" },
  { type: "goals", label: "Today’s goals", items: [
    "Turn your plan into writing.", "Keep every sentence about ONE place.", "Finish: a beginning, a middle and an end."] },
  { type: "match", label: "Match the word", head: "Match the word", bank: bankWords, words: vocab },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: vocab },
  { type: "speaking", label: "Say your first line", head: "Say your first line", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "Say your opening sentence to a partner. Your partner asks: Does it name the place?",
    frames: ["My place is ______.", "Come to my ______.", "On ______, my ______ is where I feel ______."] },
  { type: "prose", text: "m1", label: "My Uncle’s Shop (ELL 1 model)" },
  { type: "prose", text: "m2", label: "My Uncle’s Shop (ELL 2 model)" },
  { type: "text2", a: "m1", b: "m2" },
  { type: "rows", label: "The shape of the model", tag: "Model · the shape", head: "Beginning, middle, end", rows: [
    ["Beginning", "On Saturday mornings, my uncle’s shop is where I feel useful."],
    ["Middle", "old shelves · the radio and coffee · cold coins · the till by the door"],
    ["End", "This shop matters to me because my uncle trusts me there."]] },
  { type: "rows", label: "The shape of the piece", tag: "Teaching 1 of 2", head: "The shape of the piece", rows: [
    ["Beginning", "one sentence that names your place"], ["Middle", "four details: see, hear, smell, feel, and where things are"],
    ["End", "one sentence: why this place matters to you"]] },
  { type: "rows", label: "Three drafting rules", tag: "Teaching 2 of 2", head: "Three drafting rules", rows: [
    ["Stay in one place", "do not jump to another room or day"], ["Keep going", "do not stop to fix spelling: finish first"],
    ["Use your plan", "every detail is already there"], ["Remember", "A finished rough draft beats a perfect first sentence."]] },
  { type: "handout", label: "Hand out the worksheet", note: "ELL 1 and ELL 2 sheets. Name and date first. Take out your Lesson 8 plan.",
    items: [["A", "which part? · strong or weak opening?"], ["B", "put in order · add a sense detail"], ["C", "write your draft"], ["D", "check your work"], ["E", "exit ticket", true]],
    foot: "Today the whole sheet goes in the tray." },
  { type: "walk", part: "1A-A", withExample: true }, { type: "reveals", part: "1A-A" },
  { type: "walk", part: "2A-A", withExample: true }, { type: "reveals", part: "2A-A" },
  { type: "walk", part: "1A-B", withExample: true }, { type: "reveals", part: "1A-B" },
  { type: "walk", part: "2A-B", withExample: true }, { type: "reveals", part: "2A-B", good: true },
  { type: "walk", part: "1A-C", withExample: true }, { type: "reveals", part: "1A-C", good: true },
  { type: "walk", part: "2A-C", withExample: true },
  { type: "walk", part: "1A-D" }, { type: "walk", part: "2A-D" },
  { type: "pages", label: "The whole sheet again" },
  { type: "exit", part: "1A-E", note: "Then the whole sheet goes in the tray." }, { type: "reveals", part: "1A-E", good: true },
  { type: "exit", part: "2A-E", note: "Then the whole sheet goes in the tray." }, { type: "reveals", part: "2A-E", good: true },
  { type: "rows", label: "Hand in your draft", tag: "Before you go", head: "Hand in your draft", icon: "icon-folder.png", rows: [
    ["1", "Check your name is on your worksheet."], ["2", "Put the whole sheet in the tray."],
    ["3", "I read your draft and write one strength and one fix."], ["4", "You get it back next class to make it better."]] },
  { type: "nextshape", label: "Next class", head: "Next class: Making It Better", items: [
    ["Warm-up: words and grammar", "quick practice"], ["Warm-up game", "game"], ["Revise, not edit", "mini-lesson"],
    ["Three ways to revise", "mini-lesson"], ["Read and add", "partner speaking"], ["Revise your draft", "independent writing"], ["Exit ticket", "quick write"]] },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", icon: "icon-calendar.png", rows: [
    ["Next class", "Making It Better: you revise your draft."], ["Homework", "None if your draft is in the tray."],
    ["Remember", "Keep your Lesson 8 plan in your duotang."]] } ],
 sheets: [
  { lvl: "ELL 1", suffix: "1A", label: "ELL 1", objective: "Write your place in connected sentences: beginning, middle, end.",
    outcomes: "ELL 1  W1 Write simple sentences  •  W2 Compound sentences with and, but, so  •  W5 Capitals and end marks  •  W7 Familiar words and phrases", vocab,
    remember: "Beginning names the place. Middle gives details. End says why it matters. Use your plan and keep going.", helpLine },
  { lvl: "ELL 2", suffix: "2A", label: "ELL 2", objective: "Draft a descriptive paragraph with a beginning, middle and end.",
    outcomes: "ELL 2  W3 A composition with a beginning, middle and end  •  W1 Simple sentences  •  W2 Connect ideas  •  W7 Capitalization and punctuation", vocab,
    remember: "Beginning: your place and a feeling. Middle: four details. End: why it matters, with because. Stay in one place and keep going.", helpLine } ],
 worksheet: { parts: [
  // ---------------- ELL 1 ----------------
  { key: "1A-A", lvl: "ELL 1", id: "A", title: "Which part?", kind: "cloze",
    instr: "Write B (beginning), M (middle) or E (end) for each sentence.",
    example: { text: "My place is my bedroom.", ans: "B", tail: "" },
    items: [{ text: "I see my books on the shelf.", ans: "M", tail: "" }, { text: "It matters because it is mine.", ans: "E", tail: "" },
      { text: "I hear the street outside.", ans: "M", tail: "" }, { text: "My place is the park.", ans: "B", tail: "" },
      { text: "The floor is warm in the sun.", ans: "M", tail: "" }],
    how: "Beginning names the place. Middle is one detail. End says why it matters." },
  { key: "1A-B", lvl: "ELL 1", id: "B", title: "Put them in order", kind: "cloze",
    instr: "Number the sentences 1 to 4 to make a good order. The first one is done for you.",
    example: { text: "My place is the park.", ans: "1", tail: "" },
    items: [{ text: "It matters because it is quiet.", ans: "4", tail: "" }, { text: "I see the tall trees.", ans: "2 or 3", tail: "" },
      { text: "I hear the birds.", ans: "2 or 3", tail: "" }],
    how: "The beginning comes first and the end comes last. The details go in the middle, in any order." },
  { key: "1A-C", lvl: "ELL 1", id: "C", title: "Write your place", kind: "lines", lines: 2,
    instr: "Use your Lesson 8 plan. Write one sentence for each line. Capital at the start, end mark at the end.",
    example: { text: "Beginning — name your place. (Lina)", ans: "My place is my grandmother’s kitchen." },
    items: [{ text: "Beginning — name YOUR place.", ans: "My place is my uncle’s shop." },
      { text: "What you see — use an adjective.", ans: "I see old shelves and a red door." },
      { text: "Where it is — use a place word: in, on, under, next to.", ans: "The shelves are next to the window." },
      { text: "What you hear or smell.", ans: "I smell coffee, and I hear the radio." },
      { text: "Join two ideas with and, but or so.", ans: "The shop is small, but it is busy." },
      { text: "End — why it matters: It matters to me because …", ans: "It matters to me because my uncle teaches me there." }],
    how: "Copy from your plan, one sentence on each line. Keep every sentence about the same place. Keep going to the end." },
  { key: "1A-D", lvl: "ELL 1", id: "D", title: "Check your work", kind: "check",
    instr: "Read your writing again. Tick each box when it is true.",
    checks: ["My first sentence names my place.", "I used an adjective.", "I used a place word.",
      "I joined two ideas with and, but or so.", "Every sentence has a capital and an end mark.", "My last sentence says why it matters."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "1A-E", lvl: "ELL 1", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then put the whole sheet in the tray.",
    items: [{ text: "I wrote … sentences. My best detail is …", reveal: "I wrote six sentences. My best detail is the red door." }],
    how: "Count your sentences. Choose the detail you like most." },
  // ---------------- ELL 2 ----------------
  { key: "2A-A", lvl: "ELL 2", id: "A", title: "Strong or weak opening?", kind: "cloze",
    instr: "Write S for a strong opening (it names the place and draws us in) or W for weak.",
    example: { text: "This is about my kitchen.", ans: "W", tail: "" },
    items: [{ text: "If you want to know who I am, come to my kitchen at night.", ans: "S", tail: "" },
      { text: "My place is a place I like.", ans: "W", tail: "" },
      { text: "Come to my grandfather’s balcony when the rain is near.", ans: "S", tail: "" },
      { text: "I will describe my room now.", ans: "W", tail: "" },
      { text: "My room is the one place the noise cannot reach.", ans: "S", tail: "" }],
    how: "A strong opening names a real place and makes the reader want more. “This is about” and “I will describe” are weak." },
  { key: "2A-B", lvl: "ELL 2", id: "B", title: "Add a sense detail", kind: "lines", lines: 2,
    instr: "Each sentence names the place but gives no picture. Add one sense detail with and, but or so.",
    example: { text: "My kitchen is warm.  →", ans: "My kitchen is warm, and it smells of garlic rice." },
    items: [{ text: "The balcony is cool.  →", ans: "The balcony is cool, and the city hums far below." },
      { text: "The park is peaceful.  →", ans: "The park is peaceful, and the leaves move without a sound." },
      { text: "My corner is small.  →", ans: "My corner is small, but the light there is always soft." },
      { text: "The bus is crowded.  →", ans: "The bus is crowded, so I stand by the door and smell the rain." }],
    how: "Keep the sentence, add a comma and a joining word, then something you can see, hear, smell or feel. There is no single right answer." },
  { key: "2A-C", lvl: "ELL 2", id: "C", title: "Write your paragraph", kind: "open", lines: 16, newPage: true,
    instr: "Use your Lesson 8 plan. Beginning: your place and a feeling. Middle: four details. End: why it matters, with because. Use one opening with a comma, and one but or so. Stay in one place. Keep going to the end.",
    example: { text: "Beginning: place + feeling", ans: "On Saturday mornings, my uncle’s shop is where I feel useful." },
    items: [{ text: "Your paragraph", reveal: M2 }],
    how: "Start from your plan’s beginning. Write every detail as a full sentence. Do not stop to fix spelling: finish first." },
  { key: "2A-D", lvl: "ELL 2", id: "D", title: "Check your work", kind: "check",
    instr: "Read your paragraph again. Tick each box when it is true.",
    checks: ["My opening names the place and a feeling.", "My middle has four or more details.", "I used because, and but or so.",
      "One sentence starts with an opening and a comma.", "The whole paragraph stays in one place.", "My ending says why it matters."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "2A-E", lvl: "ELL 2", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then put the whole sheet in the tray.",
    items: [{ text: "I wrote … sentences. My best detail is …", reveal: "I wrote seven sentences. My best detail is the cold coins in my hand." }],
    how: "Count your sentences. Choose the detail you are most proud of." } ] },
 texts: {
  m1: { lvl: "ELL 1", title: "My Uncle’s Shop", body: M1 },
  m2: { lvl: "ELL 2", title: "My Uncle’s Shop", body: M2 } }
};
