// ELL 3 Unit 1 — worksheet content. One worksheet per lesson.
// Reading lessons (6, 7, 11) carry terminology and evidence technique; the story
// comprehension questions themselves live in the story documents.

const WS = [
  { n: 1, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["routine", "warm-up", "specific", "general", "detail", "draft", "sensory", "notice"],
      items: [
        { text: "The way something is done the same way every time is a ____.", answer: "routine" },
        { text: "A first piece of writing that gets you started, and is not for marks, is a ____.", answer: "warm-up" },
        { text: "A description that is exact and about one particular thing is ____.", answer: "specific" },
        { text: "A description that is broad and could be true of many things is ____.", answer: "general" },
        { text: "One small piece of information about something is a ____.", answer: "detail" },
        { text: "An early version of a piece of writing is a ____.", answer: "draft" },
      ] },
    { kind: "label", title: "Part B \u2014 Could you photograph it?", weight: 6,
      instr: "Write YES if a camera could capture the sentence, or NO if it could not.",
      items: [
        { text: "The apartment was small.", answer: "NO" },
        { text: "My bed touched two walls at once.", answer: "YES" },
        { text: "My neighbourhood was very friendly.", answer: "NO" },
        { text: "The man in 4B kept our spare key on a nail by his door.", answer: "YES" },
        { text: "The winters there were hard.", answer: "NO" },
        { text: "We slept in coats for three weeks in January.", answer: "YES" },
      ] },
    { kind: "lines", title: "Part C \u2014 Four details", weight: 4, lines: 8,
      instr: "Before you write your paragraph, list four things you can picture in your chosen place: one you can see, one you can hear, one you can smell or taste, and one person or object always there.",
      answer: "Look for concrete nouns rather than adjectives. \u201cLoud\u201d is not a sound; \u201ctwo radios on different stations\u201d is. Students listing only visual details need prompting on the other senses." },
    { kind: "comp", title: "Part D \u2014 Check your understanding", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "Why is today's paragraph a warm-up and not marked?", lines: 3, answer: "It is the first piece and its job is to get the student writing honestly rather than carefully. Lesson 2 uses it as raw material for the general-to-specific test." },
        { q: "What will you do with this paragraph in Lesson 2?", lines: 3, answer: "Find its most general sentence and rewrite it so a reader could photograph it \u2014 that rewrite is Voices Notebook entry one." },
      ] },
  ]},

  { n: 2, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["vague", "precise", "category", "concrete", "abstract", "narrow", "justify", "entry"],
      items: [
        { text: "Something that is not clear or exact is ____.", answer: "vague" },
        { text: "Something exact, leaving no doubt, is ____.", answer: "precise" },
        { text: "A group of things of the same kind is a ____.", answer: "category" },
        { text: "Something you can see, hear, or touch is ____.", answer: "concrete" },
        { text: "An idea you cannot point at is ____.", answer: "abstract" },
        { text: "To make something smaller and more exact is to ____ it.", answer: "narrow" },
      ] },
    { kind: "revise", title: "Part B \u2014 Make it photographable", weight: 6,
      instr: "Rewrite each general sentence so a reader could take a picture of it. Keep the same meaning.",
      items: [
        { text: "The market was busy.", answer: "Any version naming what was there: \u201cThree men were shouting the same price at once.\u201d Reject \u201cThe market was very busy.\u201d" },
        { text: "My first day at this school was difficult.", answer: "Look for one moment, not a summary: \u201cI ate lunch in the second-floor stairwell.\u201d" },
        { text: "The weather in my hometown is nice.", answer: "Reject any answer that only swaps nice for lovely. Needs a fact: temperature, season, what people wear." },
        { text: "She is a good friend.", answer: "Needs an action: \u201cShe learned to say my grandmother's name properly.\u201d" },
        { text: "The room was messy.", answer: "Needs objects and positions: \u201cThere were two plates under the bed.\u201d" },
      ] },
    { kind: "label", title: "Part C \u2014 General or specific?", weight: 5,
      instr: "Write GENERAL or SPECIFIC beside each sentence.",
      items: [
        { text: "Food is very important in my family.", answer: "GENERAL" },
        { text: "My mother salts the water before it boils, always.", answer: "SPECIFIC" },
        { text: "We had many traditions.", answer: "GENERAL" },
        { text: "On the last day of the year my father repaints the front door.", answer: "SPECIFIC" },
        { text: "Moving countries is a big change for anyone.", answer: "GENERAL" },
      ] },
    { kind: "comp", title: "Part D \u2014 Voices Notebook, entry one", weight: 4,
      instr: "Answer in complete sentences. This is checkpoint one.",
      items: [
        { q: "Write one thing you noticed on the way to school this morning that a person walking beside you would have missed.", lines: 3, answer: "Any concrete observation. Reject weather generalities. The test is whether another student in the room could have written the same sentence." },
        { q: "What makes your detail specific rather than general?", lines: 3, answer: "Look for the student applying the photograph test or the how-many-others test, not just asserting that it is specific." },
      ] },
  ]},

  { n: 3, parts: [
    { kind: "comp", title: "Part A \u2014 Your header", weight: 0,
      instr: "Complete every line before you write. This is the header the district requires, top right of your lined page.",
      items: [
        { q: "Full name", lines: 1, answer: "Student\u2019s full name." },
        { q: "Student number", lines: 1, answer: "MyEd student number." },
        { q: "Grade", lines: 1, answer: "Grade." },
        { q: "ELL level", lines: 1, answer: "3." },
        { q: "Date", lines: 1, answer: "September 14 or 15, 2026." },
      ] },
    { kind: "lines", title: "Part B \u2014 Your writing", weight: 0, lines: 22,
      instr: "Black or blue pen. Write on every line here \u2014 the spacing is already double. Continue on the back or on a second sheet if you need more room." },
  ] },
  { n: 4, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["verb", "noun", "adjective", "adverb", "connotation", "texture", "aroma", "hum"],
      items: [
        { text: "A word for an action or a state is a ____.", answer: "verb" },
        { text: "A word that describes a noun is an ____.", answer: "adjective" },
        { text: "A word that describes a verb is an ____.", answer: "adverb" },
        { text: "The feeling a word carries beyond its meaning is its ____.", answer: "connotation" },
        { text: "How a surface feels is its ____.", answer: "texture" },
        { text: "A low continuous sound is a ____.", answer: "hum" },
      ] },
    { kind: "edit", title: "Part B \u2014 One strong word", weight: 6,
      instr: "Rewrite each sentence, replacing the weak phrase with one stronger word.",
      items: [
        { text: "She said loudly that we were late.", answer: "shouted / announced / called. Reject \u201csaid very loudly\u201d." },
        { text: "The old broken-down car made a strange noise.", answer: "The wreck rattled / groaned / knocked. Look for one strong noun and one strong verb." },
        { text: "He walked slowly and sadly out of the room.", answer: "trudged / shuffled / drifted." },
        { text: "The dog went quickly across the yard.", answer: "darted / bolted / tore." },
        { text: "The street was very busy and there were a lot of people.", answer: "The street was packed / crowded / heaving. One word replaces the whole second clause." },
      ] },
    { kind: "lines", title: "Part C \u2014 Without your eyes", weight: 5, lines: 8,
      instr: "Write four sentences about a meal you remember. At least two different senses must appear, and you may not use the words good, nice, or very.",
      answer: "Check the sense count first, then the banned words. The commonest failure is four visual sentences with one smell word attached to the last." },
    { kind: "comp", title: "Part D \u2014 Check your understanding", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "Why does a strong verb usually beat a verb plus an adverb?", lines: 3, answer: "It does the same job in one word, and the stronger verb carries more information than the adverb did \u2014 darted says more than walked quickly." },
        { q: "Which sense do most writers overuse, and why does using another one work better?", lines: 3, answer: "Sight. Readers expect visual description and skim it; sound, smell and touch are less expected so they land harder. Smell in particular is tied to memory." },
      ] },
  ]},

  { n: 5, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["clause", "subject", "simple", "compound", "conjunction", "fragment", "run-on", "rhythm"],
      items: [
        { text: "A group of words with its own subject and verb is a ____.", answer: "clause" },
        { text: "Who or what the sentence is about is the ____.", answer: "subject" },
        { text: "A sentence with one clause is ____.", answer: "simple" },
        { text: "A sentence joining two clauses as equals is ____.", answer: "compound" },
        { text: "A joining word such as and, but, or so is a ____.", answer: "conjunction" },
        { text: "Two sentences joined with no punctuation or joining word make a ____.", answer: "run-on" },
      ] },
    { kind: "combine", title: "Part B \u2014 Join them", weight: 6,
      instr: "Join each pair into one compound sentence. Choose the joining word that fits the meaning, and punctuate it correctly.",
      items: [
        { text: "The shop closed at six. We arrived at ten past.", answer: "\u2026 at six, but we arrived at ten past. Comma required before but." },
        { text: "I could take the train. I could walk along the dyke.", answer: "\u2026 the train, or I could walk \u2026" },
        { text: "She spoke three languages at home. She was silent for a month at school.", answer: "\u2026 at home, but she was silent \u2026 Accept yet." },
        { text: "It rained every day that week. The garden still died.", answer: "\u2026 that week, but the garden still died. Reject so \u2014 the meaning is contrast." },
        { text: "My brother packed the car. I said goodbye to the neighbours.", answer: "\u2026 the car, and I said goodbye \u2026" },
      ] },
    { kind: "label", title: "Part C \u2014 Name the problem", weight: 5,
      instr: "Write SIMPLE, COMPOUND, FRAGMENT, or RUN-ON beside each.",
      items: [
        { text: "My father repaired watches.", answer: "SIMPLE" },
        { text: "My father repaired watches he never wore one.", answer: "RUN-ON" },
        { text: "Because the bus was late.", answer: "FRAGMENT" },
        { text: "The kettle boiled, and nobody moved.", answer: "COMPOUND" },
        { text: "Running down the hill in the rain.", answer: "FRAGMENT" },
      ] },
    { kind: "comp", title: "Part D \u2014 Check your understanding", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "When does a comma go before and, but, or so?", lines: 3, answer: "When both sides could stand alone as sentences. If the second half has no subject and verb of its own, no comma." },
        { q: "Why is a short sentence often the strongest one in a paragraph?", lines: 3, answer: "It stops the reader. After several long sentences a short one lands with weight, which is why it usually belongs at the end." },
      ] },
  ]},

  { n: 6, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["protagonist", "trait", "motive", "setting", "atmosphere", "routine", "reluctant", "belong"],
      items: [
        { text: "The main character of a story is the ____.", answer: "protagonist" },
        { text: "A quality of a person's character is a ____.", answer: "trait" },
        { text: "The reason a character does something is their ____.", answer: "motive" },
        { text: "Where and when a story happens is its ____.", answer: "setting" },
        { text: "The feeling a place gives is its ____.", answer: "atmosphere" },
        { text: "Something done regularly in the same way is a ____.", answer: "routine" },
      ] },
    { kind: "label", title: "Part B \u2014 Shown or told?", weight: 6,
      instr: "Write SHOWN if the writer gives evidence, or TOLD if the writer simply announces it.",
      items: [
        { text: "Arman was very lonely at his new school.", answer: "TOLD" },
        { text: "Arman counts the stops under his breath. Nobody hears him.", answer: "SHOWN" },
        { text: "Faraj was a kind man.", answer: "TOLD" },
        { text: "Faraj put a cake down and waved his hand at the coins.", answer: "SHOWN" },
        { text: "Everyone in the house was busy and unhappy.", answer: "TOLD" },
        { text: "His father is asleep at four in the afternoon.", answer: "SHOWN" },
      ] },
    { kind: "lines", title: "Part C \u2014 Setting as pressure", weight: 5, lines: 9,
      instr: "For each of the three places in the story \u2014 the bus, the bakery, the house \u2014 write what it allows Arman to do and what it stops him doing.",
      answer: "Bus: allows counting in Farsi and being unseen; stops him arriving. Bakery: allows an hour that is his, warmth, being expected nowhere. House: allows nothing that is only his \u2014 every room is occupied by someone else's difficulty." },
    { kind: "comp", title: "Part D \u2014 Evidence practice", weight: 4,
      instr: "Answer with a line number for each.",
      items: [
        { q: "Name one thing Arman does every day. What does the repetition suggest?", lines: 3, answer: "Rides past his stop, counts in Farsi, sits at the bakery table. Repetition turns a choice into a need." },
        { q: "What does Arman want? The story never states it \u2014 build the answer from evidence.", lines: 4, answer: "Accept any defensible reading with textual support: an hour that belongs to him, a place where he is not behind, somewhere warm where nothing is required of him. Reject \u201che wants to run away\u201d unless substantiated." },
      ] },
  ]},

  { n: 7, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["theme", "topic", "summary", "interpret", "universal", "connection", "identity", "displacement"],
      items: [
        { text: "An idea about life that a story explores is its ____.", answer: "theme" },
        { text: "What a story is about on the surface is its ____.", answer: "topic" },
        { text: "A short account of what happened is a ____.", answer: "summary" },
        { text: "To work out what something means is to ____ it.", answer: "interpret" },
        { text: "Something true across many people and places is ____.", answer: "universal" },
        { text: "A link between the text and something outside it is a ____.", answer: "connection" },
      ] },
    { kind: "label", title: "Part B \u2014 Topic or theme?", weight: 6,
      instr: "Write TOPIC or THEME beside each.",
      items: [
        { text: "Belonging.", answer: "TOPIC" },
        { text: "Belonging somewhere new can feel like a betrayal of home.", answer: "THEME" },
        { text: "Family.", answer: "TOPIC" },
        { text: "A family can be close and still leave a person with nowhere to be alone.", answer: "THEME" },
        { text: "Kindness.", answer: "TOPIC" },
        { text: "Kindness that announces itself is worth less than kindness that does not.", answer: "THEME" },
      ] },
    { kind: "revise", title: "Part C \u2014 Turn the topic into a theme", weight: 5,
      instr: "Each of these is a topic. Rewrite it as a theme: a full sentence making a claim someone could disagree with.",
      items: [
        { text: "Home.", answer: "Must make a claim. \u201cHome is important\u201d still fails \u2014 nobody disagrees with it." },
        { text: "Language.", answer: "e.g. \u201cLosing the speed of your own language costs more than losing its words.\u201d" },
        { text: "Silence.", answer: "e.g. \u201cSome questions are a kindness precisely because they are not asked.\u201d" },
        { text: "Routine.", answer: "e.g. \u201cA routine can be a way of surviving something you cannot yet name.\u201d" },
        { text: "Parents.", answer: "e.g. \u201cA parent can know something without being told and choose not to say so.\u201d" },
      ] },
    { kind: "comp", title: "Part D \u2014 Check your understanding", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "Why can you disagree with a theme but not with a topic?", lines: 3, answer: "A topic names a subject and makes no claim, so there is nothing to disagree with. A theme asserts something about life, which can be tested against the text." },
        { q: "What makes a text-to-self connection worth writing down?", lines: 3, answer: "It must change how the story reads. \u201cI also take a bus\u201d changes nothing; \u201cI also arrived late on purpose, so I know the delay was the point\u201d changes the ending." },
      ] },
  ]},

  { n: 8, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["complex", "main clause", "dependent", "subordinate", "cause", "contrast", "although", "emphasis"],
      items: [
        { text: "A sentence with a main clause and a dependent clause is ____.", answer: "complex" },
        { text: "The part that can stand alone as a sentence is the ____.", answer: "main clause" },
        { text: "A clause that cannot stand alone is ____.", answer: "dependent" },
        { text: "The reason something happens is the ____.", answer: "cause" },
        { text: "A difference set against something else is a ____.", answer: "contrast" },
        { text: "A joining word showing contrast is ____.", answer: "although" },
      ] },
    { kind: "combine", title: "Part B \u2014 Build the complex sentence", weight: 6,
      instr: "Join each pair using the joining word given. A comma follows the dependent clause only when it comes first.",
      items: [
        { text: "(because) He missed his stop. He was not ready to go home.", answer: "Because he was not ready to go home, he missed his stop \u2014 or reversed without comma. Watch that the cause is the right way round." },
        { text: "(although) She understood every word. She did not answer.", answer: "Although she understood every word, she did not answer." },
        { text: "(while) My mother filled out the forms. I translated the questions.", answer: "While my mother filled out the forms, I translated the questions." },
        { text: "(since) We moved in July. I have not seen my cousins.", answer: "Since we moved in July, I have not seen my cousins." },
        { text: "(when) The shop bell rang. Everyone looked up.", answer: "When the shop bell rang, everyone looked up." },
      ] },
    { kind: "label", title: "Part C \u2014 What does the joining word do?", weight: 5,
      instr: "Write CAUSE, TIME, or CONTRAST beside each sentence.",
      items: [
        { text: "Although the bakery stayed open late, he never bought anything.", answer: "CONTRAST" },
        { text: "Because the bakery stayed open late, he had somewhere to be.", answer: "CAUSE" },
        { text: "While he waited, the rain stopped.", answer: "TIME" },
        { text: "Since he arrived, he has not spoken in class.", answer: "TIME" },
        { text: "She spoke three languages, whereas her teacher spoke one.", answer: "CONTRAST" },
      ] },
    { kind: "comp", title: "Part D \u2014 Check your understanding", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "\u201cWhile he waited\u201d and \u201cbecause he waited\u201d describe the same event. Explain the difference in meaning.", lines: 4, answer: "While makes the waiting the background for something else. Because makes the waiting the reason for it. Same event, different argument about it." },
        { q: "Did the complex sentences make your paragraph clearer, or only longer? Be honest.", lines: 3, answer: "Either answer is acceptable if defended. Students who say longer and can point to a sentence that got worse have learned the more useful lesson." },
      ] },
  ]},

  { n: 9, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["pre-write", "brainstorm", "organizer", "select", "discard", "anecdote", "ritual", "inherit"],
      items: [
        { text: "The stage before drafting, where you gather material, is the ____ stage.", answer: "pre-write" },
        { text: "To list ideas quickly without judging them is to ____.", answer: "brainstorm" },
        { text: "A chart used to sort ideas before writing is an ____.", answer: "organizer" },
        { text: "To choose deliberately from a larger set is to ____.", answer: "select" },
        { text: "To throw out something you have decided not to use is to ____ it.", answer: "discard" },
        { text: "Something done the same way each time, with meaning, is a ____.", answer: "ritual" },
      ] },
    { kind: "lines", title: "Part B \u2014 The organizer", weight: 8, lines: 16,
      instr: "Fifteen items minimum before you stop. Words and phrases only. Five objects; five things you can hear, smell or taste; three habits or rituals; two phrases that do not translate well.",
      answer: "Count the items before reading them. Students who stop at eight have not gathered enough to select from, and the paragraph will show it. Push for volume here, not quality." },
    { kind: "label", title: "Part C \u2014 Would it survive the test?", weight: 5,
      instr: "Write KEEP or CUT. A detail survives only if a reader could photograph it and few others in the room could have written it.",
      items: [
        { text: "My grandmother's cooking.", answer: "CUT" },
        { text: "The chipped blue bowl she measured rice with.", answer: "KEEP" },
        { text: "Our traditional celebrations.", answer: "CUT" },
        { text: "The word my mother uses for the space behind the fridge.", answer: "KEEP" },
        { text: "Family is important to us.", answer: "CUT" },
      ] },
    { kind: "comp", title: "Part D \u2014 Check your understanding", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "Why gather fifteen details when the paragraph only needs five?", lines: 3, answer: "Quality comes from discarding. You cannot select well from a short list, and the first five things anyone thinks of are usually the most general." },
        { q: "Why is one object a better starting point than an abstract idea like \u201cmy culture\u201d?", lines: 3, answer: "Abstract prompts produce abstract writing. An object can be described, and the meaning arrives through the description without needing to be stated." },
      ] },
  ]},

  { n: 10, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["topic sentence", "opening", "coherence", "transition", "revise", "edit", "publish", "momentum"],
      items: [
        { text: "The sentence that sets up what a paragraph is doing is the ____.", answer: "topic sentence" },
        { text: "The first sentence, which decides whether a reader continues, is the ____.", answer: "opening" },
        { text: "The quality of holding together as one piece is ____.", answer: "coherence" },
        { text: "A word or phrase that moves the reader between ideas is a ____.", answer: "transition" },
        { text: "To change the content and shape of a draft is to ____.", answer: "revise" },
        { text: "To correct spelling, punctuation and grammar is to ____.", answer: "edit" },
      ] },
    { kind: "revise", title: "Part B \u2014 Three openings", weight: 6,
      instr: "Write three possible opening sentences for your paragraph, each using a different detail from your plan.",
      items: [
        { text: "Opening one: start with an object.", answer: "Must name a specific thing. Reject any opening that announces a category (\u201cFood is important in my family\u201d)." },
        { text: "Opening two: start with a sound or a smell.", answer: "Check it is genuinely non-visual." },
        { text: "Opening three: start in the middle of an action.", answer: "Look for a verb in progress \u2014 someone doing something, not a scene being described." },
      ] },
    { kind: "label", title: "Part C \u2014 Would you keep reading?", weight: 5,
      instr: "Write STRONG or WEAK beside each opening sentence.",
      items: [
        { text: "In my family, traditions are very important to us.", answer: "WEAK" },
        { text: "There is a pot in our kitchen that my mother will not replace.", answer: "STRONG" },
        { text: "I am going to describe something I brought from my country.", answer: "WEAK" },
        { text: "The suitcase still smells of the airport in Manila.", answer: "STRONG" },
        { text: "Culture means many different things to different people.", answer: "WEAK" },
      ] },
    { kind: "comp", title: "Part D \u2014 Check your understanding", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "Why should you not open a descriptive paragraph by announcing the topic?", lines: 3, answer: "The announcement is general and gives the reader no picture. Opening on a detail lets the reader work out the topic themselves, which holds them." },
        { q: "What does it mean to say one detail should be your centre?", lines: 3, answer: "One detail is developed further than the others rather than the paragraph listing five things equally. The centre is what the paragraph is actually about." },
      ] },
  ]},

  { n: 11, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["infer", "imply", "explicit", "implicit", "substantiate", "omission", "narrator", "withhold"],
      items: [
        { text: "To work out what is meant without being told is to ____.", answer: "infer" },
        { text: "To suggest something without stating it is to ____.", answer: "imply" },
        { text: "Something stated directly in the text is ____.", answer: "explicit" },
        { text: "Something present but not stated directly is ____.", answer: "implicit" },
        { text: "To support a claim with evidence is to ____ it.", answer: "substantiate" },
        { text: "Something deliberately left out is an ____.", answer: "omission" },
      ] },
    { kind: "label", title: "Part B \u2014 Explicit or implicit?", weight: 6,
      instr: "Write EXPLICIT if the story states it directly, or IMPLICIT if you have to work it out.",
      items: [
        { text: "Her father leaves at half past six.", answer: "EXPLICIT" },
        { text: "Her father is sheltering people on their way to the plant.", answer: "IMPLICIT" },
        { text: "One shoulder is always wetter than the other.", answer: "EXPLICIT" },
        { text: "He is holding the umbrella out sideways over someone else.", answer: "IMPLICIT" },
        { text: "The umbrella stand by the door is always full.", answer: "EXPLICIT" },
        { text: "Priya admires her father.", answer: "IMPLICIT" },
      ] },
    { kind: "lines", title: "Part C \u2014 The arithmetic", weight: 5, lines: 7,
      instr: "The story gives you three numbers in the first paragraph. Write them down, then work out what they prove.",
      answer: "Leaves 6:30, shift starts 7:30, drive is 20 minutes. Forty minutes are unaccounted for every day, and Priya tells us she has checked \u2014 so the gap is deliberate on the writer's part and already noticed by the narrator." },
    { kind: "comp", title: "Part D \u2014 Reading the silence", weight: 4,
      instr: "Answer in complete sentences.",
      items: [
        { q: "Is her father lying when he says people leave umbrellas on the bus? Defend your answer.", lines: 4, answer: "Probably not \u2014 it is very likely true and it answers the question she asked. What he avoids is the question she meant. Reward students who hold the distinction between a false statement and a deflection." },
        { q: "It is August, there is no rain, and he still leaves at half past six. What does this change?", lines: 4, answer: "It removes the umbrellas from the explanation entirely. Whatever he is doing was never about rain, so the story was never about umbrellas \u2014 which is what the last line says." },
      ] },
  ]},

  { n: 12, parts: [
    { kind: "cloze", title: "Part A \u2014 Vocabulary", weight: 6,
      instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra.",
      bank: ["criteria", "checklist", "redundant", "filler", "consistent", "portfolio", "reflect", "submit"],
      items: [
        { text: "The fixed points a piece is judged against are the ____.", answer: "criteria" },
        { text: "A list used to check work in a fixed order is a ____.", answer: "checklist" },
        { text: "Repeating something already said is ____.", answer: "redundant" },
        { text: "Words that take up space without adding meaning are ____.", answer: "filler" },
        { text: "The same all the way through is ____.", answer: "consistent" },
        { text: "To look back and think about what changed is to ____.", answer: "reflect" },
      ] },
    { kind: "revise", title: "Part B \u2014 Cut it", weight: 6,
      instr: "Each of these appeared in a real draft. Rewrite it, or write DELETE if the sentence should simply go.",
      items: [
        { text: "The pot is very old. It has been in our family a long time.", answer: "Keep one, not both. Redundant." },
        { text: "There is a thing that my mother does which is that she salts the water first.", answer: "My mother salts the water first. Filler removed." },
        { text: "This shows that my culture means a lot to me.", answer: "DELETE. It explains the paragraph back to the reader." },
        { text: "Traditions are important in many families.", answer: "DELETE. General, and could appear in anyone's paragraph." },
        { text: "It was a very nice and good meal that we all enjoyed a lot.", answer: "Needs a total rewrite with a concrete detail. Three weak words in one sentence." },
      ] },
    { kind: "lines", title: "Part C \u2014 The revision pass", weight: 5, lines: 9,
      instr: "Work through your own draft in order and record what you found. Is your opening photographable? Which detail is your centre? Which sentence could appear unchanged in a classmate's paragraph? How many weak words did you circle?",
      answer: "The honest answers matter more than the flattering ones. A student who reports four weak words and one general sentence has done the pass properly; \u201cnothing to change\u201d means it was not done." },
    { kind: "comp", title: "Part D \u2014 Closing the Voices Notebook", weight: 4,
      instr: "This is checkpoint four and it is the part the Notebook is marked on. Read back through all your entries before answering.",
      items: [
        { q: "What kind of detail do you notice most easily? Quote at least two of your own entries as evidence.", lines: 4, answer: "Look for a genuine pattern claim supported by their own entries \u2014 visual detail, sound, things people say, objects. The evidence requirement is the point; unsupported self-description scores nothing." },
        { q: "What kind of detail do you keep missing? Use your entries to show it.", lines: 4, answer: "The hardest question on the sheet and the most valuable. Accept any defensible gap: non-visual senses, other people's behaviour, their own reactions. Reject \u201cnone\u201d." },
      ] },
  ]},
];

module.exports = { WS };
