// ELL 3 U1 — the two authored reading texts.
// Levelled for Expanding (3) readers: mostly high-frequency vocabulary, short paragraphs,
// concrete action. Difficulty is carried by inference, not by sentence complexity.
// Story 1 is taught closely (L6-L7). Story 2 is read with less support (L11).

const STORY_ONE = {
  title: "The Long Way Home",
  slug: "TheLongWayHome",
  author: "written for ELL 3",
  lesson: "Lessons 6 and 7",
  blurb: "Arman has worked out that the 407 takes forty minutes to come back around.",
  // paragraphs; numbering is applied by the generator every fifth line
  paras: [
    "The 407 bus takes forty minutes to go all the way around and come back to the same stop. Arman worked this out in his second week here, and he has not told anybody.",
    "His stop is the one by the pharmacy with the green cross. He knows it is his stop. He can see the corner of his building from the window, the balcony where his mother hangs the washing even in October, when nothing dries.",
    "He stays in his seat.",
    "The bus goes on past the pharmacy, past the school, past the place where they are building something that has been a hole in the ground since he arrived. Arman counts the stops under his breath. Yek. Do. Se. Nobody hears him. The woman across from him has headphones in and her eyes shut, and the driver is watching the road.",
    "He counts in Farsi because that is how numbers arrive. In class he has to push them into English one at a time, and by the time he has the right word the question has moved on. On the bus there is no question. There is only the counting, and the window, and the same shops going by in the same order.",
    "At the eleventh stop the bus reaches the bakery on Ackroyd, and this is where Arman gets off.",
    "The bakery is run by a man called Faraj who is not from Arman's country and does not speak his language. They speak English to each other, badly, and it does not matter. Faraj sells bread and small cakes with pistachio in them and he has one table by the window with two chairs.",
    "Arman sits at the table. He buys nothing. In the first week he bought a cake, and Faraj took his money, and then on the second day Faraj put a cake down in front of him and waved his hand at the coins, and after that Arman stopped bringing any.",
    "He does his homework there. It takes about an hour. Sometimes Faraj turns the radio up when a song comes on that he likes, and sings a line, and stops.",
    "At half past five Arman packs his bag and walks the twenty minutes home, and by then the light has gone and his mother is in the kitchen and the washing is still on the balcony, still wet.",
    "\u201cWhere were you?\u201d she asks.",
    "\u201cSchool,\u201d he says.",
    "She nods. She does not ask again, and he thinks about this sometimes, on the bus, going past the pharmacy with the green cross.",
    "In the house there is his mother, and there is his father who is asleep at four in the afternoon because he works nights at the airport now, and there is the second bedroom where his sister does her university applications with the door shut. In the house everybody is doing something difficult and quiet.",
    "Arman is eleven stops away, in a warm room that smells of pistachio, counting in the only language where the numbers come first.",
    "On the Thursday before the long weekend, the bakery is closed. There is a paper sign in the window in Faraj's handwriting, and Arman stands and reads it three times, although he understood it the first time.",
    "He does not go home early.",
    "He walks the twenty minutes anyway, and then he keeps walking, down to the river where the boats are, and he sits on the wall until his hands are cold. He has nothing to do there. There is no table and no radio and no bread.",
    "When he finally gets home his mother is standing at the window.",
    "\u201cWhere were you?\u201d she says, and this time she is looking at him.",
    "\u201cThe bakery,\u201d says Arman. \u201cOn Ackroyd. I go there after school.\u201d",
    "His mother is quiet for a moment. Then she says: \u201cIs it warm there?\u201d",
    "\u201cYes.\u201d",
    "\u201cGood,\u201d she says, and she turns back to the window. \u201cThe washing will not dry. I keep putting it out.\u201d",
    "Arman stands beside her and they look at the balcony together, at the shirts hanging heavy in the dark, and neither of them says anything else about it.",
  ],
  vocab: [
    ["pharmacy", "a shop that sells medicine"],
    ["balcony", "a platform outside an upper window"],
    ["stop", "a place where a bus picks up passengers"],
    ["pistachio", "a green nut, common in Middle Eastern baking"],
    ["packs", "puts things into a bag"],
    ["applications", "forms you fill in to ask for a place or a job"],
    ["sign", "a notice with writing on it"],
    ["wall", "here, a low wall by the river that people sit on"],
    ["heavy", "here, wet enough to hang down"],
    ["quiet", "here, saying nothing"],
  ],
  teacherNotes: {
    heading: "Teacher notes \u2014 The Long Way Home",
    intro: "Do not hand this page to students. The story is short and the surface is easy; everything it is doing sits underneath. Students who read it quickly and say \u201cnothing happens\u201d have read it correctly and have not finished reading it.",
    points: [
      ["What is never stated", "The story never says Arman is homesick, lonely, or unhappy. It never explains why he does not go home. Every reading of his motive has to be built from what he does, and students must be held to that \u2014 the phrase to insist on is \u201cwhere in the text\u201d."],
      ["The counting", "Arman counts in Farsi because the numbers arrive that way. This is the story's clearest statement about what school costs him, and it is made without mentioning school. Strong readers will connect it to the classroom sentence two paragraphs later; most will need pointing."],
      ["Faraj and the cake", "Faraj takes his money once, then stops taking it, and nothing is said about it by either of them. This is the model for the whole story: care that is delivered without being named. Ask what would be lost if Faraj had said \u201cyou don't have to pay\u201d."],
      ["The house paragraph", "Everyone in the house is doing something difficult and quiet, behind a door or asleep. Arman is not escaping his family; he is escaping a house where there is no room to be a person for an hour. Students often read the mother as neglectful \u2014 push back on this from the text."],
      ["The mother's two questions", "She asks \u201cwhere were you\u201d twice. The first time she does not look at him and does not ask again. The second time she is at the window and she is looking. The difference is the plot of the story."],
      ["\u201cIs it warm there?\u201d", "This is the line to spend time on. She does not ask why, does not tell him off, does not ask about school. She asks the one question that matters to her, and it is a question about whether her son is being looked after. The washing that will not dry sits next to it deliberately."],
      ["The closed bakery", "The Thursday is the test. Without the bakery, Arman still does not go home \u2014 which proves the bakery is not the point. He needs an hour that belongs to him. Ask students what the river gives him that the bakery gave him, and what it does not."],
    ],
    themes: [
      "A person can need an hour that belongs to nobody else without that being a rejection of the people who love them.",
      "Care is often given without being announced, and announcing it can spoil it.",
      "Arriving somewhere new can cost you the speed of your own mind, and the loss is invisible to everybody but you.",
    ],
    caution: "Some students in an ELL 3 room will recognise the shift-work parent, the sibling behind a closed door, or the hour spent somewhere warm on the way home. Let recognition stay unspoken unless a student offers it. Do not invite personal disclosure in the L6 or L7 discussion; the Voices Notebook gives them a private route if they want one.",
  },
  questions: {
    literal: [
      "How long does the 407 take to come all the way around?",
      "What is at Arman's own bus stop?",
      "At which stop does Arman get off the bus?",
      "What does Faraj sell?",
      "What time does Arman pack his bag?",
      "Why is the bakery closed on the Thursday?",
    ],
    inference: [
      "Why does Arman count in Farsi rather than in English? Use the text.",
      "Faraj stops taking Arman's money and neither of them mentions it. What does this tell you about Faraj?",
      "Arman's mother asks \u201cwhere were you\u201d twice. What has changed between the two times?",
      "The bakery is closed and Arman still does not go home. What does this tell you about what he is really looking for?",
      "Why does the story end with the washing instead of with Arman?",
    ],
  },
};

const STORY_TWO = {
  title: "The Second Umbrella",
  slug: "TheSecondUmbrella",
  author: "written for ELL 3",
  lesson: "Lesson 11",
  blurb: "Priya's father leaves the house at half past six. He does not need to leave until seven.",
  paras: [
    "My father leaves the house at half past six in the morning. His shift at the plant starts at half past seven, and the drive takes twenty minutes, and I have checked this on my phone more than once.",
    "In the winter he takes two umbrellas from the stand by the door. He comes home with one.",
    "The first time I noticed, I thought he had lost it. My father does lose things. He lost his good gloves in the first month we were here, and he lost the key to the shed, and when my mother asked about the shed key he said the shed was full of the last people's rubbish anyway.",
    "But he lost the umbrella again the next week. And the week after that.",
    "We have a lot of umbrellas. That is the strange part. There is a metal stand by the door and it is always full, and my mother has never bought a single one of them.",
    "My father comes home at four o'clock and his shoulders are wet. Not his head \u2014 his head is dry, his hair is flat and dry \u2014 but the tops of his shoulders are dark with rain, and one side is always worse than the other.",
    "He hangs his coat over the radiator and it steams.",
    "At dinner he asks me about school and I say it was fine, and he asks my brother about school and my brother says it was fine, and my mother puts more rice on his plate than he asked for, which is her way of saying something she does not say.",
    "In our old city my father was not a man who left the house early. He was late for things. It was a family joke, the kind of joke you only understand is affectionate afterwards.",
    "Once, in February, I got the early bus because of an exam, and I saw him.",
    "He was standing at the bus shelter on the corner of Number Three Road, which is not on his way, and he was standing outside the shelter in the rain and not inside it, because the shelter was full. There were seven or eight people in it. They all had the grey bags from the plant.",
    "My father was holding an umbrella over a woman I have never seen. She was very small and very old and she was holding a grey bag too. My father was talking to her and she was laughing at something, and the rain was coming down on his left shoulder because his arm was out.",
    "My bus went past. He did not see me.",
    "I did not tell my mother, and I did not tell my brother, and I have thought about why for a long time.",
    "The next Saturday my father was fixing the handle on the shed door, the shed we do not have a key for, and I brought him a cup of tea and stood there.",
    "\u201cThere are a lot of umbrellas by the door,\u201d I said.",
    "He did not look up. He said: \u201cPeople leave them on the bus.\u201d",
    "\u201cWho does?\u201d",
    "\u201cPeople,\u201d he said. \u201cThey leave them and the driver puts them in a box and nobody comes for them.\u201d Then he said, in the voice he uses when a subject is finished, \u201cIt is a waste. An umbrella is a good thing.\u201d",
    "I said that it was, and I drank my own tea, and I did not ask him anything else.",
    "He is still leaving at half past six. It is August now and there is no rain, so the stand by the door is not emptying the way it does in the winter, and he comes home dry.",
    "But he still leaves at half past six.",
    "I know now that this is the part I did not understand at the beginning. I thought I was working out where the umbrellas went. That was never the question. The umbrellas were only the thing I could see.",
  ],
  vocab: [
    ["shift", "the hours a person works"],
    ["plant", "a factory"],
    ["stand", "a holder for umbrellas, by a door"],
    ["shed", "a small building in a garden for storing things"],
    ["radiator", "a metal heater on a wall"],
    ["steams", "gives off water as it dries in the heat"],
    ["shelter", "a small covered structure that protects from rain"],
    ["affectionate", "showing fondness or love"],
    ["handle", "the part of a door you hold"],
    ["waste", "using something badly, or not using it at all"],
  ],
  teacherNotes: {
    heading: "Teacher notes \u2014 The Second Umbrella",
    intro: "This is the low-support inference text and the one the L11 assessment rests on. Resist explaining it in the introduction. Students should meet it cold, and the discussion should be the first time anything is named.",
    points: [
      ["The arithmetic", "The story opens by handing students the numbers: leaves at 6:30, starts at 7:30, drive is twenty minutes. Forty minutes are unaccounted for and Priya tells you she has checked. Students who miss the gap have not read closely; students who find it have found the story's engine on page one."],
      ["What is explicit and what is not", "Explicit: two umbrellas out, one home, wet shoulders, one side worse, a full stand nobody bought. Implicit: everything about why. Use this text to make the explicit/implicit distinction concrete rather than defining it abstractly."],
      ["The one asymmetrical detail", "One shoulder is always wetter. This is the physical proof of an arm held out sideways, and it is planted three paragraphs before the scene that explains it. Ask students to find the earliest sentence that could only be true if the ending were true."],
      ["The father's answer", "\u201cPeople leave them on the bus\u201d is not a lie \u2014 it is very probably where the umbrellas come from. It answers the question she asked and avoids the question she meant. Students will want to call him dishonest; hold them to the distinction."],
      ["Why she does not tell anyone", "Priya says she has thought about why for a long time and never gives the answer. This is the largest gap in the story and the best essay question in it. Legitimate readings include protecting his privacy, protecting the joke-version of him her mother still has, and not wanting to make it a thing that gets discussed at dinner."],
      ["August", "The final movement removes the umbrellas entirely. No rain, no wet shoulders, and he still leaves at half past six \u2014 which retroactively rewrites what the whole story was about. This is the paragraph that answers the L11 writing task."],
      ["The last line", "\u201cThe umbrellas were only the thing I could see.\u201d Students should be able to say what she can see now that she could not before, in their own words, without the story ever having said it."],
    ],
    themes: [
      "What a person does when nobody is watching is the truest available account of who they are.",
      "Understanding someone can mean choosing not to make them explain themselves.",
      "A visible puzzle is often the smallest part of what is actually happening.",
    ],
    caution: "The shift-work parent and the family that has come down in the world will be close to home for some students. The story is deliberately warm and the father is admirable, which makes it safe to teach; keep the discussion on Priya's reading of her father rather than on students' own households.",
  },
  questions: {
    literal: [
      "What time does Priya's father leave the house, and what time does his shift start?",
      "How long is the drive to the plant?",
      "How many umbrellas does he take in winter, and how many come home?",
      "Which part of him is wet when he comes home, and which part is dry?",
      "Where does Priya see her father in February?",
      "What reason does her father give for the umbrellas by the door?",
    ],
    inference: [
      "What is Priya's father doing between half past six and half past seven? Substantiate your answer from at least two places in the text.",
      "Why is one shoulder always wetter than the other? Point to the sentence that explains it.",
      "Is her father lying when he says people leave umbrellas on the bus? Defend your answer.",
      "Why does Priya not tell her mother or her brother? The story never says \u2014 build a reading and support it.",
      "It is August, there is no rain, and he still leaves at half past six. What does this change about the whole story?",
      "Explain the last line in your own words. What could Priya not see at the beginning?",
    ],
  },
};

const STORIES = [STORY_ONE, STORY_TWO];

module.exports = { STORIES, STORY_ONE, STORY_TWO };
