// u1_content.js — ENG8 Unit 1 content. Pure data; consumed by make_docs.js.

const UNIT = {
  code: "ENG8",
  number: 1,
  month: "September",
  title: "Stories & Identity: Getting to Know Each Other",
  bigIdea: "Stories help us understand ourselves and connect to others; texts construct our personal, social, and cultural identity.",
  essentialQuestion: "How do the stories we tell shape who we are — and how does a writer make one small moment on the page feel real?",
  lever: "Showing, not telling — using concrete sensory detail and action to carry meaning that a flat statement cannot. The companion constraint is scope: one small moment, not a whole life. The graded composition is judged hardest on this.",
};

// ---------- 5.1 Teacher-Facing Unit Overview ----------
const TEACHER = {
  summary:
    "This opening unit builds the year's diagnostic baseline while establishing the classroom as a community of readers and writers. Students read short personal narratives and stories, learn to make a small moment vivid through showing rather than telling, and write a personal-narrative paragraph that is kept as the Term 1 diagnostic and returned in June for a growth comparison. A low-stakes oral strand — the \"One Small Thing\" object talk — front-loads speaking and listening, gives reluctant writers a second way in, and generates the raw material students later write about. The unit closes with a \"This Is Me\" showcase pairing each student's object talk with their finished narrative.",
  bigIdeas: [
    "Texts are a source of creativity and joy, and stories help us understand ourselves and connect to others.",
    "Language constructs personal, social, and cultural identity.",
    "Exploring texts and how they are made helps us understand ourselves and the world.",
  ],
  essentialQuestions: [
    "How do the stories we tell shape who we are?",
    "What does a writer do to make a moment feel real to a reader?",
    "How is showing different from telling — and why does it matter?",
    "How do we listen and respond so that everyone in the room is heard?",
  ],
  competencies: {
    "Comprehend & Connect (reading, listening, viewing)": [
      "Apply a variety of reading strategies (predicting, questioning, visualizing, inferring) to comprehend personal narratives and short stories.",
      "Recognize how literary elements (character, setting) and a writer's choices shape meaning.",
      "Recognize how language constructs personal, social, and cultural identity.",
      "Use metacognitive strategies — reflecting on oneself as a reader and writer.",
    ],
    "Create & Communicate (writing, speaking, representing)": [
      "Write a personal-narrative paragraph using the full writing process (planning, drafting, revising, editing, publishing).",
      "Use oral-language strategies in a prepared talk and in small-group discussion: focusing on the speaker, asking clarifying questions, taking turns, building on others' ideas.",
      "Use English language conventions with increasing accuracy at the sentence level.",
    ],
  },
  content: [
    "Story/text forms and functions; the personal narrative as a form.",
    "Literary elements: character (traits shown through action), setting (time, place, atmosphere), and basic narrative structure.",
    "Language conventions (foundational): subject and predicate; the complete sentence; the sentence fragment.",
    "Features of oral language: focusing on a speaker, clarifying questions, turn-taking, and simple vocal delivery.",
    "Metacognitive strategies: reflecting on self as reader and writer.",
  ],
  goals: [
    "Students can distinguish showing from telling and revise a telling sentence into a showing passage.",
    "Students can narrow a broad topic to one small, significant moment.",
    "Students can write a focused personal-narrative paragraph that shows rather than tells.",
    "Students can identify and repair a sentence fragment and name the subject and predicate of a sentence.",
    "Students can deliver a short prepared talk and participate in small-group discussion using named oral strategies.",
    "Students can reflect on their own strengths and next steps as a reader and writer.",
  ],
  vocab: [
    "narrative", "personal narrative", "small moment", "showing vs. telling",
    "sensory detail", "character", "trait", "setting", "atmosphere",
    "subject", "predicate", "sentence fragment", "revise", "edit",
    "inference", "visualize",
  ],
  grammar: [
    "Subject and predicate — every complete sentence needs both.",
    "The complete sentence vs. the fragment — four common fragment types (missing subject, missing verb, subordinate-clause-alone, phrase-alone) and how to repair each.",
    "Parts of speech introduced as needed to name what a sentence is missing (noun, verb).",
    "Basic end punctuation and capitalization revisited in the editing stage.",
  ],
  outcomes: {
    Reading: "Apply predicting, questioning, visualizing, and inferring to short personal narratives and stories; identify character and setting and explain a choice the writer made.",
    Writing: "Plan and draft a focused personal-narrative paragraph; revise for showing-not-telling; edit for complete sentences and conventions.",
    Speaking: "Deliver a 1–2 minute prepared object talk with simple vocal control; contribute to small-group discussion using a listening protocol.",
    Listening: "Focus on a speaker, ask a clarifying question, and build on another student's idea in discussion.",
  },
  assessmentPlan: {
    formative: [
      "Six-word story and \"Find Someone Who…\" reading survey (L1) — engagement and reading-identity check, not graded.",
      "Reading-strategy exit tickets across L2–L7.",
      "\"One Small Thing\" object talk (L4) — light 4-point speaking check on the speaking descriptor; genuinely low-stakes.",
      "Showing-vs-telling conversions and fragment-repair checks (L5, L8–L9).",
      "Revision and editing evidence on the draft (L12–L13).",
    ],
    summative: [
      "Personal-narrative paragraph — the Term 1 diagnostic writing sample, scored on the 4-point Proficiency Scale using the narrative rubric. Kept on file and returned in June.",
      "\"This Is Me\" showcase (L14) — object talk + narrative presented together, assessed on the presentation rubric (4-point).",
      "Unit test (60 marks) — reading strategies, literary terms, and sentence grammar, plus a short passage with comprehension and a constructed response.",
    ],
    note: "September is a diagnostic month. The 60-mark unit test is built to full spec, but its stakes should be reported lightly; the diagnostic narrative is the piece that carries forward. The practice test (40 marks) mirrors the unit test and can be used as a review or a low-stakes checkpoint.",
  },
  pacing:
    "14 lessons across roughly the first four weeks. Week 1 = launch, reading strategies, and the object-talk build (L1–L4). Week 2 = the lever and literary elements (L5–L7). Week 3 = sentence grammar and planning (L8–L10). Week 4 = draft, revise, edit, and showcase (L11–L14). Pacing is flexible; the object talks in L4 may run into a second period depending on class size.",
  materials: [
    "Fresh Ink (Giles, ed.) — short-story and personal-narrative selections.",
    "iWonder 8 anthology — shorter non-fiction and narrative pairings.",
    "Projector for the lesson decks; student worksheets (provided).",
    "One object, photo, or small artifact per student for the \"One Small Thing\" talk (letter home / notice in L1).",
    "Chart paper or a shared doc for the class \"showing bank\".",
  ],
  differentiation: {
    support: [
      "Telling-to-showing conversion tables with the sensory categories pre-labelled.",
      "Sentence frames and stems for both the talk and the written narrative.",
      "Partially completed planning organizers (the moment is chosen; students add the sensory detail).",
      "Sensory word banks by sense; a fragment-repair checklist with worked examples.",
      "Option to deliver the object talk to a small group or the teacher rather than the whole class.",
    ],
    extension: [
      "Multi-paragraph narrative option instead of the single paragraph.",
      "Add dialogue (correctly punctuated) or an in-media-res opening.",
      "Revise a published mentor sentence and justify the change in a margin note.",
      "Take on a discussion-leader role in the showcase, posing follow-up questions to peers.",
    ],
  },
  ellNotes: [
    "Front-load the unit vocabulary with visuals and cognates where available; keep the sensory word banks posted all unit.",
    "For the object talk, allow rehearsal with a partner and permit a first-language planning note before the English draft.",
    "Provide the mentor narratives in a chunked, visually supported format for developing readers.",
    "The showing-vs-telling lever is highly transferable for ELL students because it trades abstract statement for concrete, picturable language.",
  ],
  crossCurricular: [
    "Social Studies / Career Education: identity, community, and personal story.",
    "Arts Education: the object talk as a small piece of oral storytelling and performance.",
    "Advisory / Core Competencies: Positive Personal & Cultural Identity is the anchor competency for the month.",
  ],
};

// ---------- 5.2 Student-Facing Unit Introduction ----------
const STUDENT = {
  whatWeLearn: [
    "How to turn a small moment from your own life into a story a reader can see and feel.",
    "The difference between telling your reader something and showing it — and how to do the showing.",
    "How to read a story like a writer: predicting, questioning, picturing it, and reading between the lines.",
    "How to build a complete sentence and fix one that is broken.",
    "How to tell a short story out loud about something that matters to you — and how to be a good listener when it is someone else's turn.",
  ],
  whyItMatters:
    "The stories you tell — out loud and on the page — are part of how people come to know you. This month you will learn to make one small moment real for a reader, a skill you will use in every kind of writing this year. You will also start a piece of writing that you will see again in June, so you can look back and see how far you have come.",
  keyVocab: [
    "narrative", "small moment", "showing vs. telling", "sensory detail",
    "character", "setting", "atmosphere", "subject", "predicate",
    "sentence fragment", "revise", "edit",
  ],
  keySkills: [
    "Revise a 'telling' sentence into a 'showing' one.",
    "Narrow a big topic down to one small moment.",
    "Write a focused personal-narrative paragraph using the writing process.",
    "Find and fix a sentence fragment.",
    "Give a short talk and listen well in a group.",
  ],
  expectations: [
    "Bring your object (or a photo of it) for your 'One Small Thing' talk by the day it is due.",
    "Try the showing-not-telling move even when telling feels easier — that is the whole point of the unit.",
    "Keep every draft. Your first paragraph becomes part of your record for the year.",
    "Listen the way you would want to be listened to: eyes on the speaker, one clarifying question ready.",
    "Ask for a scaffold if you need one, and reach for the extension if you are ready for more.",
  ],
};

// ---------- 5.3 Lesson Plans (all 14) ----------
// Each: n, title, accentName (informational), duration, objective, standards,
// vocab, materials, sequence[], assessment, differentiation{support,extension}, homework
const LESSONS = [
  {
    n: 1, title: "Launch — What Makes a Story? (Getting to Know Each Other)",
    objective: "Students activate prior knowledge about stories, begin building classroom community, and understand the idea of a 'small moment' as the seed of a personal narrative.",
    standards: "Comprehend & Connect: recognize how language constructs identity. Create & Communicate: use oral-language strategies in small-group discussion. Core Competency: Positive Personal & Cultural Identity.",
    vocab: ["narrative", "small moment"],
    materials: ["Deck 1", "Worksheet 1 (six-word frame, 'Find Someone Who…' bingo)", "Object-talk letter/notice to send home"],
    sequence: [
      "Warm-up icebreaker — SIX-WORD STORY: model the tradition (a whole story in six words), then each student writes a six-word story or six-word 'about me'. Share a handful aloud. (Plants: every word carries weight; a story can live in a small space.)",
      "'FIND SOMEONE WHO…' reading/story bingo — students move around the room to find classmates who match squares ('has read a book more than once', 'cried at a movie', 'tells the same story every family dinner'). Surfaces reading identity and warms the room.",
      "Mini-lesson: what is a personal narrative? Contrast a 'whole life' topic with a 'small moment'. Model narrowing 'my summer' down to 'the ten seconds before I jumped off the dock'.",
      "Introduce the 'One Small Thing' object talk: preview that in a few days each student will bring one object, photo, or artifact and talk about it for 1–2 minutes. Hand out / explain the take-home notice.",
      "Exit ticket: write down one small moment you might tell a story about.",
    ],
    assessment: "Formative — six-word stories collected; exit-ticket moment reviewed for the object-talk build. Not graded.",
    diff: { support: "Six-word frame with two examples and a word bank; bingo squares read aloud.", extension: "Write three six-word stories in three different moods." },
    homework: "Choose an object, photo, or small artifact for your 'One Small Thing' talk. Bring it (or a photo) by Lesson 4.",
  },
  {
    n: 2, title: "Reading Like a Writer — Strategies on a Personal Narrative",
    objective: "Students apply predicting, questioning, visualizing, and inferring to a short personal narrative, and reflect on themselves as readers.",
    standards: "Comprehend & Connect: apply reading strategies; use metacognitive strategies (self as reader). Create & Communicate: partner interview and small-group share.",
    vocab: ["inference", "visualize"],
    materials: ["Deck 2", "Worksheet 2 (strategy log + reading-identity interview)", "Short personal narrative (Fresh Ink or iWonder 8)"],
    sequence: [
      "Warm-up: partner READING-IDENTITY INTERVIEW — students interview a partner (favourite book / a book you gave up on / where you read / do you reread) and then introduce their partner to a small group. Doubles as a getting-to-know-you and the 'self as reader' work the month reports on.",
      "Model the four strategies on the opening of the mentor narrative: predict from the title, question as you read, visualize a described moment, infer a feeling that is shown but not stated.",
      "Guided practice: read the next section together; students log one prediction, one question, one thing they pictured, one inference (Worksheet 2).",
      "Independent read of the final section with the strategy log.",
      "Share out; name which strategy helped most and why.",
      "Exit ticket: one sentence on 'the kind of reader I am'.",
    ],
    assessment: "Formative — strategy log checked for evidence of all four strategies; exit ticket read for the metacognitive strand.",
    diff: { support: "Strategy log with sentence stems ('I predict…', 'I wonder…', 'I picture…', 'I can tell…'); chunked text.", extension: "Add a text-to-self or text-to-world connection with a reason." },
    homework: "Finish the strategy log if incomplete; keep preparing your object.",
  },
  {
    n: 3, title: "Preparing the Talk — Telling a Small Story Out Loud",
    objective: "Students plan a short spoken narrative about their object, practising 'showing' out loud before they do it on the page.",
    standards: "Create & Communicate: use oral-language strategies; plan a short prepared talk. Comprehend & Connect: listen with focus.",
    vocab: ["small moment", "sensory detail"],
    materials: ["Deck 3", "Worksheet 3 (talk-planning frame + speaking stems)"],
    sequence: [
      "Hook: teacher models a 60-second object talk about one real object — deliberately SHOWING one small moment, not listing facts about the object.",
      "Name the move: the best object talks tell one small moment, not a résumé of the object. Contrast a 'telling' talk with a 'showing' talk.",
      "Planning frame: students choose the ONE moment their object is connected to and plan an opening line, the moment, and why it matters (Worksheet 3).",
      "Speaking stems and simple delivery: pace, volume, and one pause for effect. Quick partner rehearsal.",
      "Set the listening protocol for L4: eyes on the speaker, one clarifying question ready, no interrupting.",
    ],
    assessment: "Formative — planning frame checked before delivery; rehearsal observed.",
    diff: { support: "Talk-planning frame with the moment pre-scoped and opening-line options; option to deliver to a small group or the teacher in L4.", extension: "Plan a deliberate in-media-res opening ('It was already too late when…')." },
    homework: "Rehearse your talk once out loud. Bring your object tomorrow.",
  },
  {
    n: 4, title: "\"One Small Thing\" — Object Talks",
    objective: "Students deliver a 1–2 minute prepared object talk and practise focused, responsive listening.",
    standards: "Create & Communicate: deliver a prepared talk with simple vocal control. Comprehend & Connect: focus on a speaker, ask a clarifying question. Core Competency: Positive Personal & Cultural Identity; Communication.",
    vocab: ["small moment"],
    materials: ["Deck 4", "Worksheet 4 (peer-listening prompt + self-reflection)", "Speaking descriptor (4-point)"],
    sequence: [
      "Restate the listening protocol and the speaking descriptor students are being coached on (not graded harshly — a light check).",
      "Object talks in a rotation (small groups or whole class depending on size). Each speaker gets one clarifying question from a listener.",
      "Listeners complete a light peer-listening prompt: one thing you pictured, one question you'd ask (Worksheet 4).",
      "After each round, a 20-second reset and a quick 'notice' (what made a talk vivid?).",
      "Close: speaker self-reflection — the moment I chose and one thing I'd do differently.",
      "Bridge: 'You just showed a moment out loud. Next class we do it on the page.'",
    ],
    assessment: "Formative / light summative — 4-point speaking check on the speaking descriptor. Low stakes.",
    diff: { support: "Deliver to a small group or the teacher; notes permitted; talk may be shortened to one clear moment.", extension: "Take a discussion-leader role, posing a follow-up question to each speaker in the group." },
    homework: "None — reset before the writing sequence.",
  },
  {
    n: 5, title: "Showing, Not Telling — The Lever",
    objective: "Students distinguish showing from telling and revise a telling sentence into a showing passage using sensory detail and action.",
    standards: "Create & Communicate: use descriptive detail; begin the writing process. Content: story forms and literary technique.",
    vocab: ["showing vs. telling", "sensory detail"],
    materials: ["Deck 5", "Worksheet 5 (telling→showing conversion table)", "Class 'showing bank' chart"],
    sequence: [
      "Connect to L4: the object talks that landed showed a moment — they didn't announce a feeling. That is the whole unit.",
      "Define the move: TELLING states a fact or feeling ('I was nervous'); SHOWING gives detail and action so the reader infers it ('My hands wouldn't stay still, so I jammed them into my pockets').",
      "Model three conversions on the board across different senses; build the class 'showing bank' of strong verbs and sensory words.",
      "Guided practice: convert three telling sentences together using the conversion table (Worksheet 5).",
      "Independent practice: convert four more; then take ONE and expand it into a 3–4 sentence showing passage.",
      "Share strong conversions; add to the showing bank. Exit ticket: convert one last telling sentence.",
    ],
    assessment: "Formative — conversion table checked; the expanded passage is the first real showing-not-telling evidence.",
    diff: { support: "Conversion table with sensory categories pre-labelled and a sense-by-sense word bank; two worked examples.", extension: "Convert without the table; add a line that shows a feeling changing." },
    homework: "Convert one telling sentence you find in your own reading or speech.",
  },
  {
    n: 6, title: "Character on the Page — Traits Through Action",
    objective: "Students learn that character is revealed through action and detail, and identify traits shown (not stated) in a text.",
    standards: "Comprehend & Connect: recognize literary elements (characterization). Content: literary elements.",
    vocab: ["character", "trait"],
    materials: ["Deck 6", "Worksheet 6 (trait-evidence table)", "Short mentor excerpt"],
    sequence: [
      "Warm-up: a one-line 'telling' character statement ('She was kind') vs a 'showing' one ('She gave away her lunch and said she wasn't hungry'). Link straight back to L5.",
      "Mini-lesson: a trait is a claim; the action or detail is the evidence. Round vs flat (term only, light touch).",
      "Model on the mentor excerpt: name a trait, point to the exact action that shows it.",
      "Guided + independent: fill a trait-evidence table for two characters (Worksheet 6) — trait, the evidence, why it fits.",
      "Apply to the students' own writing: what does YOUR small moment show about you? (Sets up the narrative.)",
      "Exit ticket: one trait + one piece of showing evidence for a character or for yourself.",
    ],
    assessment: "Formative — trait-evidence table checked for claim-plus-evidence pairing.",
    diff: { support: "Trait-evidence table with the traits supplied; students locate the evidence.", extension: "Find a trait the character shows but would deny having." },
    homework: "None.",
  },
  {
    n: 7, title: "Setting — Time, Place, and Atmosphere",
    objective: "Students understand setting as time, place, and atmosphere, and see how setting detail creates mood.",
    standards: "Comprehend & Connect: recognize literary elements (setting). Content: literary elements; atmosphere.",
    vocab: ["setting", "atmosphere"],
    materials: ["Deck 7", "Worksheet 7 (setting + atmosphere builder)", "Two short setting passages"],
    sequence: [
      "Warm-up: read two short passages of the SAME place written in two moods; students name the feeling and the details that created it.",
      "Mini-lesson: setting = time + place; atmosphere = the feeling those details create. The writer chooses details on purpose.",
      "Model: take a neutral place (a school hallway) and write it two ways — welcoming and lonely — changing only the details.",
      "Guided + independent: students build the setting of THEIR small moment and choose an atmosphere, listing the sensory details that create it (Worksheet 7).",
      "Share; notice how a detail choice changes the feeling.",
      "Exit ticket: three sensory details that set the atmosphere of your moment.",
    ],
    assessment: "Formative — setting/atmosphere builder checked; feeds directly into the draft.",
    diff: { support: "Setting builder with sense prompts and an atmosphere word list; the two-mood model annotated.", extension: "Write the same setting in a third, more complex mood (e.g., bittersweet)." },
    homework: "None.",
  },
  {
    n: 8, title: "Building Blocks — Subject & Predicate, the Complete Sentence",
    objective: "Students identify the subject and predicate of a sentence and understand what makes a sentence complete.",
    standards: "Create & Communicate: use language conventions with increasing accuracy. Content: language conventions (RSS scope: subject/predicate).",
    vocab: ["subject", "predicate"],
    materials: ["Deck 8", "Worksheet 8 (identify + build; cloze)"],
    sequence: [
      "Warm-up: which of these is a complete thought? Sort five items into 'complete' and 'not yet'.",
      "Mini-lesson: every complete sentence has a SUBJECT (who/what it's about) and a PREDICATE (what they do / what's said about them). Name the noun and verb as needed.",
      "Model: label subject and predicate in five sentences; then build sentences from a subject-only or predicate-only start.",
      "Guided + independent: identify subject and predicate; complete cloze sentences by supplying the missing part (Worksheet 8, word bank provided).",
      "Apply: check two sentences from your own setting-builder — do they have both parts?",
      "Exit ticket: write one sentence and underline the subject once, the predicate twice.",
    ],
    assessment: "Formative — identification and cloze checked; sets up fragment work in L9.",
    diff: { support: "Colour-coded model (subject / predicate); cloze with a word bank and the first letter given.", extension: "Build sentences with compound subjects or compound predicates and label both." },
    homework: "None.",
  },
  {
    n: 9, title: "Fragments — Spotting and Fixing",
    objective: "Students recognize the common sentence fragment types and repair them into complete sentences.",
    standards: "Create & Communicate: edit for language conventions. Content: sentence fragments (RSS scope).",
    vocab: ["sentence fragment"],
    materials: ["Deck 9", "Worksheet 9 (spot + repair; fragment-repair checklist)"],
    sequence: [
      "Warm-up: fragment or sentence? Quick sort, building on L8's subject/predicate test.",
      "Mini-lesson: four common fragments — missing subject, missing verb, a subordinate clause left alone, a phrase left alone — and how to repair each.",
      "Model: repair one of each type, naming what was missing and how it was fixed.",
      "Guided + independent: spot fragments in a short passage and repair them using the fragment-repair checklist (Worksheet 9).",
      "Apply: hunt your own object-talk notes or setting-builder for a fragment; fix it.",
      "Exit ticket: repair two fragments and name the type of each.",
    ],
    assessment: "Formative — repair accuracy checked; this is the editing skill the draft is held to in L13.",
    diff: { support: "Fragment-repair checklist with worked examples; passage fragments pre-underlined.", extension: "Write a fragment on purpose for a stylistic effect and explain when that is (and isn't) allowed." },
    homework: "None.",
  },
  {
    n: 10, title: "Choosing the Moment — Planning the Narrative",
    objective: "Students select one small significant moment and plan a personal-narrative paragraph with a graphic organizer.",
    standards: "Create & Communicate: use the writing process (planning). Content: narrative form; introduction to graphic organizers (RSS scope).",
    vocab: ["small moment", "revise", "edit"],
    materials: ["Deck 10", "Worksheet 10 (narrative planning organizer)"],
    sequence: [
      "Connect: you have a moment (your object), a way to make it vivid (showing), character and setting tools, and complete sentences. Now we plan.",
      "Mini-lesson: the shape of a personal-narrative paragraph — a hook that drops us into the moment, the moment shown beat by beat, and a closing line that lands why it mattered.",
      "Model: plan the teacher's own moment on the organizer, thinking aloud about what to keep and cut (scope: one moment).",
      "Independent: students complete the planning organizer for their moment — hook idea, 3–4 showing beats, the 'why it matters' line (Worksheet 10).",
      "Quick partner check: is this ONE moment, or is it drifting into a whole day?",
      "Exit ticket: your one-sentence hook.",
    ],
    assessment: "Formative — organizer checked for scope (one moment) and for showing beats before drafting.",
    diff: { support: "Organizer with the moment pre-scoped and beat prompts; a bank of hook openings.", extension: "Plan a second, contrasting opening and choose the stronger one with a reason." },
    homework: "Bring your organizer to the drafting lesson.",
  },
  {
    n: 11, title: "Drafting the Narrative Paragraph",
    objective: "Students draft a focused personal-narrative paragraph from their plan, prioritizing showing over telling.",
    standards: "Create & Communicate: use the writing process (drafting).",
    vocab: ["revise"],
    materials: ["Deck 11", "Worksheet 11 (drafting page with beat scaffold)"],
    sequence: [
      "Mini-lesson: drafting rules for today — write the whole moment through without stopping to fix; show, don't tell; keep to the one moment.",
      "Model: draft the first two beats from the teacher's organizer live, showing thinking (not perfection).",
      "Independent drafting from the organizer, quiet writing time, teacher conferencing with 4–5 students.",
      "Mid-point nudge: reread and mark one spot that is telling — leave it flagged for revision (don't fix yet).",
      "Close: each student marks one line they're proud of and one they'll return to.",
    ],
    assessment: "Formative — draft collected or conferenced; completeness and scope checked, not yet polish.",
    diff: { support: "Drafting page with the beats from the organizer pre-listed and sentence stems for transitions.", extension: "Draft an alternative ending and keep both for the revision lesson." },
    homework: "Finish the draft to the end of the moment if class time ran short.",
  },
  {
    n: 12, title: "Revising for Showing, Not Telling",
    objective: "Students revise their draft to replace telling with showing and to sharpen sensory and action detail — a content revision, not editing.",
    standards: "Create & Communicate: use the writing process (revising); distinguish revising from editing.",
    vocab: ["revise", "edit"],
    materials: ["Deck 12", "Worksheet 12 (revision checklist + telling-hunt)"],
    sequence: [
      "Mini-lesson: revising changes WHAT the writing says and shows (meaning); editing fixes HOW it's written (mechanics). Today is revising only.",
      "Model: take a telling line from the teacher's draft and revise it into showing, using the class showing bank.",
      "'Telling hunt': students find every telling line in their own draft and revise at least two into showing (Worksheet 12).",
      "Partner revision: read a partner's paragraph and mark one place you couldn't picture — the writer revises for the reader.",
      "Add or sharpen one setting/atmosphere detail and one character-through-action detail.",
      "Exit ticket: the strongest showing line in your paragraph.",
    ],
    assessment: "Formative — revision evidence checked (telling lines converted); partner feedback used.",
    diff: { support: "Revision checklist with a fixed telling-hunt list and the showing bank attached.", extension: "Revise for rhythm too — vary one short and one long sentence for effect." },
    homework: "None — bring the revised draft to editing.",
  },
  {
    n: 13, title: "Editing & Model Annotation — Complete Sentences and Conventions",
    objective: "Students edit their draft for complete sentences (no fragments) and conventions, and annotate a model paragraph to see the target.",
    standards: "Create & Communicate: use the writing process (editing); edit for conventions. Content: fragments, subject/predicate applied.",
    vocab: ["edit"],
    materials: ["Deck 13", "Worksheet 13 (model annotation — no cloze; editing checklist)"],
    sequence: [
      "MODEL ANNOTATION (no cloze by convention): students mark up a strong model narrative paragraph — underline showing lines, box the hook, flag the 'why it matters' line, and confirm every sentence is complete.",
      "Name the target from the model: what makes it proficient?",
      "Editing pass 1 — fragments: apply the L9 checklist to their own paragraph; repair every fragment.",
      "Editing pass 2 — conventions: capitalization, end punctuation, obvious spelling.",
      "Peer edit: swap and check a partner's paragraph against the editing checklist.",
      "Prepare the clean copy for the showcase.",
    ],
    assessment: "Formative — editing checklist completed; the clean copy is the diagnostic piece that will be scored on the 4-point scale.",
    diff: { support: "Editing checklist chunked into one-target passes; model annotation partly done as an example.", extension: "Edit a deliberately error-seeded passage against the checklist, then their own." },
    homework: "Finalize the clean copy for the 'This Is Me' showcase.",
  },
  {
    n: 14, title: "\"This Is Me\" Showcase — Publish, Present & Reflect",
    objective: "Students present their object talk and finished narrative together, participate in a discussion protocol, and reflect metacognitively on the unit.",
    standards: "Create & Communicate: publish and present; use oral-language strategies. Comprehend & Connect: metacognition (self as reader/writer). Core Competency: Positive Personal & Cultural Identity; Communication.",
    vocab: ["narrative", "small moment"],
    materials: ["Deck 14", "Worksheet 14 (showcase reflection)", "Project brief (This Is Me)", "Presentation rubric (4-point)"],
    sequence: [
      "Set the showcase: each student presents their object and reads (or tells) their narrative moment — the spoken and written versions of the same small moment, side by side.",
      "Discussion protocol: after each presentation, one appreciation and one clarifying question from the audience.",
      "Presentations in rotation (groups or whole class), assessed on the presentation rubric.",
      "Publish: paragraphs go into the writing record / portfolio; this is the kept Term 1 diagnostic.",
      "Metacognitive reflection: what changed between your out-loud version (L4) and your written version? What kind of reader and writer are you becoming? (Worksheet 14).",
      "Close the unit and preview Unit 2.",
    ],
    assessment: "Summative — 'This Is Me' showcase on the presentation rubric (4-point). The narrative is filed as the diagnostic. Reflection informs goal-setting.",
    diff: { support: "Present to a small group; a sentence-framed reflection.", extension: "Reflect in a short written paragraph comparing the spoken and written craft choices." },
    homework: "None — unit complete.",
  },
];

module.exports = { UNIT, TEACHER, STUDENT, LESSONS };
