// ELL12 U1 L10 — Making It Better. ALL content here; the renderer holds the design.
// Rebuilt Sep 26 2026 from the v13 L11 "Revising" deck + Core sheets, to the standing orders, on the L05–L09 pattern.
// Approved spec Sep 26: drafts come back today with one strength + one fix (Week 2 draft read) and Part C is built on that fix;
// no collection today. Outcomes: ELL 1 W7 + W2; ELL 2 W2 + W9 (revise and edit; W7 moves to L11 with editing).
// Revision stays on this sheet (no writing above the line on the L9 draft); students star each changed sentence on the draft.
// Models: flat versions of L9's "My Uncle's Shop", shown beside the real ones.
// Unit order: L9 Writing My Place · L10 this · L11 Cleaning It Up
const vocab = [
  ["revise", "to change writing to show more"],
  ["edit", "to fix capitals, marks and spelling"],
  ["flat word", "a word that shows nothing: nice, good, big"],
  ["stronger word", "a word that shows more: warm, huge"],
  ["sense detail", "what you see, hear, smell or feel"],
  ["reason", "why it matters: it starts with because"],
  ["before", "the sentence as you first wrote it"],
  ["after", "the same sentence, made better"]];
const bankWords = ["sense detail", "after", "edit", "reason", "flat word", "revise", "before", "stronger word"];
const helpLine = "Stuck? Fill in a help slip: “Can you check my …?”  “I need help with …”";
const F1 = "My place is my uncle’s shop. I see shelves and a door. The shelves are next to the window. It is nice. The shop is small, but it is busy. I like it there.";
const M1 = "My place is my uncle’s shop. I see old shelves and a red door. The shelves are next to the window. I smell coffee, and I hear the radio. The shop is small, but it is busy. It matters to me because my uncle teaches me there.";
const F2 = "On Saturday mornings, my uncle’s shop is where I go. There are shelves next to the window. The shop is nice. When customers pay, I hold the money. The till is on a counter by the door. The shop is small, but it is always busy. I like this shop a lot.";
const M2 = "On Saturday mornings, my uncle’s shop is where I feel useful. Old shelves lean next to the window, full of rice bags and tins. The radio plays in the back, and the shop smells of coffee. When customers pay, the cold coins feel heavy in my hand. The till sits on a wooden counter by the door, so I can greet everyone who comes in. The shop is small, but it is always busy. This shop matters to me because my uncle trusts me there.";

module.exports = {
 course: "ELL12",
 meta: { unit: 1, unitTitle: "Who I Am", lesson: 10, title: "Making It Better", subtitle: "Revise: show more", month: "September" },
 banner: { obj: "Revise your draft: add a sense, a stronger word, a reason.",
   std: "ELL 1: W7 describing words · W2 joining with and  •  ELL 2: W2 connect ideas with because · W9 revise", lit: ["COM", "TH", "PS"] },
 plan: {
  objective: "Students revise their Lesson 9 drafts, starting from the fix you wrote: sense details, stronger words, a reason with because. Revising only; editing is next lesson.",
  outcomes: "ELL 1: W7 · W2. ELL 2: W2 · W9 (revising half; editing and W7 in Lesson 11).",
  materials: "Deck · ELL 1 and ELL 2 Lesson 10 worksheets · the Lesson 9 drafts with your strength and fix, ready to hand back · help slips",
  timing: "80 minutes",
  steps: [
   ["8", "Warm-up Parts A and B", "In exercise books, five items per level, both levels on one slide. Part A · Vocabulary: ELL 1 stronger words (huge, freezing, tiny, delicious, soft); ELL 2 exact adjectives (ancient, steaming, silent, crowded, spotless). Part B · Grammar: ELL 1 sense verbs (looks, sounds, smells, tastes, feels); ELL 2 because or because of. Reveal one at a time, alternating levels."],
   ["7", "Pump it up", "Warm-up game. A flat sentence goes on the screen; partners have 30 seconds to add a sense or a stronger word, then two or three pairs say theirs. Five sentences, then one good answer for each. English only."],
   ["4", "Title, goals and drafts back", "Read the three goals. Hand back the Lesson 9 drafts. Students read your strength first, then your fix."],
   ["6", "Match the word", "Eight revising words against meanings from a shuffled bank, revealed one at a time, then the key-vocabulary summary."],
   ["4", "Revise, not edit", "Revising changes what the writing shows: a sense, a stronger word, a reason. Editing (capitals, end marks, spelling) is next class."],
   ["8", "Three ways to revise, with the model", "The three ways, each with a before and after from My Uncle’s Shop. Read the flat version of each level in full, then flat and real side by side."],
   ["4", "Read your fix", "Partners read the sentence you marked and their partner suggests one thing to add. English only."],
   ["10", "Worksheet Parts A and B", "Hand out both sheets. Walk Part A and Part B for each level with the worked example. Part A answers one at a time; Part B shows one good answer each."],
   ["24", "Part C: revise your draft", "Walk Part C and show one good answer for each level. Students rewrite the sentence you marked, then one more, before and after; ELL 2 add a new because sentence. They star each changed sentence on the Lesson 9 draft. Circulate: anyone without a fix picks a flat sentence."],
   ["5", "Check and exit ticket", "Part D tick-box check, then the Part E exit ticket. Both sheets stay in the duotang for the clean copy. Next class, then agendas."] ],
  diff: "Support: ELL 1 may choose the stronger word from the Part A pairs for Part C; the three-ways slide can stay up during Part C. Extension: ELL 2 early finishers revise a third flat spot and add a second sense to their ending.",
  assess: "MARKING TODAY: nothing collected. Hand back the Lesson 9 drafts at the start (one strength, one fix each); Part C is built on that fix. Glance at Part C as you circulate. The clean copy is collected at the end of Lesson 11.",
  homework: "None. Keep the Lesson 9 draft and this sheet together in your duotang: you need both for the clean copy in Lesson 11.",
  watch: "Students editing spelling instead of revising. Changes that swap one flat word for another (nice → good). ELL 2 because sentences that give no real reason. Students without a returned draft: give them a flat sentence to start." },
 shape: [["Warm-up: words and grammar", "quick practice"], ["Pump it up", "warm-up game"], ["Your draft is back", "reading feedback"],
   ["Match the word", "vocabulary game"], ["Revise, not edit", "mini-lesson"], ["Three ways to revise", "mini-lesson"],
   ["Read your fix", "partner speaking"], ["Worksheet Parts A and B", "worksheet"], ["Part C: revise your draft", "independent writing"],
   ["Check and exit ticket", "quick write"]],
 sequence: [
  { type: "drill", part: "A", kind: "Vocabulary", lvls: [
    { lvl: "ELL 1", bankLabel: "Stronger words", bank: "soft · tiny · huge · delicious · freezing",
      items: [["Very big is ____.", "huge"], ["Very cold is ____.", "freezing"], ["Very small is ____.", "tiny"],
        ["Very good food is ____.", "delicious"], ["Like a pillow, it is ____.", "soft"]] },
    { lvl: "ELL 2", bankLabel: "Exact adjectives", bank: "spotless · crowded · steaming · ancient · silent",
      items: [["A very old tree is ____.", "ancient"], ["Tea too hot to drink is ____.", "steaming"], ["A room with no sound is ____.", "silent"],
        ["A bus full of people is ____.", "crowded"], ["A very clean floor is ____.", "spotless"]] } ] },
  { type: "drill", part: "B", kind: "Grammar", lvls: [
    { lvl: "ELL 1", bankLabel: "Sense verbs", bank: "looks · smells · feels · tastes · sounds",
      items: [["I hear the bell. It ____ loud.", "sounds"], ["I touch the rug. It ____ soft.", "feels"], ["I eat the mango. It ____ sweet.", "tastes"],
        ["I see the sky. It ____ grey.", "looks"], ["I smell the soup. It ____ good.", "smells"]] },
    { lvl: "ELL 2", bankLabel: "because or because of?", bank: "because · because of",
      items: [["I love it ____ the view.", "because of"], ["I go there ____ it is quiet.", "because"], ["I stay home ____ the snow.", "because of"],
        ["I smile ____ my aunt is there.", "because"], ["It is calm ____ the trees.", "because of"]] } ] },
  { type: "rows", label: "Pump it up", tag: "Warm-up game", head: "Pump it up: how to play", englishOnly: true, rows: [
    ["1", "A flat sentence goes on the screen."], ["2", "With a partner, 30 seconds: add a sense or a stronger word."],
    ["3", "Say your new sentence to the class."], ["Win", "The sentence that shows the most wins the round."]] },
  { type: "rows", label: "Pump it up: try these", tag: "Warm-up game", head: "Pump these up", rows: [
    ["1", "The dog is big."], ["2", "The food is good."], ["3", "The street is loud."], ["4", "My bed is nice."], ["5", "The sky is pretty."]] },
  { type: "rows", label: "Pump it up: good answers", tag: "Warm-up game · one good answer each", head: "Pumped up", rows: [
    ["1", "The dog is huge, and its fur smells like rain."], ["2", "The soup is hot and salty."], ["3", "The street is loud, and horns honk all night."],
    ["4", "My bed is soft and warm."], ["5", "The sky is orange over the sea."]] },
  { type: "speaking", label: "Pump it up: frames", head: "Pump it up: say it like this", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "Read the flat sentence. Add ONE thing. Say the whole new sentence.",
    frames: ["The ______ is ______, and I hear ______.", "The ______ is ______, and it smells like ______.", "A stronger word is ______."] },
  { type: "title", label: "Today’s lesson" },
  { type: "goals", label: "Today’s goals", items: [
    "Make your writing show more.", "Add a sense, a stronger word, or a reason.", "Revise now: spelling comes next class."] },
  { type: "rows", label: "Your draft is back", tag: "Your draft", head: "Your draft is back", icon: "icon-read.png", rows: [
    ["1", "Read my strength first: keep doing that."], ["2", "Read my fix: that is your first job today."],
    ["3", "No fix? Choose one flat sentence yourself."]] },
  { type: "match", label: "Match the word", head: "Match the word", bank: bankWords, words: vocab },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: vocab },
  { type: "rows", label: "Revise, not edit", tag: "Teaching 1 of 2", head: "Revise, not edit", rows: [
    ["Revise (today)", "change what the writing shows: a sense, a stronger word, a reason"],
    ["Edit (next class)", "fix capitals, end marks and spelling"],
    ["Remember", "A flat sentence with perfect spelling is still flat."]] },
  { type: "rows", label: "Three ways to revise", tag: "Teaching 2 of 2", head: "Three ways to revise", rows: [
    ["Add a sense", "It is nice.  →  I smell coffee, and I hear the radio."],
    ["Stronger word", "shelves and a door  →  old shelves and a red door"],
    ["Add a reason", "I like it there.  →  It matters to me because my uncle teaches me there."]] },
  { type: "prose", text: "f1", label: "My Uncle’s Shop, flat (ELL 1)" },
  { type: "prose", text: "f2", label: "My Uncle’s Shop, flat (ELL 2)" },
  { type: "text2", a: "f1", b: "m1", label: "ELL 1: before and after", tag: "Model · ELL 1 · before and after", head: "Before and after: ELL 1" },
  { type: "text2", a: "f2", b: "m2", label: "ELL 2: before and after", tag: "Model · ELL 2 · before and after", head: "Before and after: ELL 2" },
  { type: "speaking", label: "Read your fix", head: "Read your fix", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "Read the sentence I marked to a partner. Your partner suggests ONE thing to add.",
    frames: ["My sentence is: ______.", "You can add a sense: I hear / smell ______.", "A stronger word is ______."] },
  { type: "handout", label: "Hand out the worksheet", note: "ELL 1 and ELL 2 sheets. Name and date first. Keep your Lesson 9 draft open beside it.",
    items: [["A", "stronger word · revise or edit?"], ["B", "add a sense · replace the flat word"], ["C", "revise your draft"], ["D", "check your work"], ["E", "exit ticket", true]],
    foot: "Both sheets stay in your duotang for next class." },
  { type: "walk", part: "1A-A", withExample: true }, { type: "reveals", part: "1A-A" },
  { type: "walk", part: "2A-A", withExample: true }, { type: "reveals", part: "2A-A" },
  { type: "walk", part: "1A-B", withExample: true }, { type: "reveals", part: "1A-B", good: true },
  { type: "walk", part: "2A-B", withExample: true }, { type: "reveals", part: "2A-B", good: true },
  { type: "walk", part: "1A-C", withExample: true }, { type: "reveals", part: "1A-C", good: true },
  { type: "walk", part: "2A-C", withExample: true }, { type: "reveals", part: "2A-C", good: true },
  { type: "walk", part: "1A-D" }, { type: "walk", part: "2A-D" },
  { type: "pages", label: "The whole sheet again" },
  { type: "exit", part: "1A-E", note: "Then both sheets go in your duotang." }, { type: "reveals", part: "1A-E", good: true },
  { type: "exit", part: "2A-E", note: "Then both sheets go in your duotang." }, { type: "reveals", part: "2A-E", good: true },
  { type: "rows", label: "Keep your draft", tag: "Before you go", head: "Keep both sheets", icon: "icon-folder.png", rows: [
    ["1", "Your Lesson 9 draft: every changed sentence has a star."], ["2", "This sheet: your new sentences are in Part C."],
    ["3", "Both go in your duotang."], ["4", "Next class you use both to write a clean copy."]] },
  { type: "nextshape", label: "Next class", head: "Next class: Cleaning It Up", items: [
    ["Warm-up: words and grammar", "quick practice"], ["Warm-up game", "game"], ["Edit one thing at a time", "mini-lesson"],
    ["Using the help slip", "mini-lesson"], ["Read it out loud", "partner speaking"], ["Write your clean copy", "independent writing"], ["Hand in", "clean copy"]] },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", icon: "icon-calendar.png", rows: [
    ["Next class", "Cleaning It Up: edit and write your clean copy."], ["Homework", "None. Keep both sheets in your duotang."],
    ["Remember", "The clean copy is handed in at the end of next class."]] } ],
 sheets: [
  { lvl: "ELL 1", suffix: "1A", label: "ELL 1", objective: "Revise your sentences: add a sense or a stronger word.",
    outcomes: "ELL 1  W7 Familiar words and phrases  •  W2 Compound sentences with and, but, so", vocab,
    remember: "Revising means your writing shows more: a sense or a stronger word. Spelling is next class.", helpLine },
  { lvl: "ELL 2", suffix: "2A", label: "ELL 2", objective: "Revise your paragraph: sense details, stronger words and a reason.",
    outcomes: "ELL 2  W2 Connect ideas using and, but, so, or, because  •  W9 Revise and edit (revising today)", vocab,
    remember: "Revise for what the writing shows: replace flat words, add sense details, add a reason with because. Edit next class.", helpLine } ],
 worksheet: { parts: [
  // ---------------- ELL 1 ----------------
  { key: "1A-A", lvl: "ELL 1", id: "A", title: "Stronger word", kind: "cloze",
    instr: "Write the stronger word: the one that shows more.",
    example: { text: "nice / warm", ans: "warm", tail: "" },
    items: [{ text: "big / huge", ans: "huge", tail: "" }, { text: "fresh / good", ans: "fresh", tail: "" },
      { text: "cold / freezing", ans: "freezing", tail: "" }, { text: "tiny / small", ans: "tiny", tail: "" },
      { text: "nice / soft", ans: "soft", tail: "" }],
    how: "A flat word shows nothing. A stronger word helps the reader see, hear or feel it." },
  { key: "1A-B", lvl: "ELL 1", id: "B", title: "Add a sense", kind: "lines", lines: 2,
    instr: "Add a sense detail with and. Write the whole new sentence.",
    example: { text: "The kitchen is warm.  →", ans: "The kitchen is warm, and it smells like bread." },
    items: [{ text: "My room is quiet.  →", ans: "My room is quiet, and I hear the rain." },
      { text: "The park is green.  →", ans: "The park is green, and it smells like grass." },
      { text: "The window is bright.  →", ans: "The window is bright, and I feel the sun." },
      { text: "The market is busy.  →", ans: "The market is busy, and I hear people talk." },
      { text: "The soup is hot.  →", ans: "The soup is hot, and it smells like ginger." }],
    how: "Keep the sentence. Add a comma, and, then something you see, hear, smell, taste or feel. There is no single right answer." },
  { key: "1A-C", lvl: "ELL 1", id: "C", title: "Revise your draft", kind: "lines", lines: 2, newPage: true,
    instr: "Use your Lesson 9 draft and Mr. Reid’s fix. Write the sentence before, then after. Put a star ★ next to each sentence you changed on your draft. No fix? Choose a flat sentence yourself.",
    example: { text: "Before: The kitchen is nice. (Lina)", ans: "After: The kitchen is warm, and it smells like rice." },
    items: [{ text: "My fix, before:", ans: "It is nice." },
      { text: "After: add a sense.", ans: "I smell coffee, and I hear the radio." },
      { text: "Another sentence, before:", ans: "I see shelves and a door." },
      { text: "After: use a stronger word.", ans: "I see old shelves and a red door." }],
    how: "Copy the sentence as it is now. Then write it again so it shows more. Put a star on your draft so you remember it next class." },
  { key: "1A-D", lvl: "ELL 1", id: "D", title: "Check your work", kind: "check",
    instr: "Read your new sentences. Tick each box when it is true.",
    checks: ["I chose a stronger word.", "I added a sense detail with and.",
      "I rewrote the sentence Mr. Reid marked.", "I put a star by each change on my draft."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "1A-E", lvl: "ELL 1", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then put both sheets in your duotang.",
    items: [{ text: "My best change is …", reveal: "My best change is the red door." }],
    how: "Choose the change that shows the most." },
  // ---------------- ELL 2 ----------------
  { key: "2A-A", lvl: "ELL 2", id: "A", title: "Revise or edit?", kind: "cloze",
    instr: "Write R for a revising change (what the writing shows) or E for an editing change (capitals, marks, spelling).",
    example: { text: "Change ‘nice’ to ‘warm.’", ans: "R", tail: "" },
    items: [{ text: "Add a sense detail.", ans: "R", tail: "" }, { text: "Fix a capital letter.", ans: "E", tail: "" },
      { text: "Fix the spelling of ‘kitchen.’", ans: "E", tail: "" }, { text: "Add because to give a reason.", ans: "R", tail: "" },
      { text: "Add a period.", ans: "E", tail: "" }],
    how: "Revising changes what the reader sees and understands. Editing fixes the mechanics. Today is revising." },
  { key: "2A-B", lvl: "ELL 2", id: "B", title: "Replace the flat word", kind: "lines", lines: 2,
    instr: "Rewrite each sentence with a stronger word or detail instead of the flat word.",
    example: { text: "The food was good.  →", ans: "The food was warm and salty." },
    items: [{ text: "It was a big kitchen.  →", ans: "It was a wide, bright kitchen." },
      { text: "The music was good.  →", ans: "The music was slow and soft." },
      { text: "The room was nice.  →", ans: "The room was warm and still." },
      { text: "The street was noisy.  →", ans: "The street roared with buses and horns." },
      { text: "The garden was pretty.  →", ans: "The garden was bright with red flowers." }],
    how: "Cut the flat word. Put in a word or detail the reader can see, hear or feel. There is no single right answer." },
  { key: "2A-C", lvl: "ELL 2", id: "C", title: "Revise your paragraph", kind: "lines", lines: 2, newPage: true,
    instr: "Use your Lesson 9 paragraph and Mr. Reid’s fix. Write each change in full. Put a star ★ next to each sentence you changed in your paragraph. No fix? Choose a flat spot yourself.",
    example: { text: "Before: The shop is nice.", ans: "After: The radio plays in the back, and the shop smells of coffee." },
    items: [{ text: "My fix, before:", ans: "There are shelves next to the window." },
      { text: "After:", ans: "Old shelves lean next to the window, full of rice bags and tins." },
      { text: "Another flat spot, before:", ans: "When customers pay, I hold the money." },
      { text: "After:", ans: "When customers pay, the cold coins feel heavy in my hand." },
      { text: "My new because sentence:", ans: "This shop matters to me because my uncle trusts me there." }],
    how: "Copy the flat sentence, then write it again with a sense or a stronger word. Your because sentence gives a real reason. Star each change in your paragraph." },
  { key: "2A-D", lvl: "ELL 2", id: "D", title: "Check your work", kind: "check",
    instr: "Read your new sentences. Tick each box when it is true.",
    checks: ["I replaced flat words with stronger ones.", "I added at least one sense detail.", "I rewrote the sentence Mr. Reid marked.",
      "I added a real reason with because.", "I starred each change in my paragraph.", "I did not fix spelling yet: that is next class."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "2A-E", lvl: "ELL 2", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then put both sheets in your duotang.",
    items: [{ text: "My best change is …, because …", reveal: "My best change is the cold coins, because the reader can feel them." }],
    how: "Choose the change that shows the most, and say why." } ] },
 texts: {
  f1: { lvl: "ELL 1 · before", title: "My Uncle’s Shop (flat)", body: F1 },
  m1: { lvl: "ELL 1 · after", title: "My Uncle’s Shop", body: M1 },
  f2: { lvl: "ELL 2 · before", title: "My Uncle’s Shop (flat)", body: F2 },
  m2: { lvl: "ELL 2 · after", title: "My Uncle’s Shop", body: M2 } }
};
