// ELL12 U1 L07 — One Clear Picture (capitals, end marks, different openings). ALL content here; the renderer holds the design.
// Rebuilt Sep 21 2026 from the v13 L08 deck + Core sheets, to the standing orders, on the L05/L06 pattern.
// Unit order: L6 Joining Ideas · L7 this · L8 Planning My Place
const bankWords = ["variety", "period", "comma", "capital letter", "question mark", "proper noun", "exclamation mark", "sentence opening"];
const vocab = [
  ["capital letter", "a big letter: A, B, C"],
  ["period", "the end mark for a statement: ."],
  ["question mark", "the end mark for a question: ?"],
  ["exclamation mark", "the end mark for strong feeling: !"],
  ["proper noun", "a special name that needs a capital: Lina, Richmond"],
  ["sentence opening", "the first word or words of a sentence"],
  ["variety", "not all the same"],
  ["comma", "a pause mark; put one after an opening"]];
const helpLine = "Stuck? Fill in a help slip: \u201CCan you check my \u2026?\u201D  \u201CI need help with \u2026\u201D";

module.exports = {
 course: "ELL12",
 meta: { unit: 1, unitTitle: "Who I Am", lesson: 7, title: "One Clear Picture", subtitle: "Capitals, end marks and different openings", month: "September" },
 banner: { obj: "Write clean sentences: capitals, end marks and different openings.",
   std: "ELL 1: W5 capitals and end punctuation \u00B7 W1 simple sentences  \u2022  ELL 2: W7 capitals and punctuation \u00B7 W1 simple sentences", lit: ["COM", "TH"] },
 plan: {
  objective: "Students clean up their sentences before drafting: capitals and end marks (ELL 1), and different openings with a comma (ELL 2).",
  outcomes: "ELL 1: W5 capitals and end marks \u00B7 W1. ELL 2: W7 capitals and punctuation \u00B7 W1.",
  materials: "Deck \u00B7 ELL 1 and ELL 2 Lesson 7 worksheets, one each plus spares \u00B7 exercise books \u00B7 help slips in the box \u00B7 the eight game sentences (below)",
  timing: "80 minutes",
  steps: [
   ["10", "Warm-up Parts A and B", "In exercise books. Part A \u00B7 Vocabulary: words that always take a capital \u2014 ELL 1 days and months, ELL 2 places, languages and nationalities. Part B \u00B7 Grammar: ELL 1 chooses . ? or !; ELL 2 chooses the opener that fits (After, When, Outside, First, Soon, In). Show all ten, then reveal one at a time, alternating levels."],
   ["3", "Warm-up: write it", "ELL 1: one statement and one question about the weekend. ELL 2: three sentences about the morning, each starting a different way. Show the one example answer and take two or three aloud."],
   ["7", "Show me the mark", "Say a sentence; students show its end mark: fist = period, one hand up = question mark, two hands up = exclamation mark. Sentences: Where is the bathroom? \u00B7 I like pizza. \u00B7 Watch out! \u00B7 Do you have a brother? \u00B7 My name is Mr. Reid. \u00B7 Wow, that is amazing! \u00B7 What day is it today? \u00B7 The bus is late. Then partners play. English only."],
   ["2", "Title and goals", "Read the three goals. Name the big idea: a reader should never have to guess where a sentence starts or ends."],
   ["6", "Teaching 1: capitals and end marks", "Capitals at the start, on names, places and days, and on I; the three end marks. Ask for one more example of each from the room."],
   ["6", "Teaching 2: different openings", "Three flat sentences that all start The rice\u2026, then the same ideas with In the pan and Soon. The comma goes after an opening. Then the ELL 1 and ELL 2 examples."],
   ["6", "Match the word", "Eight words against meanings from a shuffled bank, revealed one at a time, then the key-vocabulary summary."],
   ["4", "Say it three ways", "Partners say one idea three ways, each with a different opening; the listener picks the best one. English only."],
   ["6", "Lina\u2019s kitchen", "Read My Kitchen (ELL 1) and The Sunday Kitchen (ELL 2) in full, then side by side. Students find a capital for each reason: start, name, place, day, I. Then reveal."],
   ["10", "Worksheet Parts A and B", "Hand out both sheets. Show the full pages, then walk Part A and Part B for each level with the worked example, revealing one answer at a time."],
   ["14", "Part C independent writing", "Walk Part C for each level and reveal the answers. ELL 1 rewrites each sentence with its capital and end mark; ELL 2 rewrites each sentence with a new opening and a comma. Circulate with help slips."],
   ["6", "Check and exit ticket", "Part D tick-box check, then the Part E exit ticket on the sheet, with one example answer per level. Next class, then agendas."] ],
  diff: "Support: the Teaching 1 slide can go back up during Part C, and ELL 1 may use the warm-up days and months list. Extension: ELL 2 early finishers write three sentences about their own place, each with a different opening.",
  assess: "Formative. Part C shows who controls capitals and end marks (ELL 1) and who can vary an opening with a comma (ELL 2). The exit ticket is the quick check. Not marked.",
  homework: "Finish Part C if it is not done.",
  watch: "Lower-case i, and places or days with no capital. Questions ending in a period. ELL 2: a missing comma after an opening, or an opening that changes the meaning." },
 shape: [["Warm-up: words and grammar", "quick practice"], ["Show me the mark", "warm-up game"], ["Capitals and end marks", "mini-lesson"],
   ["Different openings", "mini-lesson"], ["Match the word", "vocabulary game"], ["Say it three ways", "partner speaking"],
   ["Lina\u2019s kitchen", "reading"], ["Worksheet Parts A and B", "worksheet"], ["Part C: fix it and new openings", "independent writing"],
   ["Check and exit ticket", "quick write"]],
 sequence: [
  { type: "drill", part: "A", kind: "Vocabulary", lvls: [
    { lvl: "ELL 1", bankLabel: "Word bank \u2014 one word in each blank", bank: "Saturday \u00B7 January \u00B7 Wednesday \u00B7 Sunday \u00B7 December \u00B7 Tuesday \u00B7 Monday \u00B7 Friday \u00B7 September \u00B7 Thursday",
      items: [["The day after Monday is ____.", "Tuesday"], ["The day before Saturday is ____.", "Friday"], ["Lina cooks with her grandmother on ____.", "Sunday"],
        ["The first month of the year is ____.", "January"], ["School starts in ____.", "September"], ["The last month of the year is ____.", "December"],
        ["The day after Tuesday is ____.", "Wednesday"], ["The day before Friday is ____.", "Thursday"], ["The first school day of the week is ____.", "Monday"],
        ["The day after Friday is ____.", "Saturday"]] },
    { lvl: "ELL 2", bankLabel: "Word bank \u2014 one word in each blank", bank: "Vancouver \u00B7 Tagalog \u00B7 Manila \u00B7 Canadian \u00B7 English \u00B7 British Columbia \u00B7 Pacific \u00B7 Filipino \u00B7 Richmond \u00B7 Philippines",
      items: [["Lina is from the ____.", "Philippines"], ["People from Canada are ____.", "Canadian"], ["Richmond is in the province of ____.", "British Columbia"],
        ["Many people in the Philippines speak ____ and English.", "Tagalog"], ["Lina\u2019s family moved from Manila to ____.", "Richmond"],
        ["The ocean next to Vancouver is the ____ Ocean.", "Pacific"], ["In this class, we speak ____.", "English"],
        ["The big city next to Richmond is ____.", "Vancouver"], ["People from the Philippines are ____.", "Filipino"],
        ["Lina is from ____, the capital city of the Philippines.", "Manila"]] } ] },
  { type: "drill", part: "B", kind: "Grammar", lvls: [
    { lvl: "ELL 1", bankLabel: "Use . or ? or !", bank: "!   \u00B7   .   \u00B7   ?",
      items: [["I live in Richmond____", "."], ["Where is my spoon____", "?"], ["Watch out____", "!"], ["Do you like soup____", "?"],
        ["My brother is ten____", "."], ["Wow, this is hot____", "!"], ["What time is it____", "?"], ["We eat at seven____", "."],
        ["I love this song____", "!"], ["Is the rice ready____", "?"]] },
    { lvl: "ELL 2", bankLabel: "Choose the opener that fits", bank: "Soon \u00B7 In \u00B7 First \u00B7 After \u00B7 Outside \u00B7 When",
      items: [["____ school, I walk home.", "After"], ["____ the rice is ready, we eat.", "When"], ["____, the rain taps on the glass.", "Outside"],
        ["____, I wash my hands. Then I cook.", "First"], ["____ the kitchen, the radio plays.", "In"], ["It is almost six. ____, dinner will be ready.", "Soon"],
        ["____ I get home, I take off my shoes.", "When"], ["____ dinner, we wash the plates.", "After"], ["____ the corner, the rice cooker clicks.", "In"],
        ["____, I read the recipe. Then I start.", "First"]] } ] },
  { type: "rows", label: "Warm-up: write it", tag: "Warm-up \u00B7 write it", head: "Write it", icon: "icon-book.png", big: "In your exercise book.", rows: [
    ["ELL 1", "One statement and one question about your weekend."],
    ["ELL 2", "Three sentences about your morning. Start each one a different way."]] },
  { type: "rows", label: "Warm-up: example answer", tag: "Warm-up \u00B7 example answer", head: "One good answer", rows: [
    ["ELL 1", "I play soccer on Saturday. Do you like soccer?"],
    ["ELL 2", "At seven, my alarm rings. After breakfast, I catch the bus. Outside, the air is cold."]] },
  { type: "rows", label: "Show me the mark", tag: "Warm-up game", head: "Show me the mark: how to play", englishOnly: true, rows: [
    ["1", "I say a sentence."], ["2", "Show its end mark with your hands."],
    ["Fist", "a period ( . )"], ["One hand", "a question mark ( ? )"], ["Two hands", "an exclamation mark ( ! )"],
    ["3", "Then play with a partner."]] },
  { type: "speaking", label: "Show me the mark: with a partner", head: "Now with a partner", englishOnly: true, signAll: true,
    prompt: "Say a sentence. Your partner shows the mark and says it.",
    frames: ["It is a statement. It ends with a period.", "It is a question. It ends with a question mark.", "It is strong feeling. It ends with an exclamation mark."] },
  { type: "title", label: "Today\u2019s lesson" },
  { type: "goals", label: "Today\u2019s goals", items: [
    "Start every sentence with a capital letter.",
    "End every sentence with . or ? or !",
    "ELL 2: start your sentences in different ways."] },
  { type: "rows", label: "Capitals and end marks", tag: "Teaching 1 of 2", head: "Capitals and end marks", rows: [
    ["Start", "every sentence: The rice is hot."], ["Names", "people, places, days: Lina, Richmond, Sunday"], ["I", "always a capital: Lina and I cook."],
    ["Period", "a statement: The kitchen is warm."], ["Question", "a question mark: Is the rice ready?"], ["Feeling", "an exclamation mark: I love this room!"]] },
  { type: "rows", label: "Different openings", tag: "Teaching 2 of 2", head: "Different openings", rows: [
    ["All the same", "The rice is hot. The rice is sweet. The rice is ready."], ["Different", "The rice is hot. In the pan, it crackles. Soon, it is ready."],
    ["Openers", "when, after, in, outside, first, soon"], ["Comma", "Put a comma after the opening: After school, I walk home."],
    ["Why", "The same start sounds flat. Different starts keep the reader with you."]] },
  { type: "rows", label: "Examples", tag: "Examples", head: "Clean sentences", rows: [
    ["ELL 1", "The kitchen is warm."], ["ELL 1", "Is the rice ready?"], ["ELL 1", "I love this room!"],
    ["ELL 2", "Outside, the rain taps on the glass."], ["ELL 2", "When the plates are empty, the radio still plays."]] },
  { type: "match", label: "Match the word", head: "Match the word", bank: bankWords, words: vocab },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: vocab },
  { type: "speaking", label: "Say it three ways", head: "Say it three ways", englishOnly: true, signAll: true, icon: "icon-friends.png",
    prompt: "One idea, three openings. Your partner picks the best one.",
    frames: ["The ______ is ______.", "In the ______, the ______ is ______.", "When I ______, the ______ is ______.", "The best one is number ______."] },
  { type: "prose", text: "k1", label: "My Kitchen" },
  { type: "prose", text: "k2", label: "The Sunday Kitchen" },
  { type: "text2", a: "k1", b: "k2" },
  { type: "rows", label: "Find the capitals", tag: "Practice", head: "Find the capitals in Lina\u2019s kitchen", rows: [
    ["Start", "a capital at the start of a sentence"], ["Name", "a capital on a person\u2019s name"], ["Place", "a capital on a place"],
    ["Day", "a capital on a day"], ["I", "the word I"]] },
  { type: "rows", label: "Find the capitals: My Kitchen", tag: "Practice \u00B7 answers", head: "In My Kitchen", rows: [
    ["Start", "My name is Lina."], ["Name", "Lina"], ["Place", "Manila, Richmond"], ["Day", "Sunday"], ["I", "I am fifteen years old."]] },
  { type: "rows", label: "Find the capitals: The Sunday Kitchen", tag: "Practice \u00B7 answers", head: "In The Sunday Kitchen", rows: [
    ["Start", "If you want to know who I am, \u2026"], ["Name", "Lina"], ["Place", "Richmond, Manila"], ["Day", "Sunday"],
    ["I", "I taste everything before anyone else."]] },
  { type: "handout", label: "Hand out the worksheet", note: "ELL 1 and ELL 2 sheets. Name and date first.",
    items: [["A", "the capitals"], ["B", "end marks \u00B7 same or different?"], ["C", "fix it \u00B7 new openings"], ["D", "check your work"], ["E", "exit ticket", true]],
    foot: "The sheet stays in your duotang." },
  { type: "walk", part: "1A-A", withExample: true }, { type: "reveals", part: "1A-A" },
  { type: "walk", part: "2A-A", withExample: true }, { type: "reveals", part: "2A-A" },
  { type: "walk", part: "1A-B", withExample: true }, { type: "reveals", part: "1A-B" },
  { type: "walk", part: "2A-B", withExample: true }, { type: "reveals", part: "2A-B" },
  { type: "walk", part: "1A-C", withExample: true }, { type: "reveals", part: "1A-C" },
  { type: "walk", part: "2A-C", withExample: true }, { type: "reveals", part: "2A-C" },
  { type: "walk", part: "1A-D" }, { type: "walk", part: "2A-D" },
  { type: "pages", label: "The whole sheet again" },
  { type: "exit", part: "1A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "1A-E", good: true },
  { type: "exit", part: "2A-E", note: "Show me your exit ticket. The sheet stays in your duotang." }, { type: "reveals", part: "2A-E", good: true },
  { type: "nextshape", label: "Next class", head: "Next class: Planning My Place", items: [
    ["Warm-up: words and grammar", "quick practice"], ["Warm-up game", "game"], ["How Lina planned", "mini-lesson"],
    ["The three-part plan", "mini-lesson"], ["Tell me your place", "partner speaking"], ["Worksheet: fill your plan", "independent work"],
    ["Exit ticket", "quick write"]] },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", icon: "icon-calendar.png", rows: [
    ["Next class", "Planning My Place."], ["Homework", "Finish Part C if it is not done."], ["Remember", "Your worksheet goes in your duotang."]] } ],
 sheets: [
  { lvl: "ELL 1", suffix: "1A", label: "ELL 1", objective: "Use capital letters and end marks.",
    outcomes: "ELL 1  W5 Use capital letters, periods and question marks  \u2022  W1 Write simple sentences", vocab,
    remember: "Start with a capital. End with . or ? or ! Names, places, days and I always have a capital.", helpLine },
  { lvl: "ELL 2", suffix: "2A", label: "ELL 2", objective: "Write with correct capitals and different openings.",
    outcomes: "ELL 2  W7 Use capitalization and punctuation correctly  \u2022  W1 Write simple sentences", vocab,
    remember: "Vary your openings so the writing is not flat. Put a comma after an opening. Keep every capital and end mark correct.", helpLine } ],
 worksheet: { parts: [
  // ---------------- ELL 1 ----------------
  { key: "1A-A", lvl: "ELL 1", id: "A", title: "Find the capitals", kind: "cloze",
    instr: "Write every word that needs a capital letter.",
    example: { text: "my friend lina is here.", ans: "My, Lina", tail: "" },
    items: [{ text: "we live in richmond.", ans: "We, Richmond", tail: "" }, { text: "i like rice.", ans: "I", tail: "" },
      { text: "she is from manila.", ans: "She, Manila", tail: "" }, { text: "on monday we cook.", ans: "On, Monday", tail: "" },
      { text: "my brother and i eat.", ans: "My, I", tail: "" },
      { text: "lina and i go to school.", ans: "Lina, I", tail: "" }, { text: "is it tuesday today?", ans: "Is, Tuesday", tail: "" }],
    how: "Look for four things: the first word, names of people and places, days of the week, and the word I. Some lines need two capitals." },
  { key: "1A-B", lvl: "ELL 1", id: "B", title: "Add the end mark", kind: "cloze", newPage: true,
    instr: "Write . or ? or ! on the line. You can use a mark more than once.",
    bank: ["!", ".", "?"], bankCols: 3, crossed: [],
    example: { text: "The rice is hot", ans: ".", tail: "" },
    items: [{ text: "Is the window open", ans: "?", tail: "" }, { text: "I love this kitchen", ans: "!", tail: "" },
      { text: "She sings a song", ans: ".", tail: "" }, { text: "Where is the spoon", ans: "?", tail: "" }, { text: "Watch out", ans: "!", tail: "" }],
    how: "A question asks something: ? A strong feeling: ! Everything else is a statement: ." },
  { key: "1A-C", lvl: "ELL 1", id: "C", title: "Fix and write", kind: "lines", lines: 2,
    instr: "Add the capital and the end mark. Write the whole sentence again.",
    example: { text: "the rice smells sweet  \u2192", ans: "The rice smells sweet." },
    items: [{ text: "is the rice ready  \u2192", ans: "Is the rice ready?" }, { text: "i live in richmond  \u2192", ans: "I live in Richmond." },
      { text: "she is from manila  \u2192", ans: "She is from Manila." }, { text: "we cook on sunday  \u2192", ans: "We cook on Sunday." },
      { text: "wow, this soup is hot  \u2192", ans: "Wow, this soup is hot!" },
      { text: "where do you live  \u2192", ans: "Where do you live?" }, { text: "i love my grandmother\u2019s kitchen  \u2192", ans: "I love my grandmother\u2019s kitchen!" }],
    how: "Copy the sentence. Fix the first letter, any names, places, days and I. Then choose the end mark." },
  { key: "1A-D", lvl: "ELL 1", id: "D", title: "Check your work", kind: "check",
    instr: "Read your work again. Tick each box when it is true.",
    checks: ["I found the words that need capitals.", "I added the right end marks.", "Every sentence starts with a capital.",
      "Names, places and days have capitals.", "The word I is a capital.", "Every sentence has an end mark."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "1A-E", lvl: "ELL 1", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then show me before you leave.",
    items: [{ text: "Write one sentence about you. Use the name of a place.", reveal: "I live in Richmond." }],
    how: "One sentence: a capital at the start, a capital on the place, an end mark." },
  // ---------------- ELL 2 ----------------
  { key: "2A-A", lvl: "ELL 2", id: "A", title: "Fix the capitals", kind: "lines", lines: 2,
    instr: "Write each line again with the correct capital letters.",
    example: { text: "my friend lina is from manila.  \u2192", ans: "My friend Lina is from Manila." },
    items: [{ text: "on monday we go to richmond.  \u2192", ans: "On Monday we go to Richmond." },
      { text: "i think the rice is ready.  \u2192", ans: "I think the rice is ready." },
      { text: "her name is sofia, and she likes canada.  \u2192", ans: "Her name is Sofia, and she likes Canada." },
      { text: "we read a book about the philippines.  \u2192", ans: "We read a book about the Philippines." }],
    how: "Capitals go on the first word, names, places, countries, days and I. Check every word before you copy." },
  { key: "2A-B", lvl: "ELL 2", id: "B", title: "Same or different opening?", kind: "cloze",
    instr: "Read the two sentences. Write S if they start the same way, or D if they start differently.",
    example: { text: "The rice is hot. The rice is sweet.", ans: "S", tail: "" },
    items: [{ text: "The window is cold. Outside, the rain falls.", ans: "D", tail: "" }, { text: "She sings while she cooks. Soon, the food is ready.", ans: "D", tail: "" },
      { text: "The window is cold. The window is cloudy.", ans: "S", tail: "" }, { text: "The rice is hot. In the pan, it crackles.", ans: "D", tail: "" },
      { text: "She sings. She cooks.", ans: "S", tail: "" }],
    how: "Look only at the first word or two of each sentence. Same start: S. Different start: D." },
  { key: "2A-C", lvl: "ELL 2", id: "C", title: "New openings", kind: "lines", lines: 2,
    instr: "Rewrite each sentence so it starts differently: when, in, outside, first or after. Put a comma after the opening.",
    example: { text: "The rain taps on the glass.  \u2192", ans: "Outside, the rain taps on the glass." },
    items: [{ text: "I taste everything.  \u2192", ans: "First, I taste everything." },
      { text: "The plates are empty after dinner.  \u2192", ans: "After dinner, the plates are empty." },
      { text: "My grandmother hums a song in the kitchen.  \u2192", ans: "In the kitchen, my grandmother hums a song." },
      { text: "The kitchen smells like home when the rice is ready.  \u2192", ans: "When the rice is ready, the kitchen smells like home." }],
    how: "Find the part that says when or where. Move it to the front and put a comma after it. The meaning must stay the same." },
  { key: "2A-D", lvl: "ELL 2", id: "D", title: "Check your work", kind: "check",
    instr: "Read your work again. Tick each box when it is true.",
    checks: ["I fixed every capital in Part A.", "I marked S or D in Part B.", "My new sentences start in different ways.",
      "I put a comma after each opening.", "Proper nouns have capitals.", "Every sentence has an end mark."],
    how: "Tick a box only when it is true. Fix anything you cannot tick yet." },
  { key: "2A-E", lvl: "ELL 2", id: "E", title: "Exit ticket", kind: "exit", lines: 2,
    instr: "Answer, then show me before you leave.",
    items: [{ text: "Write one sentence about your morning. Start with an opening, and use a proper noun.", reveal: "Before school, I walk my dog in Minoru Park." }],
    how: "An opening, a comma, then the sentence. The name of the place gets a capital." } ] },
 texts: {
  k1: { lvl: "ELL 1", title: "My Kitchen",
    body: "My name is Lina. I am fifteen years old. I am from Manila, but now I live in Richmond. On Sunday, I am in the kitchen with my grandmother. The rice smells good, and the radio is loud. I am happy in my kitchen." },
  k2: { lvl: "ELL 2", title: "The Sunday Kitchen",
    body: "If you want to know who I am, come to my kitchen on a Sunday morning. My name is Lina, and I am fifteen years old. I moved to Richmond from Manila two years ago, but the kitchen still smells like home. Garlic rice crackles in the pan, and the rice cooker clicks and steams in the corner. My grandmother\u2019s radio plays old songs while she hums along, a little off-key. I stand beside her with a wooden spoon, and I taste everything before anyone else because I am the official taster. The window is cloudy with steam, and outside the rain taps on the glass. My little brother asks a hundred questions, and I answer every one. I want to be a nurse one day, so I like taking care of people, and this kitchen is where I learned how. When the plates are empty and the radio is still playing, I know exactly who I am." } }
};
