// ELL3 U1 L04 — Words That Carry Weight. ALL content here; the renderer holds the design.
// Unit order: L1 Where You Are From · L2 Cold Start: First Reading · L3 September Writing Sample · L4 this · L5 Simple and Compound
// Build: bash build.sh lessons/ELL3_U01_L04.js v2 v2
module.exports = {
 course: "ELL3",
 meta: { unit: 1, unitTitle: "The Exact Thing", lesson: 4, title: "Words That Carry Weight", subtitle: "Strong verbs and more than one sense", month: "September" },
 banner: { obj: "Choose verbs and nouns that do more work, and write from more than one sense.",
   std: "Evidence  W1 \u00B7 W2  \u2014  familiar and academic content language \u00B7 descriptive sentences", lit: ["COM", "TH"] },
 plan: {
  objective: "Students replace weak verb-plus-adverb and adjective-stacked phrasing with one precise word, and build description from at least two senses rather than sight alone.",
  outcomes: "W1 familiar and some academic content language \u00B7 W2 descriptive sentences.",
  materials: "Deck \u00B7 Lesson 4 worksheet, one per student plus spares \u00B7 exercise books \u00B7 pens \u00B7 the duotang holding the Lesson 1 paragraph",
  timing: "80 minutes",
  steps: [
   ["5", "Warm-up", "Three ways of walking that are not just walking, then which of the three tells you most about the person doing it. Take four or five aloud and write the strongest on the board. Do not explain the lesson yet \u2014 the list is the evidence for it."],
   ["2", "Goals", "Read the three goals. Name that today is about choosing words, not adding them."],
   ["12", "Vocabulary \u2014 match the word", "Ten words against their meanings from a shuffled bank, revealed one at a time. Then the summary slide, then a partner talk: each partner uses four of the words in a sentence about this room. Circulate for connotation and texture, which are the two they will avoid."],
   ["12", "Teaching", "Strong verbs beat adverbs, then use more than your eyes. Stop after each for one check question: \u201cgive me a better verb than walked quickly\u201d, and \u201cname a sense that is not sight\u201d."],
   ["5", "Examples", "Three weak-to-strong rewrites. Read the weak version aloud and ask students to judge it before you show the rewrite."],
   ["8", "Worksheet Part A", "Hand out the sheet. Walk the word bank task \u2014 eight words, six blanks, two extra, and the example already done with its word crossed out of the bank. Reveal one answer at a time."],
   ["10", "Worksheet Part B", "Walk the one-strong-word rewrites. The worked example shows the level required: one replacement word, not a longer sentence. Reveal answers as complete sentences."],
   ["6", "Speaking", "In pairs, describe this room using only sound. No visual words at all. Then swap and do it with smell or touch. Both partners speak. English only for this one."],
   ["12", "Part C \u2014 independent writing", "Four sentences about a meal you remember: at least two different senses, and none of the words good, nice or very. Then underline the one word doing the most work and be ready to defend it. The exercise book entry comes from something heard, smelled or touched \u2014 never seen."],
   ["5", "Part D \u2014 thinking it through", "The two questions on why a strong verb beats verb-plus-adverb, and which sense writers overuse. Answers revealed as complete sentences."],
   ["3", "Exit ticket", "Part E is the tick-box check. Exit ticket on the slide: hardest sense and why, and one weak word from today with its stronger replacement."] ],
  diff: "Advanced tier as written. For Foundation and Bridge, reduce the Part A bank to six words with no extras and accept three Part B rewrites rather than five. Students who arrive mid-unit begin the exercise book entries at this lesson; do not backfill.",
  assess: "Formative. Part B is the piece to look at \u2014 it shows whether they can find one word or only add words. Not marked.",
  homework: "Finish the four meal sentences.",
  watch: "Four visual sentences with one smell word bolted onto the last one. Ask which sense the sentence is actually built from, not which words appear in it. The adjective swap is the commonest failure and needs naming aloud the first time it appears." },
 shape: [["Three ways of walking", "warm-up talk"], ["Today\u2019s goals", "reading together"], ["Match the word", "vocabulary game"],
   ["Partner talk with the words", "speaking"], ["Strong verbs, and more than your eyes", "instruction"], ["Weak to strong", "examples"],
   ["Part A \u2014 vocabulary", "worksheet"], ["Part B \u2014 one strong word", "worksheet"], ["Only sounds", "partner speaking"],
   ["Part C \u2014 a meal you remember", "independent writing"], ["Part D \u2014 thinking it through", "written answers"], ["Exit ticket", "quick write"]],
 sequence: [
  { type: "warmup", label: "Warm-up", head: "Warm-up \u2014 three ways of walking",
    prompts: ["\u201cWalked\u201d is a fine word. Name three ways of walking that are not just walking.",
      "Which one of your three tells you most about the person doing it?"] },
  { type: "title", label: "Today\u2019s lesson" },
  { type: "goals", label: "Today\u2019s goals", items: [
    "Choose verbs and nouns that do more work.",
    "Use sensory detail from more than one sense.",
    "Avoid stacking adjectives to fix a weak noun."] },
  { type: "match", label: "Match the word", head: "Match the word to its meaning",
    bank: ["texture", "adverb", "hum", "noun", "connotation", "glare", "verb", "aroma", "adjective", "synonym"],
    words: [
     ["verb", "a word for an action or a state"],
     ["noun", "a word for a person, place, thing, or idea"],
     ["adjective", "a word that describes a noun"],
     ["adverb", "a word that describes a verb"],
     ["synonym", "a word with a similar meaning to another"],
     ["connotation", "the feeling a word carries beyond its meaning"],
     ["texture", "how a surface feels"],
     ["aroma", "a smell, usually a pleasant one"],
     ["glare", "harsh bright light, or a hard look"],
     ["hum", "a low continuous sound"]] },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: [
    ["verb", "a word for an action or a state"],
    ["noun", "a word for a person, place, thing, or idea"],
    ["adjective", "a word that describes a noun"],
    ["adverb", "a word that describes a verb"],
    ["synonym", "a word with a similar meaning to another"],
    ["connotation", "the feeling a word carries beyond its meaning"],
    ["texture", "how a surface feels"],
    ["aroma", "a smell, usually a pleasant one"],
    ["glare", "harsh bright light, or a hard look"],
    ["hum", "a low continuous sound"]] },
  { type: "speaking", label: "Partner talk", head: "Use four of the words", englishOnly: true,
    icon: "icon-friends.png", big: "Both partners speak.",
    prompt: "With your partner, use four of today\u2019s words in sentences about this room.",
    frames: ["The ______ of this room is ______.",
      "A ______ has a ______ connotation.",
      "I can hear a ______ coming from ______.",
      "Another word for ______ is ______."] },
  { type: "cards", label: "Strong verbs", tag: "Teaching 1 of 2", head: "Strong verbs beat adverbs", icon: "icon-pen.png", big: "One word, not two.", cards: [
    { title: "Two words, one job", body: "\u201cHe walked quickly\u201d uses two words to do one job." },
    { title: "One word, more meaning", body: "\u201cHe hurried\u201d does it in one. \u201cHe darted\u201d tells you more again." },
    { title: "Check the verb first", body: "When you reach for an adverb, first check whether a better verb exists.", tone: "teal" },
    { title: "Nouns too", body: "Same for nouns: \u201ca big old building\u201d is often just \u201ca warehouse\u201d.", tone: "teal" }] },
  { type: "cards", label: "More than your eyes", tag: "Teaching 2 of 2", head: "Use more than your eyes", icon: "icon-read.png", big: "Two senses beat five.", cards: [
    { title: "Readers skim sight", body: "Most writers describe only what they saw. Readers are used to that and skim it." },
    { title: "Sound, smell, touch", body: "These three are underused, so they land harder when you use them." },
    { title: "Smell carries memory", body: "Smell is the sense most tied to the past.", tone: "teal" },
    { title: "You do not need five", body: "Two well-chosen senses beat five listed ones.", tone: "teal" }] },
  { type: "rows", label: "Weak to strong", tag: "Examples", head: "Weak \u2192 strong", pair: 2, rows: [
    ["Weak", "The kitchen was very hot and smelled nice."],
    ["Strong", "The kitchen held the smell of frying garlic and the back of my neck was damp."],
    ["Weak", "He spoke in a loud angry voice."],
    ["Strong", "He barked my name across the shop."],
    ["Weak", "It was a nice quiet morning."],
    ["Strong", "Nothing moved except a bus two streets away."]] },
  { type: "handout", label: "Hand out the worksheet", note: "A and B together. C on your own.",
    foot: "Part E is the check at the end. Keep the sheet in your duotang." },
  { type: "walk", part: "A" },
  { type: "reveals", part: "A" },
  { type: "walk", part: "B" },
  { type: "reveals", part: "B" },
  { type: "speaking", label: "Only sounds", head: "Describe this room \u2014 sounds only", englishOnly: true,
    icon: "icon-friends.png", big: "No visual words.",
    prompt: "In pairs, describe this classroom using only sounds. Then swap and do it with smell or touch.",
    frames: ["Without looking, I can hear ______.",
      "This room smells like ______.",
      "The desk feels ______ under my hand."] },
  { type: "walk", part: "C" },
  { type: "reveals", part: "C" },
  { type: "walk", part: "D" },
  { type: "reveals", part: "D" },
  { type: "walk", part: "E" },
  { type: "exit", label: "Exit ticket", part: "F", note: "Hand me your exit ticket. The worksheet stays in your duotang." },
  { type: "next", label: "Next class", title: "Simple and Compound", sub: "Joining sentences with and, but, so and for \u2014 and the comma that goes with them.", icon: "icon-pen.png" },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", rows: [
    ["Homework", "Finish the four meal sentences."],
    ["Next class", "Simple and Compound."],
    ["Bring", "Your exercise book."]] } ],
 worksheet: {
  objective: "Choose verbs and nouns that do more work, and write from more than one sense.",
  outcomes: "W1 familiar and some academic content language  \u2022  W2 descriptive sentences",
  parts: [
   { id: "A", title: "Vocabulary", kind: "cloze", weight: 6,
     instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra. Cross out each word as you use it.",
     bank: ["verb", "noun", "adjective", "adverb", "connotation", "texture", "aroma", "hum"],
     crossed: ["noun"],
     example: { text: "A word for a person, place, thing, or idea is a", ans: "noun", tail: "" },
     items: [
      { text: "How a surface feels is its", ans: "texture", tail: "" },
      { text: "A word that describes a verb is an", ans: "adverb", tail: "" },
      { text: "A low continuous sound is a", ans: "hum", tail: "" },
      { text: "A word for an action or a state is a", ans: "verb", tail: "" },
      { text: "The feeling a word carries beyond its meaning is its", ans: "connotation", tail: "" },
      { text: "A word that describes a noun is an", ans: "adjective", tail: "" }],
     how: "Read the whole sentence first, then choose the word that fits. Cross each word out of the bank as you use it. Two words are left over at the end." },
   { id: "B", title: "One strong word", kind: "lines", weight: 6, lines: 2,
     instr: "Rewrite each sentence, replacing the weak phrase with one stronger word.",
     example: { text: "The dog went quickly across the yard.", ans: "The dog darted across the yard." },
     items: [
      { text: "She said loudly that we were late.", ans: "She shouted that we were late." },
      { text: "The old broken-down car made a strange noise.", ans: "The wreck rattled." },
      { text: "The soup tasted very good.", ans: "The soup tasted rich." },
      { text: "He walked slowly and sadly out of the room.", ans: "He trudged out of the room." },
      { text: "The street was very busy and there were a lot of people.", ans: "The street swarmed." }],
     how: "One word does the work. Do not make the sentence longer \u2014 make it sharper. If you have written \u201cvery\u201d or an \u201c-ly\u201d word, you have not finished." },
   { id: "C", title: "Without your eyes", kind: "lines", weight: 8, lines: 5,
     instr: "Write four sentences about a meal you remember. At least two different senses must appear, and you may not use the words good, nice, or very.",
     example: { text: "One sentence about a meal, built from smell.", ans: "The kitchen filled with the aroma of burnt garlic before anyone sat down." },
     items: [
      { text: "Sentence 1 \u2014 start with what you could hear, smell, or touch.", reveal: "The oil hissed in the pan before I reached the door." },
      { text: "Sentence 2 \u2014 add a second sense.", reveal: "The bowl was hot enough that I passed it from hand to hand." },
      { text: "Sentence 3 \u2014 one strong verb, no adverb.", reveal: "My grandmother ladled the broth without looking at it." },
      { text: "Sentence 4 \u2014 finish the moment.", reveal: "Nobody spoke until the steam had gone." },
      { text: "Underline the one word doing the most work, and be ready to say why.", reveal: "Ladled \u2014 it shows the care and the practice in one word." }],
     how: "Two senses at least, and none of them sight only. No good, nice, or very. Then underline the single word you think is doing the most work." },
   { id: "D", title: "Thinking it through", kind: "lines", weight: 4, lines: 5,
     instr: "Answer in complete sentences.",
     example: { text: "Why is \u201cthe wreck rattled\u201d stronger than \u201cthe old broken-down car made a strange noise\u201d?", ans: "It is stronger because one noun and one verb carry the whole picture, so the reader is not slowed down by extra words." },
     items: [
      { text: "Why does a strong verb usually beat a verb plus an adverb?", ans: "A strong verb usually beats a verb plus an adverb because it carries the same meaning in one word, and it often tells the reader more than the adverb did." },
      { text: "Which sense do most writers overuse, and why does using another one work better?", ans: "Most writers overuse sight, and using another sense works better because readers are not expecting it, so the detail lands harder." }],
     how: "Full sentences, not notes. Use part of the question in your answer so the sentence stands on its own." },
   { id: "E", title: "Check", kind: "check",
     instr: "Read your work back. Tick each box when it is true.",
     checks: ["I used a stronger word instead of adding an adverb.",
       "I did not stack adjectives to fix a weak noun.",
       "My meal sentences use at least two senses.",
       "I did not use good, nice, or very.",
       "I underlined the word doing the most work.",
       "My Part D answers are complete sentences."],
     how: "Go back through the sheet and tick a box only when it is true. Fix anything you cannot tick." },
   { id: "F", title: "Exit ticket", kind: "exit", lines: 2,
     instr: "Answer, then hand this part to me.",
     items: [
      { text: "Which sense was hardest to write with, and why do you think that is?" },
      { text: "Write down one weak word you used today and its stronger replacement." }],
     how: "Two short answers. Hand me this part only \u2014 the rest of the sheet stays in your duotang." } ] },
 texts: {}
};
