// ELL3 U1 L06 — The Long Way Home (second, close reading). ALL content here; the renderer holds the design.
// Unit order: L1 Where You Are From · L2 Cold Start: First Reading · L3 General and Specific · L4 Words That Carry Weight
//             · L5 Simple and Compound · L6 this · L7 What the Story Means
// Students first met the story cold in L2. This lesson is the close reread: character and setting from evidence.
// Exercise books were collected before this lesson (checkpoint two) and are handed back at the start of it.
// Build: bash build.sh lessons/ELL3_U01_L06.js v2 v3
module.exports = {
 course: "ELL3",
 meta: { unit: 1, unitTitle: "The Exact Thing", lesson: 6, title: "The Long Way Home", subtitle: "Reading a character and a place from evidence", month: "September" },
 banner: { obj: "Read a story closely and use its evidence in your writing.",
   std: "Evidence  W2 · W14  —  descriptive sentences · complete sentences", lit: ["COM", "TH"] },
 plan: {
  objective: "Students reread “The Long Way Home” closely, read character and setting from what the text shows, and support a paragraph with line references and one exact quotation.",
  outcomes: "W2 descriptive sentences · W14 complete sentences. Reading and speaking are not scored.",
  materials: "Deck · Lesson 6 worksheet, one per student plus spares · the marked exercise books from checkpoint two, to hand back · the line-numbered story document for anyone who wants it on paper · pens",
  timing: "80 minutes",
  steps: [
   ["8", "Exercise books back — the four levels", "Hand back the exercise books first — the warm-up is written in them. Go over NYM, MM, M and FM on the slide. A level describes the writing, not the person, and Meeting is the target. Students read your comments and find one entry they would now change. Take marks questions after class, not in front of everyone."],
   ["5", "Warm-up", "Two questions in the exercise book. The first is personal (a longer route taken on purpose). The second sends them back to Arman from the Lesson 2 reading: why does he ride past his stop? Take three answers to the second and write them on the board without judging them — the lesson tests them."],
   ["2", "Goals", "Read the three goals. Name that today is a second, closer reading: they know what happens, so now they look at how the writer shows it."],
   ["8", "Vocabulary — match the word", "Ten words against their meanings from a shuffled bank, revealed one at a time, then the summary slide. Partner talk: each pair uses four of the words in sentences about Arman. Circulate for motive and reluctant, which carry the lesson."],
   ["6", "Teaching", "Character is shown, not announced; setting is not just scenery. Stop after each for one check question: “what does Arman do when nobody is watching?” and “what does the bus let him do?”"],
   ["8", "Reread the story", "Read the whole story aloud from the slides with line numbers showing, students following. This is a second reading, so do not stop to explain. Word list after, for anyone who still needs it."],
   ["2", "Examples", "Two pieces of evidence and one weak-to-strong answer. Ask why “Arman is sad” is weak before showing the strong version."],
   ["10", "Worksheet Parts A and B", "Hand out the sheet. Part A: story sentences with a word-bank gap, the example done and its word crossed out, two words left over. Part B: SHOWN or TOLD. Reveal one answer at a time after each Part."],
   ["7", "Part C — setting as pressure", "Walk the classroom example first: what a place allows, what it stops. Then the bus, the bakery and the house on their own. Reveal as complete sentences with line references."],
   ["7", "Parts D and E — evidence, then between the lines", "Part D: three questions answered from what is on the page, each with a line reference. Part E: two questions where nothing is said straight out. Do each example together. Reveal as complete sentences. Part E question 2, about the mother, feeds the argument that follows."],
   ["5", "Speaking — argue it in threes", "In threes, argue about Part E question 2. One person must disagree with the other two and defend it from the text. English only."],
   ["10", "Part F — your paragraph", "Six to eight sentences: what does the long way home give Arman that the short way does not? Two pieces of evidence, one exact quotation, no retelling. Model paragraph shown after they have started, not before. Then Part G, the tick-box check."],
   ["2", "Exit ticket", "Part H, the last Part on the sheet. Worksheet into the duotang."] ],
  diff: "Foundation and Bridge: Part A without the two extra words, Part D questions 1 and 3 and Part E question 1 only, and a Part F paragraph of four to five sentences with one piece of evidence. Extension: add a sentence on what the short way would cost him. Absent for Lesson 2: read the story on paper during the warm-up.",
  assess: "Formative. Part F is the piece to look at: does the paragraph make a claim and support it, or does it retell? Parts D and E show whether students can give a line reference. Not marked. The exercise-book entry from the story counts toward the unit’s exercise-book mark.",
  homework: "Finish the Part F paragraph if not completed. Exercise-book entry from the story: one specific detail the writer chose, and what it tells you that a general statement would not.",
  watch: "Students reading the mother as neglectful. Push back from the text: she asks twice, and the second time she is looking at him. Watch for students quietly recognising their own household; do not draw attention to them. Anyone who reads their level as a verdict: say privately that September is a starting line." },
 shape: [["Exercise books back", "the four levels"], ["Why does Arman ride past his stop?", "warm-up, in your exercise book"], ["Today’s goals", "reading together"],
   ["Match the word", "vocabulary game"], ["Partner talk with the words", "speaking"], ["Showing character, setting as pressure", "instruction"],
   ["The Long Way Home", "second reading"], ["Strong and weak evidence", "examples"], ["Parts A and B", "worksheet"],
   ["Part C — setting as pressure", "worksheet"], ["Parts D and E — evidence", "written answers"], ["Argue it in threes", "group speaking"],
   ["Part F — your paragraph", "independent writing"], ["Exit ticket", "quick write"]],
 sequence: [
  { type: "title", label: "Today’s lesson" },
  { type: "section", label: "Exercise books back", title: "Your exercise books are back", sub: "Before we start", icon: "icon-book.png" },
  { type: "cards", label: "The four levels", tag: "How your work is marked", head: "The four levels", icon: "icon-book.png", big: "Meeting is the target.", cards: [
    { title: "NYM — Not Yet Meeting", body: "The skill is not in your writing yet, or only with a lot of help." },
    { title: "MM — Minimally Meeting", body: "The skill shows up sometimes. Some mistakes change the meaning." },
    { title: "M — Meeting", body: "You use the skill all through the piece. Small mistakes do not change the meaning.", tone: "teal" },
    { title: "FM — Fully Meeting", body: "You use the skill correctly on your own, and you can explain it.", tone: "teal" }] },
  { type: "rows", label: "Read my comments", tag: "How your work is marked", head: "Now, with your exercise book", icon: "icon-pen.png", big: "About the writing, not you.", rows: [
    ["Read", "Read my comments beside your entries."],
    ["Find", "Find one entry you would now change."],
    ["Ask", "Questions about your level? Ask me after class."]] },
  { type: "warmup", label: "Warm-up", head: "Warm-up — in your exercise book",
    prompts: ["Have you ever taken a longer route somewhere on purpose? Why?",
      "Think back to “The Long Way Home”. Why do you think Arman rides past his stop?"] },
  { type: "goals", label: "Today’s goals", items: [
    "Read a short story closely, a second time.",
    "Identify character and setting with evidence.",
    "Track how a place reveals a person."] },
  { type: "match", label: "Match the word", head: "Match the word to its meaning",
    bank: ["reluctant", "setting", "belong", "motive", "threshold", "trait", "routine", "atmosphere", "protagonist", "detour"],
    words: [
     ["protagonist", "the main character"],
     ["trait", "a quality in a person"],
     ["motive", "the reason someone does something"],
     ["setting", "where and when a story happens"],
     ["atmosphere", "the feeling a place gives"],
     ["routine", "something done the same way every day"],
     ["detour", "a longer way instead of the direct one"],
     ["reluctant", "unwilling; slow to act"],
     ["threshold", "a doorway; where outside meets inside"],
     ["belong", "to fit in and be accepted"]] },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: [
     ["protagonist", "the main character"],
     ["trait", "a quality in a person"],
     ["motive", "the reason someone does something"],
     ["setting", "where and when a story happens"],
     ["atmosphere", "the feeling a place gives"],
     ["routine", "something done the same way every day"],
     ["detour", "a longer way instead of the direct one"],
     ["reluctant", "unwilling; slow to act"],
     ["threshold", "a doorway; where outside meets inside"],
     ["belong", "to fit in and be accepted"]] },
  { type: "speaking", label: "Partner talk", head: "Use four of the words", englishOnly: true,
    icon: "icon-friends.png", big: "Both partners speak.",
    prompt: "With your partner, use four of today’s words in sentences about Arman.",
    frames: ["Arman’s routine is ______.",
      "The atmosphere of the bakery is ______.",
      "Arman is reluctant to ______ because ______.",
      "I think Arman’s motive is ______."] },
  { type: "cards", label: "Showing character", tag: "Teaching 1 of 2", head: "Character is shown, not announced", icon: "icon-read.png", big: "Look at what he does.", cards: [
    { title: "Shown, not said", body: "The story never says “Arman was homesick”. It shows him doing something." },
    { title: "When nobody is watching", body: "What a character chooses when nobody is watching is the real evidence." },
    { title: "Every day", body: "Repeated actions matter more than single ones. Notice what happens every day.", tone: "teal" },
    { title: "What he avoids", body: "What a character avoids tells you as much as what he does.", tone: "teal" }] },
  { type: "cards", label: "Setting as pressure", tag: "Teaching 2 of 2", head: "Setting is not just scenery", icon: "icon-hand.png", big: "Allows. Stops.", cards: [
    { title: "Where, when — and pressure", body: "Setting is where and when. In a good story it also pushes on the character." },
    { title: "Two questions", body: "What does the place allow him to do? What does it stop him doing?" },
    { title: "Different limits", body: "A bus, a shop, a stairwell: each one puts different limits on a person.", tone: "teal" },
    { title: "Watch the change", body: "When the setting changes, watch whether the character changes with it.", tone: "teal" }] },
  { type: "text", text: "story", label: "The story", continues: "The story continues", budget: 330 },
  { type: "wordlist", text: "story", label: "Words in this story", note: "You have read this story once already. Use the list only for a word that still stops you." },
  { type: "rows", label: "Examples", tag: "Examples", head: "Strong and weak evidence", pair: 2, rows: [
    ["Character", "Arman counts the stops in Farsi. Nobody asked him to. Nobody hears him."],
    ["Setting", "The bakery is warm and nobody expects him there, so he can stay."],
    ["Weak", "Arman is sad."],
    ["Strong", "Arman avoids his own front door: he rides past his stop every day."]] },
  { type: "handout", label: "Hand out the worksheet", note: "A and B together. Then C, D and your paragraph.",
    foot: "The exit ticket is the last Part. The whole sheet goes in your duotang at the end." },
  { type: "walk", part: "A" },
  { type: "reveals", part: "A" },
  { type: "walk", part: "B" },
  { type: "reveals", part: "B" },
  { type: "walk", part: "C" },
  { type: "reveals", part: "C" },
  { type: "walk", part: "D" },
  { type: "reveals", part: "D" },
  { type: "walk", part: "E" },
  { type: "reveals", part: "E" },
  { type: "speaking", label: "Argue it in threes", head: "Argue it in threes", englishOnly: true,
    icon: "icon-friends.png", big: "One of you must disagree.",
    prompt: "Argue about Part E, question 2. One person disagrees with the other two and defends it from the text.",
    frames: ["I think his mother understands ______ because line ___ says ______.",
      "I disagree, because on line ___ ______.",
      "We agree on ______ but not on ______."] },
  { type: "walk", part: "F", note: "Sixteen lines on your sheet. Aim for six to eight sentences: claim, evidence, explain, evidence, explain, close." },
  { type: "rows", label: "Part F — one good answer", tag: "Part F · one good answer", head: "One good paragraph", rows: [
    ["Claim", "The long way home gives Arman an hour where he is not behind."],
    ["Evidence", "In class the question moves on before he finds the English word (line 5)."],
    ["Explain", "On the bus and at the bakery nothing is asked of him, so he cannot fall behind."],
    ["Evidence", "At home everybody is “doing something difficult and quiet” (line 14)."],
    ["Explain", "So there is no room for him there either."],
    ["Close", "The long way gives him an hour between two hard places."]] },
  { type: "walk", part: "G", note: "Six boxes on your sheet. Tick one only when it is true. Fix anything you cannot tick." },
  { type: "exit", label: "Exit ticket", part: "H", note: "Hand me your exit ticket. The worksheet stays in your duotang." },
  { type: "next", label: "Next class", title: "What the Story Means", sub: "Topic, plot and theme — and saying a theme as a full sentence.", icon: "icon-read.png" },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", rows: [
    ["Homework", "Finish your Part F paragraph."],
    ["Exercise book", "One detail from the story, and what it tells you."],
    ["Bring", "Your exercise book, every class."]] } ],
 worksheet: {
  objective: "Read a story closely and use its evidence in your writing.",
  outcomes: "W2 longer, more descriptive sentences  •  W14 complete sentences",
  parts: [
   { id: "A", title: "Vocabulary", kind: "cloze", weight: 6, bankCols: 5,
     instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra. Cross out each word as you use it.",
     bank: ["atmosphere", "threshold", "motive", "protagonist", "belong", "routine", "trait", "detour", "setting", "reluctant"],
     crossed: ["protagonist"],
     example: { text: "Arman is the main character, the", ans: "protagonist", tail: "" },
     items: [
      { text: "Riding past his stop is now Arman’s", ans: "routine", tail: "" },
      { text: "The bakery on Ackroyd is one", ans: "setting", tail: "" },
      { text: "Arman skips his stop and takes a", ans: "detour", tail: "" },
      { text: "Arman does not want to go home. He is", ans: "reluctant", tail: "" },
      { text: "The warm bakery has a calm, safe", ans: "atmosphere", tail: "" },
      { text: "We must work out Arman’s", ans: "motive", tail: "" },
      { text: "At Faraj’s table, Arman feels he can", ans: "belong", tail: "" }],
     how: "Read the whole sentence first, then choose the word that fits. Cross each word out of the bank as you use it. Two words are left over at the end." },
   { id: "B", title: "Shown or told?", kind: "cloze", weight: 6, bankCols: 2, newPage: true,
     instr: "Write SHOWN if the writer gives evidence, or TOLD if the writer simply announces it.",
     bank: ["SHOWN", "TOLD"], crossed: [],
     example: { text: "Arman sits at the table and buys nothing.", ans: "SHOWN", tail: "" },
     items: [
      { text: "Arman was very lonely at his new school.", ans: "TOLD", tail: "" },
      { text: "Arman counts the stops under his breath. Nobody hears him.", ans: "SHOWN", tail: "" },
      { text: "Faraj was a kind man.", ans: "TOLD", tail: "" },
      { text: "Faraj put a cake down and waved his hand at the coins.", ans: "SHOWN", tail: "" },
      { text: "Everyone in the house was busy and unhappy.", ans: "TOLD", tail: "" },
      { text: "His father is asleep at four in the afternoon.", ans: "SHOWN", tail: "" }],
     how: "Ask one question: does the sentence name a feeling or a quality, or does it show an action you can picture? A named feeling is TOLD. An action is SHOWN." },
   { id: "C", title: "Setting as pressure", kind: "lines", weight: 6, lines: 5,
     instr: "For each place, write what it allows Arman to do and what it stops him doing. Give a line number for each.",
     example: { text: "The classroom.", ans: "The classroom lets Arman learn English. It stops him keeping up, because the question moves on before he finds the word (line 5)." },
     items: [
      { text: "The bus.", ans: "The bus lets Arman count in Farsi with nobody hearing (line 4). It stops him arriving home (line 3)." },
      { text: "The bakery.", ans: "The bakery lets Arman sit somewhere warm where nothing is expected (lines 8–9). It keeps him from home until dark (line 10)." },
      { text: "The house.", ans: "The house gives Arman nothing of his own, because everyone is “doing something difficult and quiet” (line 14). It stops him having a place to be." }],
     how: "Two sentences for each place: what it allows, then what it stops. Put the line number in brackets after each piece of evidence, like the example." },
   { id: "D", title: "Evidence practice", kind: "lines", weight: 6, lines: 5,
     instr: "Answer in complete sentences. Give a line number for each answer.",
     example: { text: "What does Arman do when the bakery is closed?", ans: "When the bakery is closed, Arman walks down to the river and sits on the wall instead of going home (lines 17\u201318)." },
     items: [
      { text: "Name one thing Arman does every day. What does the repetition suggest?", ans: "Every day Arman stays on the bus past his own stop (line 3). The repetition suggests that staying away from home is a need, not a one-time choice." },
      { text: "Where and when does the story take place? Give two details.", ans: "The story takes place in a city in October, when the washing on the balcony never dries (line 2). The bakery is on Ackroyd (line 6)." },
      { text: "What does Arman do at the bakery that he does not do at home?", ans: "At the bakery Arman does his homework for an hour (line 9). At home he does not even say where he has been, and answers only \u201cSchool\u201d (line 12)." }],
     how: "Answer the question in your first sentence, then give the evidence with its line number. Use part of the question in your answer so the sentence stands on its own." },
   { id: "E", title: "Reading between the lines", kind: "lines", weight: 4, lines: 5,
     instr: "Answer in complete sentences. Give a line number for each answer.",
     example: { text: "Why does Faraj stop taking Arman\u2019s money?", ans: "Faraj stops taking Arman\u2019s money because he can see that Arman needs the table more than the cake (line 8)." },
     items: [
      { text: "Find the moment the story first hints that something is wrong. Quote it.", ans: "The story first hints that something is wrong in line 3: \u201cHe stays in his seat.\u201d Arman knows it is his stop, but he does not get off." },
      { text: "His mother asks, \u201cIs it warm there?\u201d What does her question show she understands about Arman?", ans: "Her question shows she understands that Arman needed somewhere warm, which the house has not been. She says \u201cGood\u201d (line 24)." }],
     how: "Nothing here is said straight out. Answer first, then show the line that made you think it. Your answer can differ from a partner\u2019s if the text supports it." },
   { id: "F", title: "Your paragraph", kind: "open", weight: 10, lines: 16,
     instr: "Write one paragraph, six to eight sentences: what does the long way home give Arman that the short way does not? Use at least two pieces of evidence and quote at least one of them exactly. Do not retell the story — your reader has read it.",
     example: { ans: "A strong first sentence answers the question: The long way home gives Arman an hour where he is not behind." },
     how: "First sentence answers the question. Then two pieces of evidence, each with a line number, and one of them quoted exactly. Say what each one shows. No retelling. Write your own first sentence — do not copy the example." },
   { id: "G", title: "Check your work", kind: "check",
     instr: "Read your work back. Tick each box when it is true.",
     checks: ["I gave a line number with my evidence.",
       "I wrote what each place allows and what it stops.",
       "My Part D and E answers are complete sentences.",
       "My paragraph answers the question in the first sentence.",
       "I quoted at least one line exactly.",
       "My paragraph does not retell the story."],
     how: "Go back through the sheet and tick a box only when it is true. Fix anything you cannot tick." },
   { id: "H", title: "Exit ticket", kind: "exit", lines: 2,
     instr: "Answer, then hand this part to me.",
     items: [
      { text: "Which detail in the story stayed with you after this second reading?" },
      { text: "Name one place in the story and one thing it stops Arman doing." }],
     how: "Two short answers. Hand me this part only — the rest of the sheet stays in your duotang." } ] },
 texts: { story: { ...require("./ELL3_U01_L02.js").texts.story, words: [
  ["pharmacy", "a shop that sells medicine"], ["balcony", "a platform outside an upper window"], ["stop", "where a bus picks people up"],
  ["pistachio", "a small green nut"], ["packs", "puts things into a bag"], ["applications", "forms to ask for a place"],
  ["sign", "a notice with writing on it"], ["wall", "here, a low wall to sit on"], ["heavy", "here, wet and hanging down"], ["quiet", "here, saying nothing"]] } }
};
