// ELL3 U1 L08 — Because, While, When. ALL content here; the renderer holds the design.
// Unit order: L5 Simple and Compound · L6 The Long Way Home · L7 What the Story Means · L8 this · L9 Finding Your Details
// The turn from L5: there they joined equals with and/but/so. Here one clause takes charge of the other.
// Students rewrite the L7 theme paragraph — they must bring it. Not a new paragraph, the same argument in better sentences.
// Build: bash build.sh lessons/ELL3_U01_L08.js v1 v2
module.exports = {
 course: "ELL3",
 meta: { unit: 1, unitTitle: "The Exact Thing", lesson: 8, title: "Because, While, When", subtitle: "Complex sentences, and the joining word that carries your meaning", month: "September" },
 banner: { obj: "Build complex sentences and choose the joining word that carries your meaning.",
   std: "Sentence control  W5 · W12 · W11  —  complex sentences · punctuation · agreement", lit: ["COM", "TH"] },
 plan: {
  objective: "Students build complex sentences with because, while, when, although and since, punctuate the dependent clause correctly, and choose the joining word that carries their meaning.",
  outcomes: "W5 complex sentences · W12 punctuation · W11 subject/verb agreement",
  materials: "Deck · Lesson 8 worksheet, one per student plus spares · exercise books · the Lesson 7 theme paragraphs, which students rewrite today · spare copies of the Lesson 7 sheet for anyone without one · pens",
  timing: "80 minutes",
  steps: [
   ["6", "Warm-up", "Two questions in the exercise book. The first joins “I stayed inside. It was raining.” so that one half explains the other. The second asks how many joining words would work, and whether they mean the same thing. Take two answers to the second and write both on the board without judging them — the difference between them is the whole lesson."],
   ["2", "Goals", "Read the three goals. Name the turn from Lesson 5: they can already join equals with and, but and so. Today one half takes charge of the other."],
   ["8", "Vocabulary — match the word", "Ten words against their meanings from a shuffled bank, revealed one at a time, then the summary slide. These are the words they need in order to talk about their own sentences. Watch dependent and subordinate — students often take them for two different things rather than two names for one clause."],
   ["6", "Teaching 1 — two clauses, one in charge", "Compound joins equals; complex makes one half serve the other. Say “Because the bus was late” aloud and let the silence sit — it is not a sentence. Then the comma rule: dependent clause first takes a comma, second usually takes none. Check question: which half could stand alone?"],
   ["6", "Teaching 2 — the joining word carries the meaning", "Because and since give a reason, when and while give a time, although and whereas set up a contrast. The point is the last card: “while he waited” and “because he waited” are the same event argued differently. Check question: which of the two blames him?"],
   ["3", "Examples", "Six sentences in three pairs: dependent clause first then second, contrast then time, and the cause the wrong way round then the right way round. Ask which one of the last pair is wrong before you say it. That error is the one Part B is built to catch."],
   ["8", "Part A — vocabulary", "Hand out the sheet. Six blanks from a nine-word bank, the example done and complex crossed out of the bank, two words left over at the end. Reveal one answer at a time."],
   ["10", "Part B — build the complex sentence", "Five pairs joined with the joining word given. The example is done for them. Do the first one aloud together, then release to pairs. Reveal as complete sentences. Watch for the cause reversed: “Because he missed his stop, he was not ready to go home” is grammatical and wrong."],
   ["7", "Part C — what the word does", "Five sentences labelled CAUSE, TIME or CONTRAST, and the words repeat. Since is the hard one — it does both jobs, so the sentence around it decides. Reveal one at a time."],
   ["5", "Part D — meaning and emphasis", "Two written answers: the while/because difference, and moving a dependent clause to the end to shift the weight of the sentence. Do the example together first. Reveal as complete sentences."],
   ["5", "Speaking — although and because", "Partner A gives one fact about their week; Partner B answers with a complex sentence using although. Then they swap and use because. Both partners speak, English only. Circulate and listen for the comma — you can hear it as a pause."],
   ["10", "Part E — rewrite your paragraph", "They rewrite the Lesson 7 theme paragraph with at least two complex sentences, one beginning with the dependent clause, and underline both. Not a new paragraph and not a new argument — the same claim, better sentences. Then the honesty line: clearer, or only longer? A defended “longer” is the better answer. Show the model rewrite only after they start."],
   ["2", "Part F — check your work", "Eight tick boxes in two columns. Tick only what is true and fix the rest. The two comma boxes are the ones to insist on."],
   ["2", "Exit ticket", "Part G, the last Part on the sheet. Hand that part in; the rest of the worksheet goes into the duotang."]],
  diff: "Foundation: Part A without the two extra words, Part B items 1–3 only, and a Part E rewrite of three sentences carrying one complex sentence. Bridge: add Part D question 2 and a fourth joining word in Part E. Anyone without a Lesson 7 paragraph rewrites their Lesson 1 paragraph instead.",
  assess: "Formative, not marked. Part B shows whether the comma rule has landed and whether the cause runs the right way round. Part E shows whether complex sentences are carrying an argument or only lengthening one. The exercise-book entry counts toward the unit’s exercise-book mark.",
  homework: "Finish the Part E rewrite if it is not done. Exercise-book entry: one sentence you joined today, and one line on what the joining word does that and, but or so could not.",
  watch: "The reversed cause — grammatical, wrong, and easy to miss when marking quickly. Students bolting although onto a sentence that holds no contrast. A comma after a dependent clause that comes second. And the student who rewrites the paragraph into something new: the argument stays, only the sentences change." },
 shape: [["Join two sentences into one", "warm-up, in your exercise book"], ["Today’s goals", "reading together"],
   ["Match the word", "vocabulary game"], ["Two clauses, one in charge", "instruction"],
   ["The joining word carries the meaning", "instruction"], ["Strong and weak joins", "examples"],
   ["Part A — vocabulary", "worksheet"], ["Part B — build the complex sentence", "worksheet"],
   ["Part C — what the word does", "worksheet"], ["Part D — meaning and emphasis", "written answers"],
   ["Although and because, out loud", "partner speaking"], ["Part E — rewrite your paragraph", "independent writing"],
   ["Part F — check your work", "tick boxes"], ["Exit ticket", "quick write"]],
 sequence: [
  { type: "title", label: "Today’s lesson" },
  { type: "warmup", label: "Warm-up", head: "Warm-up — in your exercise book",
    prompts: ["“I stayed inside. It was raining.” Join these two so that one explains the other.",
      "How many joining words could you use? Do they all mean the same thing?"] },
  { type: "goals", label: "Today’s goals", items: [
    "Build complex sentences with because, while, when, although and since.",
    "Punctuate a dependent clause correctly.",
    "Choose the joining word that carries the meaning you want."] },
  { type: "match", label: "Match the word", head: "Match the word to its meaning",
    bank: ["since", "cause", "subordinate", "emphasis", "complex", "whereas", "dependent", "contrast", "main clause", "although"],
    words: [
     ["complex", "having a main clause and a dependent clause"],
     ["main clause", "the part that can stand alone as a sentence"],
     ["dependent", "unable to stand alone; it needs the main clause"],
     ["subordinate", "another name for the dependent clause"],
     ["cause", "the reason something happens"],
     ["contrast", "a difference set against something else"],
     ["although", "a joining word showing contrast"],
     ["since", "a joining word showing cause or time"],
     ["whereas", "a joining word showing direct contrast"],
     ["emphasis", "the weight given to one part of a sentence"]] },
  { type: "vocab", label: "Key vocabulary", head: "Key vocabulary", words: [
     ["complex", "having a main clause and a dependent clause"],
     ["main clause", "the part that can stand alone as a sentence"],
     ["dependent", "unable to stand alone; it needs the main clause"],
     ["subordinate", "another name for the dependent clause"],
     ["cause", "the reason something happens"],
     ["contrast", "a difference set against something else"],
     ["although", "a joining word showing contrast"],
     ["since", "a joining word showing cause or time"],
     ["whereas", "a joining word showing direct contrast"],
     ["emphasis", "the weight given to one part of a sentence"]] },
  { type: "cards", label: "Two clauses, one in charge", tag: "Teaching 1 of 2", head: "Two clauses, one in charge", icon: "icon-pen.png", big: "One serves the other.", cards: [
    { title: "Equals, or not", body: "In a compound sentence the two halves are equals. In a complex sentence, one serves the other." },
    { title: "It cannot stand alone", body: "“Because the bus was late” is not a sentence. It needs a main clause to lean on." },
    { title: "Either order", body: "The dependent clause can come first or second. Both are correct.", tone: "teal" },
    { title: "The comma rule", body: "First, then a comma. Second, and usually no comma at all.", tone: "teal" }] },
  { type: "cards", label: "The joining word", tag: "Teaching 2 of 2", head: "The joining word carries the meaning", icon: "icon-read.png", big: "Same event. New argument.", cards: [
    { title: "Reason", body: "Because and since give a reason. Something happened, and this is why." },
    { title: "Time", body: "When and while give a time: one thing happens against the background of another." },
    { title: "Contrast", body: "Although and whereas set one thing against another. It is true in spite of it.", tone: "teal" },
    { title: "Same event, new argument", body: "“While he waited” and “because he waited” are one event, argued two ways.", tone: "teal" }] },
  { type: "rows", label: "Examples", tag: "Examples", head: "Strong and weak joins", pair: 2, rows: [
    ["Dependent first", "Because the bakery stayed open late, Arman had somewhere to be."],
    ["Dependent second", "Arman had somewhere to be because the bakery stayed open late."],
    ["Contrast", "Although the bakery stayed open late, he never bought anything."],
    ["Time", "While the bakery stayed open, he did his homework at the table."],
    ["Wrong way round", "Because he missed his stop, he was not ready to go home."],
    ["Right way round", "Because he was not ready to go home, he missed his stop."]] },
  { type: "handout", label: "Hand out the worksheet", note: "A, B and C together. Then D, your rewrite, and the check.",
    foot: "The exit ticket is the last Part. The whole sheet goes in your duotang at the end." },
  { type: "walk", part: "A" },
  { type: "reveals", part: "A" },
  { type: "walk", part: "B" },
  { type: "reveals", part: "B" },
  { type: "walk", part: "C" },
  { type: "reveals", part: "C" },
  { type: "walk", part: "D" },
  { type: "reveals", part: "D" },
  { type: "speaking", label: "Although and because", head: "Although and because, out loud", englishOnly: true,
    icon: "icon-friends.png", big: "Both partners speak.",
    prompt: "Partner A gives one fact about their week. Partner B answers with a complex sentence using although. Then swap, and use because.",
    frames: ["This week I ______.",
      "Although ______, ______.",
      "Because ______, ______.",
      "Since ______, I ______."] },
  { type: "walk", part: "E", note: "Fourteen lines on your sheet. The same argument as Lesson 7 — better sentences. Underline your two complex sentences." },
  { type: "rows", label: "Part E — one good rewrite", tag: "Part E · one good rewrite", head: "One good rewrite", pair: 2, rows: [
    ["Before", "Arman says nothing at home. He is the one who keeps the family moving."],
    ["After", "Although Arman says nothing at home, he is the one who keeps the family moving."],
    ["Before", "The bakery is warm. He stays there. He does not want to go home."],
    ["After", "He stays at the bakery because he does not want to go home."],
    ["Before", "He waited. The rain stopped."],
    ["After", "While he waited, the rain stopped."]] },
  { type: "walk", part: "F", note: "Eight boxes on your sheet. Tick one only when it is true. Fix anything you cannot tick." },
  { type: "exit", label: "Exit ticket", part: "G", note: "Hand me your exit ticket. The worksheet stays in your duotang." },
  { type: "next", label: "Next class", title: "Finding Your Details", sub: "Back to your Lesson 1 paragraph — and counting the details that are really specific.", icon: "icon-pen.png" },
  { type: "rows", label: "Agendas", tag: "Before you go", head: "Take out your agenda", rows: [
    ["Homework", "Finish your Part E rewrite."],
    ["Exercise book", "One sentence you joined, and what the joining word does."],
    ["Bring", "Your exercise book, every class."]] }],
 worksheet: {
  objective: "Build complex sentences and choose the joining word that carries your meaning.",
  outcomes: "W5 complex sentences with connecting words  •  W12 punctuation  •  W11 subject/verb agreement",
  parts: [
   { id: "A", title: "Vocabulary", kind: "cloze", weight: 6, bankCols: 3,
     instr: "Fill each blank with a word from the word bank. Each word is used once. Two words are extra. Cross out each word as you use it.",
     bank: ["contrast", "main clause", "emphasis", "complex", "although", "cause", "whereas", "dependent", "subordinate"],
     crossed: ["complex"],
     example: { text: "A main clause plus a dependent clause is", ans: "complex", tail: "" },
     items: [
      { text: "The part that can stand alone as a sentence is the", ans: "main clause", tail: "" },
      { text: "A clause that cannot stand alone is", ans: "dependent", tail: "" },
      { text: "The reason something happens is the", ans: "cause", tail: "" },
      { text: "A difference set against something else is a", ans: "contrast", tail: "" },
      { text: "A joining word showing contrast is", ans: "although", tail: "" },
      { text: "Another name for the dependent clause is the", ans: "subordinate", tail: "" }],
     how: "Read the whole sentence first, then choose the word that fits it. Cross each word out of the bank as you use it. Two words are left over at the end — that is meant to happen." },
   { id: "B", title: "Build the complex sentence", kind: "lines", weight: 6, lines: 2,
     instr: "Join each pair into one complex sentence using the joining word given. A comma follows the dependent clause only when it comes first.",
     example: { text: "(because) He missed his stop. He was not ready to go home.", ans: "Because he was not ready to go home, he missed his stop." },
     items: [
      { text: "(although) She understood every word. She did not answer.", ans: "Although she understood every word, she did not answer." },
      { text: "(while) My mother filled out the forms. I translated the questions.", ans: "While my mother filled out the forms, I translated the questions." },
      { text: "(since) We moved in July. I have not seen my cousins.", ans: "Since we moved in July, I have not seen my cousins." },
      { text: "(when) The shop bell rang. Everyone looked up.", ans: "When the shop bell rang, everyone looked up." },
      { text: "(because) The bus was full. He waited for the next one.", ans: "Because the bus was full, he waited for the next one." }],
     how: "Decide which half is the reason, or the time, or the thing being set against the other — that half takes the joining word. If it comes first, put a comma after it. If it comes second, no comma. Check the cause is the right way round before you write it down." },
   { id: "C", title: "What the word does", kind: "cloze", weight: 5, bankCols: 3,
     instr: "Write CAUSE, TIME or CONTRAST in the blank beside each sentence. The words are used more than once.",
     bank: ["CONTRAST", "CAUSE", "TIME"], crossed: [],
     example: { text: "Although the bakery stayed open late, he never bought anything.", ans: "CONTRAST", tail: "" },
     items: [
      { text: "Because the bakery stayed open late, he had somewhere to be.", ans: "CAUSE", tail: "" },
      { text: "While he waited, the rain stopped.", ans: "TIME", tail: "" },
      { text: "Since he arrived, he has not spoken in class.", ans: "TIME", tail: "" },
      { text: "She spoke three languages, whereas her teacher spoke one.", ans: "CONTRAST", tail: "" },
      { text: "When the shop bell rang, everyone looked up.", ans: "TIME", tail: "" }],
     how: "Cover the joining word with your finger and ask what it is doing. Telling you why? CAUSE. Telling you when? TIME. Setting two things against each other? CONTRAST. Since does two jobs, so read the whole sentence before you decide." },
   { id: "D", title: "Meaning and emphasis", kind: "lines", weight: 4, lines: 5,
     instr: "Answer in complete sentences.",
     example: { text: "Which is stronger: “He waited and the rain stopped” or “While he waited, the rain stopped”? Why?", ans: "The second one is stronger, because while turns the waiting into background and puts the weight on the rain stopping. The first gives both halves the same weight." },
     items: [
      { text: "“While he waited” and “because he waited” describe the same event. Explain the difference in meaning.", ans: "While makes the waiting the background for something else. Because makes the waiting the reason for it. The event is the same, but the argument about it is different." },
      { text: "Rewrite this so that the emphasis falls on the second half: “Although she understood every word, she did not answer.”", ans: "She did not answer, although she understood every word. Moving the dependent clause to the end puts the weight on her silence." }],
     how: "Answer the question in your first sentence, then explain it. Use the words cause, contrast, time and emphasis where they fit — that is what you learned them for." },
   { id: "E", title: "Rewrite your paragraph", kind: "open", weight: 10, lines: 14,
     instr: "Take out your Lesson 7 theme paragraph and rewrite it here so that it contains at least two complex sentences, one of them beginning with the dependent clause. Underline both. Check every comma. Then, on the last line, answer this: did the complex sentences make your argument clearer, or only longer?",
     example: { ans: "One rewritten sentence: Although Arman says nothing at home, he is the one who keeps the family moving." },
     how: "You are not writing a new paragraph. Keep the same argument as Lesson 7 and change the sentences. Underline your two complex sentences so I can find them. Then be honest on the last line — if it only got longer, say so and you will have learned the more useful thing." },
   { id: "F", title: "Check your work", kind: "check",
     instr: "Read your work back. Tick each box when it is true.",
     checks: ["Every complex sentence has a main clause.",
       "A comma follows the dependent clause when it comes first.",
       "No comma when the dependent clause comes second.",
       "My joining word matches my meaning: cause, time or contrast.",
       "My paragraph has at least two complex sentences.",
       "One of them begins with the dependent clause.",
       "My subjects and verbs agree.",
       "I answered the honesty question on the last line."],
     how: "Go back through the sheet and tick a box only when it is true. Fix anything you cannot tick." },
   { id: "G", title: "Exit ticket", kind: "exit", lines: 2,
     instr: "Answer, then hand this part to me.",
     items: [
      { text: "Write one sentence using although about learning English." },
      { text: "Which joining word do you overuse? Name the one you will use instead next time." }],
     how: "Two short answers. Hand me this part only — the rest of the sheet stays in your duotang." }] }
};
